### ISSUE TITLE
Abnormal executor termination

### ISSUE THREAD

**Issue by FlorianOtel** [mesosphere/kubernetes-mesos#105]
Hi, I'm trying to replicate the example in the README.md and I'm running into problems: 

Setup: 

- 3  Mesos nodes (1 master / "mesos0" + 2 slaves / "mesos1" and "mesos2" ) on top of  Ubuntu 14.04
- Running marathon & Chronos with Docker executor (tested Marathon).
- Installed etcd on the master ("mesos0") natively
- Built & installed from source "kubernetes-mesos" (had a broken "kubernetes-mesos" library dependency on "libmesos-0.21.0.so" vs existing "libmesos-0.21.1"  when attempting to run from the "jdef/kubernetes-mesos:build-latest" container, can log a different issue if needed). 

Problem:

When attempting to launch the provided "examples/pod-nginx.json" the "kubernetes-mesos" log complains: 

I1210 10:42:40.738986 00684 scheduler.go:196] Received offers
I1210 10:42:41.413256 00684 scheduler.go:246] Received status update task_id:<value:"43baf91f-8059-11e4-ad2b-08002786ce5e" > state:TASK_LOST message:"Abnormal executor termination" slave_id:<value:"20141209-094241-167841964-5050-991-1" > timestamp:1.418208158019543e+09
E1210 10:42:41.413363 00684 scheduler.go:381] Task lost: 'task_id:<value:"43baf91f-8059-11e4-ad2b-08002786ce5e" > state:TASK_LOST message:"Abnormal executor termination" slave_id:<value:"20141209-094241-167841964-5050-991-1" > timestamp:1.418208158019543e+09 '
I1210 10:42:43.735722 00684 scheduler.go:196] Received offers

I have several other related issues ("stock" Kuberentes pods -- i.e. this https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/guestbook/README.md ) but will take one at a time. 

Let me know if you need additional log / debug info (omitted here for brevity)

Thanks, 

Florian

**Comment by jdef** [comment]
Closing out due to inactivity. If this is still a problem, please re-open and provide additional details. Thanks!
