### ISSUE TITLE
Setting up kubernetes-mesos on ubuntu boxes local intranet

### ISSUE THREAD

**Issue by sourav82** [mesosphere/kubernetes-mesos#113]
I was trying to setup kubernetes-mesos framework with 1 mesos master and 3 mesos slaves (no cloud, just setting up taking 4 ubuntu boxes in private intranet). Marathon framework with mesos was configured successfully.

I installed kubernetes-mesos in the mesos master as documented in https://github.com/mesosphere/kubernetes-mesos. I started etcd, kubernetes-mesos and controller-manager in this mesos master node.

I would like to know which services to be started in mesos slaves for kubernetes master to detect them as minions.

**Comment by mikesplain** [comment]
I don't think you need to start any process. I've been running a Dev cluster of the similar size and all my nodes were added as minions automatically.

**Comment by sourav82** [comment]
Thanks @mikesplain. It worked by starting mesos slave with --ip parameters. Now kubernetes able to find the minions properly.
