### ISSUE TITLE
Service takes host port (instead of container ports) to group pods

### ISSUE THREAD

**Issue by sourav82** [mesosphere/kubernetes-mesos#116]
My service looks like below -

{
  "apiVersion": "v1beta1",
  "kind": "Service",
  "id": "app",
  "selector": {
    "name": "app"
  },
  "containerPort": 80,
  "port": 8585,
}
I've pods created with below replication controller config -
{
  "id": "app",
  "apiVersion": "v1beta1",
  "kind": "ReplicationController",
  "desiredState": {
    "replicas": 3,
    "replicaSelector": {"name": "app"},
    "podTemplate": {
      "desiredState": {
        "manifest": {
          "version": "v1beta1",
          "id": "app",
          "containers": [
            {
              "name": "app",
              "image": "10.227.125.10:5000/app-kubernetes",
              "ports": [{"containerPort": 80, "hostPort": 31020}]
             }
          ]
        }
      },
      "labels": {"name": "app"}
    }
  },
  "labels": {"name": "app"}
}
After 3 pods created by this replication controller, I start the service. But not able to access the application using http://10.227.125.10:8585/ (10.227.125.10 is the IP of the system where I created the service).

But, if I change the service to use port 31020 as container port, then I am able to use the service from IE in port 8585. As per documentation, "containerPort" of service should have the port of the container inside the pods. In this example, container port inside pod is 80 and host port is 31020. But the service is behaving differently. Please help here what wrong I am doing in setting it up.

Thanks & Regards,
Sourav

**Comment by jdef** [comment]
Default Docker networking is not compatible with stock kubernetes, see
details in #115

I've found it simpler to use named ports. For example, in your pod
template: `"ports": [{"containerPort": 80, "hostPort": 31020, "name":
"myapp"}]`. Then, in your service spec change containerPort to "myapp".

On Wed, Jan 7, 2015 at 5:13 AM, sourav82 <notifications@github.com> wrote:

> My service looks like below -
>
> {
> "apiVersion": "v1beta1",
> "kind": "Service",
> "id": "app",
> "selector": {
> "name": "app"
> },
> "containerPort": 80,
> "port": 8585,
> }
> I've pods created with below replication controller config -
> {
> "id": "app",
> "apiVersion": "v1beta1",
> "kind": "ReplicationController",
> "desiredState": {
> "replicas": 3,
> "replicaSelector": {"name": "app"},
> "podTemplate": {
> "desiredState": {
> "manifest": {
> "version": "v1beta1",
> "id": "app",
> "containers": [
> {
> "name": "app",
> "image": "10.227.125.10:5000/app-kubernetes",
> "ports": [{"containerPort": 80, "hostPort": 31020}]
> }
> ]
> }
> },
> "labels": {"name": "app"}
> }
> },
> "labels": {"name": "app"}
> }
> After 3 pods created by this replication controller, I start the service.
> But not able to access the application using http://10.227.125.10:8585/
> (10.227.125.10 is the IP of the system where I created the service).
>
> But, if I change the service to use port 31020 as container port, then I
> am able to use the service from IE in port 8585. As per documentation,
> "containerPort" of service should have the port of the container inside the
> pods. In this example, container port inside pod is 80 and host port is
> 31020. But the service is behaving differently. Please help here what wrong
> I am doing in setting it up.
>
> Thanks & Regards,
> Sourav
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/116>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by sourav82** [comment]
Thanks @jdef . I used named ports and it is working like a charm!
