### ISSUE TITLE
Is there any way to express service dependencies so that kubectl creates them in order?

### ISSUE THREAD

**Issue by sourav82** [mesosphere/kubernetes-mesos#119]
I have 2 services. One containing 2 pod replicas for a web application which is dependent on another backend service having pod (2 replicas) for mysql containers.

Web application uses environment variables set by backend db service. I've all the json inside same directory.

Is there any way to express the dependencies so that kubectl always create (and run) backend pods and services before it starts the web application service?

**Comment by jdef** [comment]
What you're asking for is not currently supported in kubernetes. You may be
interested in these discussions:

* https://github.com/GoogleCloudPlatform/kubernetes/issues/2385
* https://github.com/GoogleCloudPlatform/kubernetes/issues/1899


On Fri, Jan 9, 2015 at 7:02 AM, sourav82 <notifications@github.com> wrote:

> I have 2 services. One containing 2 pod replicas for a web application
> which is dependent on another backend service having pod (2 replicas) for
> mysql containers.
>
> Web application uses environment variables set by backend db service. I've
> all the json inside same directory.
>
> Is there any way to express the dependencies so that kubectl always create
> (and run) backend pods and services before it starts the web application
> service?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/119>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by sourav82** [comment]
@jdef Thanks for clarification.
