### ISSUE TITLE
Any UI for kubernetes-mesos framework?

### ISSUE THREAD

**Issue by sourav82** [mesosphere/kubernetes-mesos#120]
I was wondering if there is any Marathon like UI for managing (create, delete, update etc.) docker tasks (in terms of pods, replicationControllers, services etc.) for kubernetes-mesos framework?

**Comment by jdef** [comment]
There is a default kubernetes UI, though there's not a ton of functionality there yet. Future release of Kubernetes will (probably) expand on this.

If you're running on GCE you can do this in a couple of steps:
* First, you'll need to add a few iptables rules on your master node, once you determine the port that the 'kubernetes-ro' service (for example) is running on:

```shell
$ sudo iptables-save|grep -e kubernetes  # 60951, in this case, is the service port on this host
-A KUBE-PROXY -d 10.10.10.90/32 -p tcp -m comment --comment kubernetes-ro -m tcp --dport 80 -j DNAT --to-destination 10.223.113.227:60951
-A KUBE-PROXY -d 10.10.10.210/32 -p tcp -m comment --comment kubernetes -m tcp --dport 443 -j DNAT --to-destination 10.223.113.227:38526

# now update your firewall rules to map incoming traffic on port 80 to the kubernetes-ro service
# 10.223.113.227 here matches $servicehost, the address the API server is bound to
$ sudo iptables -t nat -A KUBE-PROXY -d 10.223.113.227/32 -p tcp -m comment --comment \
    kubernetes-ro -m tcp --dport 80 -j DNAT --to-destination 10.223.113.227:60951
$ sudo iptables -A INPUT -i eth0 -p tcp -m state --state NEW,ESTABLISHED -m tcp --dport 60951 \
    -j ACCEPT
```
* Second, you'll need add a firewall rule in the GCE console that opens up port 80 for your development cluster.

There's a similar firewall configuration process documented in the [Kubernetes-Mesos on GCE tutorial][1].

[1]: https://mesosphere.com/docs/tutorials/kubernetes-mesos-gcp/

**Comment by sourav82** [comment]
Thanks @jdef for your clarification. Will do this way.
