### ISSUE TITLE
overlap between mesos TaskInfo.DiscoveryInfo and k8s labels?

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#126]
Would be it be useful to automatically translate pod labels to [TaskInfo.DiscoveryInfo][2] (or to ExecutorInfo.DiscoveryInfo)? For example:
* discovery.k8sm/visibility ~=> TaskInfo.DiscoveryInfo.Visibility
* discovery.k8sm/name ~=> TaskInfo.DiscoveryInfo.name
* discovery.k8sm/environment ~=> TaskInfo.DiscoveryInfo.environment
* discovery.k8sm/location ~=> TaskInfo.DiscoveryInfo.location
* discovery.k8sm/version ~=> TaskInfo.DiscoveryInfo.version

I'm guessing [mesos-dns][1] will probably move in the direction of using discovery info to construct SRV records. May be some overlap here with #125.

[1]: https://github.com/mesosphere/mesos-dns
[2]: https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L1074

**Comment by timothysc** [comment]
I may be missing something, but I don't see how you can add it to the TaskInfo b/c that implies you know the service re-director prior to launching.   k8's dns linkage is only through services, and you only know the service ip "after" it's been started. 

Unless you can somehow update the TaskInfo.Discovery struct on the fly via a framework message.?.?.?

**Comment by jdef** [comment]
There's an architectural disconnect between k8s services and mesos
"services" as reported by mesos-dns:
* kubernetes services are spec'd independently from pods, and may be backed
by specialized load balancers; pods can back more than 1 service
* mesos-dns (current) SRV's reference the tasks directly (and each k8sm pod
is a task)

Would it be interesting for mesos-dns to actually provide records for both?
* k8sm pods (tasks) would get IP and SRV records (useful when clients
actually want the A records for all the pods, instead of a load-balanced
service)
* some separate mesos-dns plugin would monitor k8sm endpoints and create
IP, and SRV records for those (could be useful when the service is realized
via some advanced load balancer)


On Fri, Jan 23, 2015 at 9:43 AM, Timothy St. Clair <notifications@github.com
> wrote:

> I may be missing something, but I don't see how you can add it to the
> TaskInfo b/c that implies you know the service re-director prior to
> launching. k8's dns linkage is only through services, and you only know the
> service ip "after" it's been started.
>
> Unless you can somehow update the TaskInfo.Discovery struct on the fly via
> a framework message.?.?.?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/126#issuecomment-71202418>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by kozyraki** [comment]
I could be wrong (forgive my limited understanding of K8S) but there seems to be a very simple solution here. Assume this [example K8S service](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services_overview.png) that includes a number of pods behind a proxy. We want this service to be reachable by clients at myapp.k8s.mesos. Then:
- when K8S launches the proxy, it sets the discovery info so that it becomes discoverable as myapp.k8s.mesos (myapp.domain in general) through Mesos-DNS. All clients use that, go to the proxy and then the proxy does its magic. 
- The next problem is how the proxy finds its pods. We can actually keep Mesos-DNS out of this if we want, using whatever approach is used right now. But if needed, Mesos-DNS can also play a role. If all myapp pods are launched in a way that generates the same name on Mesos-DNS (e.g., myapp-pod.k8s.mesos), a mesos-DNS lookup for this name will return multiple [A] and [SRV] records that describe all pods. 

Does this make any sense?

**Comment by jdef** [comment]
The k8s proxy does not run as a mesos task, instead it is a component of k8s that (currently) spins up as a child proc of the executor. The proxy then watches the k8s services registry for Service and Endpoint (pod availability) changes. Based on those things it manages iptables nat rules, as well as starts/stops goroutines to proxy tcp/udp connections (see https://github.com/mesosphere/kubernetes-mesos/tree/master/docs#networking). It's also possible to run a k8sm proxy process manually on an arbitrary server: for example, you wanted to use your mesos master nodes as load balancers for external clients of k8sm services (your Service specifications would define PublicIPs = { list of mesos masters running the k8sm proxy }).

So, when you say "...\[the proxy\] sets the discovery info so that it becomes discoverable.." that doesn't jive with my understanding: services are not launched as mesos tasks, therefore they have no discovery info.

If other mesos things (non-k8sm tasks) wanted to find kubernetes-mesos services, then it'd be great if mesos-dns had a plugin that watched for k8sm Service changes (via the k8sm API server) and updated it's SRV and A records accordingly. The initial version of this plugin could ignore k8sm tasks all together, since they're normally not intended to be exposed directly as services anyway.

And these SRV registrations probably only mean anything to a non-k8sm client if a k8sm Service has specified PublicIPs, otherwise the (dynamically allocated, NAT'd) IP's that are normally associated with k8sm services won't make much sense to other things in the cluster.

Does that help to give some clarity?

**Comment by jdef** [comment]
experimental support for publishing discovery-info for tasks was implemented for #256, closing this out. dealing with k8s services can be dealt with in a separate GH ticket.
