### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by brandon-adams** [mesosphere/kubernetes-mesos#127]
Hi all,

I'm trying to run the latest stable kubernetes-mesos with Mesos 0.21.1 (running on Ubuntu 12.04 and OpenStack)  and I'm getting the below error from my mesos slaves:

> WARNING: Logging before InitGoogleLogging() is written to STDERR
> I0122 19:50:55.556480 21516 fetcher.cpp:76] Fetching URI 'http://23.23.23.48:10251/kube-proxy'
> I0122 19:50:55.556727 21516 fetcher.cpp:126] Downloading 'http://23.23.23.48:10251/kube-proxy' to '/tmp/mesos/slaves/20150122-184520-806819607-5050-18244-S0/frameworks/20150122-184520-806819607-5050-18244-0001/executors/KubeleteExecutorID/runs/540d92d3-676d-498f-b959-35be29b5cd5a/kube-proxy'
> I0122 19:50:55.671934 21516 fetcher.cpp:76] Fetching URI 'http://23.23.23.48:10251/k8sm-executor'
> I0122 19:50:55.672111 21516 fetcher.cpp:126] Downloading 'http://23.23.23.48:10251/k8sm-executor' to '/tmp/mesos/slaves/20150122-184520-806819607-5050-18244-S0/frameworks/20150122-184520-806819607-5050-18244-0001/executors/KubeleteExecutorID/runs/540d92d3-676d-498f-b959-35be29b5cd5a/k8sm-executor'
> ./k8sm-executor: error while loading shared libraries: libmesos-0.21.1.so: cannot open shared object file: No such file or directory

I was getting this error earlier, when starting the *k8sm-scheduler*, but that was resolved by setting the LD_LIBRARY_PATH=/usr/local/lib environment variable. I have gone on each of my slaves and set that variable globally but the error still persists. Any ideas?

**Comment by jdef** [comment]
Sounds like you might be missing `/usr/local/lib` from your ld configuration on both the masters and the slaves. On my GCE node I see that path listed here.

```shell
jclouds@development-3692-8fa:~$ cat /etc/ld.so.conf.d/libc.conf
# libc default configuration
/usr/local/lib
```

After you update your configuration you'll want to `sudo ldconfig`. You may need to restart the slave services to pick up the changes (doesn't hurt to try without it first).

**Comment by brandon-adams** [comment]
Thanks @jdef, that solved that error. Though it seems like I have to run `sudo ldconfig` whenever I restart, as the k8sm-scheduler didn't pick it up after a restart. Thanks again.

**Comment by Fei-Guang** [comment]
export LD_LIBRARY_PATH="/home/ubuntu/mesos-0.25.0//build/src/.libs/"

**Comment by jdef** [comment]
this ticket is quite dated and was filed against a version of k8s-mesos that was compiled against a version of mesos-go that relied upon the native mesos bindings. this has long since been resolved since the mesos-go dependencies were updated a while back to avoid dependencies on the native mesos library. not sure why it's getting attention now but I see no need to re-open this ticket.

**Comment by cschneider** [comment]
I can reproduce the problem with mesos-0.27.2. 
Mesos only worked after manually executing export LD_LIBRARY_PATH and sudo ldconfig.
Without it the test frameworks failed.

I would have expected make install to already set this up correctly. Of course it is very well possible that I simply did something wrong.

**Comment by jdef** [comment]
@cschneider it's very strange to hear this is happening to you. k8s-mesos no longer links against the shared libraries produced by mesos builds. are you sure that you're seeing a failure due to a missing libmesos dependency?

**Comment by cschneider** [comment]
I think the error was shown when running the C test framework. So probably my issue was rather with the test framework than with mesos itself. Does that make sense?

**Comment by jdef** [comment]
Yes, that makes sense. In that case, it sounds like this bug is perhaps
filed against the wrong project? If you're experiencing problems with
building and installing mesos itself I recommend posting a question the
mesos user mailing list. see http://mesos.apache.org/community/

**Comment by cschneider** [comment]
Thanks. Will do so.
