### ISSUE TITLE
Running heapster for Kubernetes cluster monitoring on Kubernetes-mesos framework

### ISSUE THREAD

**Issue by sourav82** [mesosphere/kubernetes-mesos#137]
I have set up kubernetes-mesos framework having two minions as below -

root@root-G6:/EBS/src/github.com/GoogleCloudPlatform/heapster# kubectl get minions
NAME                LABELS
10.227.125.10       <none>
10.227.125.3        <none>

I wanted to make use of Heapster for Kubernetes cluster monitoring. cAdvisor were running in pods on each minions. Below are the pods -

root@etp-ProLiant-DL180-G6:/EBS/prometheus# kubectl get pods

NAME                                 |  IMAGE(S)             |                   HOST                        |  LABELS                  |                 STATUS
------------------------------------ | --------------------- | -------------------------------------------- | ----------------------- | ---------------------------
cf7bfe93-a78e-11e4-b11e-984be16ce9ba   google/cadvisor:0.8.0                    10.227.125.10/10.227.125.10   name=cadvisor                            Running
------------------------------------ | --------------------- | -------------------------------------------- | ----------------------- | -----------------------
cf7bb0a1-a78e-11e4-b11e-984be16ce9ba   google/cadvisor:0.8.0                    10.227.125.3/10.227.125.3     name=cadvisor                            Running
------------------------------------ | --------------------- | -------------------------------------------- | ----------------------- | -----------------------
f95a0a29-a78e-11e4-b11e-984be16ce9ba   kubernetes/heapster_influxdb:v0.2        10.227.125.10/10.227.125.10   name=influxGrafana                       Running
                                       kubernetes/heapster_grafana:v0.2
------------------------------------ | --------------------- | -------------------------------------------- | ----------------------- | -----------------------
773cf11c-a78f-11e4-b11e-984be16ce9ba   kubernetes/heapster:v0.5                 10.227.125.10/10.227.125.10   name=heapster,uses=monitoring-influxdb   Running
------------------------------------ | --------------------- | -------------------------------------------- | ----------------------- | -----------------------

But heapster is not able to fetch data from cAdvisor as it is not able to connect with it. 

While executing curl -v http://10.227.125.3:10250/stats/heapster/heapster/, below error comes -

* Hostname was NOT found in DNS cache
*   Trying 10.227.125.3...
* Connected to 10.227.125.3 (10.227.125.3) port 10250 (#0)
> GET /stats/heapster/heapster/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.227.125.3:10250
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 29 Jan 2015 09:19:06 GMT
< Content-Length: 2
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 10.227.125.3 left intact
{}

Is there any specific configuration to set it up? I'm using local ubuntu boxes as Kubernetes cluster. Not using any cloud like GCE, AWS etc.

**Comment by jdef** [comment]
cadvisor support is not yet integrated into kubernetes-mesos. the
/stats/... call you're making requires cadvisor support.

On Thu, Jan 29, 2015 at 6:54 AM, sourav82 <notifications@github.com> wrote:

> I have set up kubernetes-mesos framework having two minions as below -
>
> root@root-G6:/EBS/src/github.com/GoogleCloudPlatform/heapster# kubectl
> get minions
> NAME LABELS
> 10.227.125.10
> 10.227.125.3
>
> I wanted to make use of Heapster for Kubernetes cluster monitoring.
> cAdvisor were running in pods on each minions. Below are the pods -
>
> root@etp-ProLiant-DL180-G6:/EBS/prometheus# kubectl get pods
>   NAME IMAGE(S) HOST LABELS STATUS
>
> cf7bfe93-a78e-11e4-b11e-984be16ce9ba google/cadvisor:0.8.0
> 10.227.125.10/10.227.125.10 name=cadvisor Running
> ------------------------------------ | --------------------- |
> -------------------------------------------- | ----------------------- |
> -----------------------
> cf7bb0a1-a78e-11e4-b11e-984be16ce9ba google/cadvisor:0.8.0
> 10.227.125.3/10.227.125.3 name=cadvisor Running
> ------------------------------------ | --------------------- |
> -------------------------------------------- | ----------------------- |
> -----------------------
> f95a0a29-a78e-11e4-b11e-984be16ce9ba kubernetes/heapster_influxdb:v0.2
> 10.227.125.10/10.227.125.10 name=influxGrafana Running
> kubernetes/heapster_grafana:v0.2
> ------------------------------------ | --------------------- |
> -------------------------------------------- | ----------------------- |
> -----------------------
> 773cf11c-a78f-11e4-b11e-984be16ce9ba kubernetes/heapster:v0.5
> 10.227.125.10/10.227.125.10 name=heapster,uses=monitoring-influxdb Running
> ------------------------------------ | --------------------- |
> -------------------------------------------- | ----------------------- |
> -----------------------
>
> But heapster is not able to fetch data from cAdvisor as it is not able to
> connect with it.
>
> While executing curl -v http://10.227.125.3:10250/stats/heapster/heapster/,
> below error comes -
>
>    - Hostname was NOT found in DNS cache
>    - Trying 10.227.125.3...
>    - Connected to 10.227.125.3 (10.227.125.3) port 10250 (#0) > GET
>    /stats/heapster/heapster/ HTTP/1.1 > User-Agent: curl/7.35.0 > Host:
>    10.227.125.3:10250 > Accept: */* > < HTTP/1.1 200 OK < Date: Thu, 29
>    Jan 2015 09:19:06 GMT < Content-Length: 2 < Content-Type: text/plain;
>    charset=utf-8 <
>    - Connection #0 to host 10.227.125.3 left intact {}
>
> Is there any specific configuration to set it up? I'm using local ubuntu
> boxes as Kubernetes cluster. Not using any cloud like GCE, AWS etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/137>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by sourav82** [comment]
@jdef, is there any plan for this integration in near future?

**Comment by jdef** [comment]
I'm not sure when support for cadvisor (#18) will be implemented. Over the
next couple of months, one of the goals is to test k8sm at scale. That
becomes a little easier to quantify if we can get good metrics, so perhaps
cadvisor support will be tackled as part of those efforts.

On Thu, Jan 29, 2015 at 11:30 PM, sourav82 <notifications@github.com> wrote:

> @jdef <https://github.com/jdef>, is there any plan for this integration
> in near future?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/137#issuecomment-72152803>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by jdef** [comment]
closing this out, please re-open if you have additional questions on this topic.
