### ISSUE TITLE
create-binding-failure

### ISSUE THREAD

**Issue by brandon-adams** [mesosphere/kubernetes-mesos#148]
Hello again. I've upgraded kubernetes-mesos to the latest master to pull in some recent changes, and now I am unable to create any pods. I'm pulling this error from the scheduler log: 
```
I0209 21:31:26.092462    8674 plugin.go:227] Try to schedule pod devops-cluster-pod
I0209 21:31:26.092816    8674 pod_task.go:120] Evaluating port range {31000:32000} 31080
I0209 21:31:26.110871    8674 plugin.go:158] Attempting to bind devops-cluster-pod to mesos-slave-6
I0209 21:31:26.134424    8674 plugin.go:160] launching task : &{0067ed69-b0a3-11e4-857e-fa163e3c002e 0xc20821ba20 name:"PodTask" task_id:<value:"0067ed69-b0a3-11e4-857e-fa163e3c002e" > slave_id:<value:"20150209-162605-806819607-5050-1837-S33" > resources:<name:"cpus" type:SCALAR scalar:<value:0.25 > > resources:<name:"mem" type:SCALAR scalar:<value:64 > > resources:<name:"ports" type:RANGES ranges:<range:<begin:31080 end:31080 > > > executor:<executor_id:<value:"KubeleteExecutorID" > command:<uris:<value:"http://23.23.23.48:10251/kube-proxy" executable:true > uris:<value:"http://23.23.23.48:10251/k8sm-executor" executable:true > value:"./k8sm-executor -v=2 -hostname_override=0.0.0.0 -allow_privileged=false -api_servers=23.23.23.48:8888 -etcd_servers=http://23.23.23.48:4001" > name:"Kubelet Executor" source:"kubernetes" > data:"typemeta:\n  kind: \"\"\n  apiversion: \"\"\nobjectmeta:\n  name: devops-cluster-pod\n  namespace: default\n  selflink: /api/v1beta1/boundPods/devops-cluster-pod\n  uid: 0047b18e-b0a3-11e4-97ba-fa163e3c002e\n  resourceversion: \"\"\n  creationtimestamp: 2015-02-09T21:31:25Z\n  labels: {}\n  annotations: {}\nspec:\n  volumes: []\n  containers:\n  - name: apache-modcluster\n    image: sewatech/modcluster\n    command: []\n    workingdir: \"\"\n    ports:\n    - name: \"\"\n      hostport: 31080\n      containerport: 80\n      protocol: TCP\n      hostip: \"\"\n    env:\n    - name: KUBERNETES_RO_SERVICE_HOST\n      value: 10.10.10.51\n    - name: KUBERNETES_RO_SERVICE_PORT\n      value: \"80\"\n    - name: KUBERNETES_RO_PORT\n      value: tcp://10.10.10.51:80\n    - name: KUBERNETES_RO_PORT_80_TCP\n      value: tcp://10.10.10.51:80\n    - name: KUBERNETES_RO_PORT_80_TCP_PROTO\n      value: tcp\n    - name: KUBERNETES_RO_PORT_80_TCP_PORT\n      value: \"80\"\n    - name: KUBERNETES_RO_PORT_80_TCP_ADDR\n      value: 10.10.10.51\n    - name: KUBERNETES_SERVICE_HOST\n      value: 10.10.10.243\n    - name: KUBERNETES_SERVICE_PORT\n      value: \"443\"\n    - name: KUBERNETES_PORT\n      value: tcp://10.10.10.243:443\n    - name: KUBERNETES_PORT_443_TCP\n      value: tcp://10.10.10.243:443\n    - name: KUBERNETES_PORT_443_TCP_PROTO\n      value: tcp\n    - name: KUBERNETES_PORT_443_TCP_PORT\n      value: \"443\"\n    - name: KUBERNETES_PORT_443_TCP_ADDR\n      value: 10.10.10.243\n    memory: 0\n    cpu: 0\n    volumemounts: []\n    livenessprobe: null\n    lifecycle: null\n    terminationmessagepath: \"\"\n    privileged: false\n    imagepullpolicy: \"\"\n  restartpolicy:\n    always: {}\n    onfailure: null\n    never: null\n  dnspolicy: ClusterFirst\n  nodeselector: {}\n  host: \"\"\n"  id:<value:"20150209-162605-806819607-5050-1837-O3565" > framework_id:<value:"20150209-162605-806819607-5050-1837-0009" > slave_id:<value:"20150209-162605-806819607-5050-1837-S33" > hostname:"mesos-slave-6" resources:<name:"cpus" type:SCALAR scalar:<value:4 > role:"*" > resources:<name:"mem" type:SCALAR scalar:<value:6962 > role:"*" > resources:<name:"disk" type:SCALAR scalar:<value:25116 > role:"*" > resources:<name:"ports" type:RANGES ranges:<range:<begin:31000 end:32000 > > role:"*" >  false false /pods/default/devops-cluster-pod}
I0209 21:31:26.136377    8674 plugin.go:375] attempting to yield a pod
I0209 21:31:26.815098    8674 scheduler.go:199] Received status update task_id:<value:"0067ed69-b0a3-11e4-857e-fa163e3c002e" > state:TASK_FAILED message:"create-binding-failure" slave_id:<value:"20150209-162605-806819607-5050-1837-S33" > timestamp:1.423517486913847e+09 
E0209 21:31:26.815281    8674 scheduler.go:303] Task failed: 'task_id:<value:"0067ed69-b0a3-11e4-857e-fa163e3c002e" > state:TASK_FAILED message:"create-binding-failure" slave_id:<value:"20150209-162605-806819607-5050-1837-S33" > timestamp:1.423517486913847e+09 '
```

And the following from the minion/slave error log:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0209 21:31:26.528070  1262 fetcher.cpp:76] Fetching URI 'http://23.23.23.48:10251/kube-proxy'
I0209 21:31:26.528355  1262 fetcher.cpp:126] Downloading 'http://23.23.23.48:10251/kube-proxy' to '/var/lib/mesos/slaves/20150209-162605-806819607-5050-1837-S33/frameworks/20150209-162605-806819607-5050-1837-0009/executors/KubeleteExecutorID/runs/742ed9b9-996f-4559-a41c-87b49e89bd85/kube-proxy'
I0209 21:31:26.617662  1262 fetcher.cpp:76] Fetching URI 'http://23.23.23.48:10251/k8sm-executor'
I0209 21:31:26.617815  1262 fetcher.cpp:126] Downloading 'http://23.23.23.48:10251/k8sm-executor' to '/var/lib/mesos/slaves/20150209-162605-806819607-5050-1837-S33/frameworks/20150209-162605-806819607-5050-1837-0009/executors/KubeleteExecutorID/runs/742ed9b9-996f-4559-a41c-87b49e89bd85/k8sm-executor'
I0209 21:31:26.846970    1272 node.go:52] Connecting to docker on unix:///var/run/docker.sock
I0209 21:31:26.850757    1272 util.go:136] Sending events to APIserver.
I0209 21:31:26.851513    1272 main.go:140] Initialize executor driver...
I0209 21:31:26.864850    1272 event.go:92] Event(api.ObjectReference{Kind:"Minion", Namespace:"default", Name:"0.0.0.0", UID:"0.0.0.0", APIVersion:"", ResourceVersion:"", FieldPath:""}): status: '', reason: 'starting' Starting kubelet.
I0209 21:31:26.865401    1272 main.go:156] Waiting for driver initialization to complete
I0209 21:31:26.866326    1272 plugins.go:56] Registering credential provider: .dockercfg
I0209 21:31:26.866727    1272 main.go:212] Starting proxy process...
I0209 21:31:26.872462  1277 exec.cpp:132] Version: 0.21.1
I0209 21:31:26.891150    1272 main.go:197] Executor driver is running!
I0209 21:31:26.891525    1272 main.go:202] Starting kubelet server...
I0209 21:31:26.891565    1272 server.go:53] Starting to listen on 0.0.0.0:10250
I0209 21:31:26.897632  1284 exec.cpp:206] Executor registered on slave 20150209-162605-806819607-5050-1837-S33
I0209 21:31:26.904199    1272 executor.go:61] Executor executor_id:<value:"KubeleteExecutorID" > framework_id:<value:"20150209-162605-806819607-5050-1837-0009" > command:<uris:<value:"http://23.23.23.48:10251/kube-proxy" executable:true > uris:<value:"http://23.23.23.48:10251/k8sm-executor" executable:true > value:"./k8sm-executor -v=2 -hostname_override=0.0.0.0 -allow_privileged=false -api_servers=23.23.23.48:8888 -etcd_servers=http://23.23.23.48:4001" > name:"Kubelet Executor" source:"kubernetes"  of framework user:"root" name:"KubernetesScheduler" hostname:"mesos-master"  registered with slave hostname:"mesos-slave-6" port:5051 resources:<name:"cpus" type:SCALAR scalar:<value:4 > role:"*" > resources:<name:"mem" type:SCALAR scalar:<value:6962 > role:"*" > resources:<name:"disk" type:SCALAR scalar:<value:25116 > role:"*" > resources:<name:"ports" type:RANGES ranges:<range:<begin:31000 end:32000 > > role:"*" > id:<value:"20150209-162605-806819607-5050-1837-S33" > checkpoint:true 
I0209 21:31:26.907587    1272 executor.go:80] Launch task name:"PodTask" task_id:<value:"0067ed69-b0a3-11e4-857e-fa163e3c002e" > slave_id:<value:"20150209-162605-806819607-5050-1837-S33" > resources:<name:"cpus" type:SCALAR scalar:<value:0.25 > > resources:<name:"mem" type:SCALAR scalar:<value:64 > > resources:<name:"ports" type:RANGES ranges:<range:<begin:31080 end:31080 > > > executor:<executor_id:<value:"KubeleteExecutorID" > framework_id:<value:"20150209-162605-806819607-5050-1837-0009" > command:<uris:<value:"http://23.23.23.48:10251/kube-proxy" executable:true > uris:<value:"http://23.23.23.48:10251/k8sm-executor" executable:true > value:"./k8sm-executor -v=2 -hostname_override=0.0.0.0 -allow_privileged=false -api_servers=23.23.23.48:8888 -etcd_servers=http://23.23.23.48:4001" > name:"Kubelet Executor" source:"kubernetes" > data:"typemeta:\n  kind: \"\"\n  apiversion: \"\"\nobjectmeta:\n  name: devops-cluster-pod\n  namespace: default\n  selflink: /api/v1beta1/boundPods/devops-cluster-pod\n  uid: 0047b18e-b0a3-11e4-97ba-fa163e3c002e\n  resourceversion: \"\"\n  creationtimestamp: 2015-02-09T21:31:25Z\n  labels: {}\n  annotations: {}\nspec:\n  volumes: []\n  containers:\n  - name: apache-modcluster\n    image: sewatech/modcluster\n    command: []\n    workingdir: \"\"\n    ports:\n    - name: \"\"\n      hostport: 31080\n      containerport: 80\n      protocol: TCP\n      hostip: \"\"\n    env:\n    - name: KUBERNETES_RO_SERVICE_HOST\n      value: 10.10.10.51\n    - name: KUBERNETES_RO_SERVICE_PORT\n      value: \"80\"\n    - name: KUBERNETES_RO_PORT\n      value: tcp://10.10.10.51:80\n    - name: KUBERNETES_RO_PORT_80_TCP\n      value: tcp://10.10.10.51:80\n    - name: KUBERNETES_RO_PORT_80_TCP_PROTO\n      value: tcp\n    - name: KUBERNETES_RO_PORT_80_TCP_PORT\n      value: \"80\"\n    - name: KUBERNETES_RO_PORT_80_TCP_ADDR\n      value: 10.10.10.51\n    - name: KUBERNETES_SERVICE_HOST\n      value: 10.10.10.243\n    - name: KUBERNETES_SERVICE_PORT\n      value: \"443\"\n    - name: KUBERNETES_PORT\n      value: tcp://10.10.10.243:443\n    - name: KUBERNETES_PORT_443_TCP\n      value: tcp://10.10.10.243:443\n    - name: KUBERNETES_PORT_443_TCP_PROTO\n      value: tcp\n    - name: KUBERNETES_PORT_443_TCP_PORT\n      value: \"443\"\n    - name: KUBERNETES_PORT_443_TCP_ADDR\n      value: 10.10.10.243\n    memory: 0\n    cpu: 0\n    volumemounts: []\n    livenessprobe: null\n    lifecycle: null\n    terminationmessagepath: \"\"\n    privileged: false\n    imagepullpolicy: \"\"\n  restartpolicy:\n    always: {}\n    onfailure: null\n    never: null\n  dnspolicy: ClusterFirst\n  nodeselector: {}\n  host: \"\"\n" 
I0209 21:31:26.908910    1272 executor.go:130] Binding 'devops-cluster-pod' to '' ...
```
I'm going to try and roll back to a previous version as a first step.
This doesn't really give me anything to work with here, so any ideas?

**Comment by jdef** [comment]
Some recent commits split apart two operations that used to be co-located: the kubernetes "create binding" API call and the mesos "launchTasks" API call. Now, in master, launchTasks is invoked in the scheduler and the kubernetes create-binding is invoked on the executor. If create-binding fails then the executor sends a special `TASK_FAILED` message to the scheduler `create-binding-failed`. The scheduler makes an effort to reschedule such pods by re-adding them to the scheduling queue.

Some preliminaries:
* It sounds like you're able to reproduce this problem frequently - is that the case?
* What do your kubernetes apiserver logs show?
* Do you, perhaps, have lingering state in etcd (from prior k8s pods) that would cause new pod bindings to fail (conflict)? There's a `/registry/boundpods` node in etcd that tracks bindings. Perhaps you can explore the state with a few `curl` calls and report back?

**Comment by brandon-adams** [comment]
I'll start trying to pull that stuff together, thanks.

As an aside, I've been trying to revert back to an earlier commit and I'm not having much success. I'm using the docker build method, specifying an earlier commit (56c72bec23fff213fa9810105d1ff9bb0a0b662e to be exact, or anything before the split), and I'm still encountering the binding error. Is this a problem with Kubernetes itself, and not the framework? Is this not something I can roll back here?

**Comment by jdef** [comment]
a064d99759 is the commit with the "create binding" changes.

If binding is failing then kubernetes is probably finding constraint
violations that mesos isn't. This can happen if etcd state is dirty. You
could try increasing the log verbosity of the apiserver to get more info.
Or curl'ing etcd to inspect state.

--sent from my phone

**Comment by brandon-adams** [comment]
So curling etcd is leading to some more issues.

`curl http://$servicehost:4001/v2/keys/registry/pods/default/`
`{"errorCode":100,"message":"Key not found","cause":"/registry/pods","index":6}`

`curl http://$servicehost:4001/v2/keys/`
`{"action":"get","node":{"key":"/","dir":true,"nodes":[{"key":"/registry","dir":true,"modifiedIndex":3,"createdIndex":3}]}}`

`curl http://$servicehost:4001/v2/keys/registry/`
`{"action":"get","node":{"key":"/registry","dir":true,"nodes":[{"key":"/registry/services","dir":true,"modifiedIndex":3,"createdIndex":3}],"modifiedIndex":3,"createdIndex":3}}`

So it looks like, for some reason, etcd isn't getting set up correctly. I've tried killing it and running it again multiple times but it stays the same.

**Comment by jdef** [comment]
any update on this?

**Comment by jdef** [comment]
ping @brandon-adams, there's a new release out - perhaps it will fix your problem?

**Comment by brandon-adams** [comment]
Sorry I've been away from this issue, I had to roll back and freeze for a project so I haven't gone back to this version. I'll try updating a test stack and see if that fixes anything.

**Comment by jdef** [comment]
Sounds good, thanks!

On Mon, Mar 16, 2015 at 1:12 PM, Brandon <notifications@github.com> wrote:

> Sorry I've been away from this issue, I had to roll back and freeze for a
> project so I haven't gone back to this version. I'll try updating a test
> stack and see if that fixes anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/148#issuecomment-81814901>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by brandon-adams** [comment]
As an aside, is there any link between a Kubernetes pod and a Mesos PodTask which I can query? For example, I'm trying to show the makeup of a PodTask, so I want to be able to look at the Task from Mesos and know exactly to which Kubernetes pod it corresponds, so I can then go into Kubernetes and look at the containers within.

**Comment by jdef** [comment]
There's an undocumented debugging endpoint here:

curl http://$servicehost:10251/debug/registry/tasks

The columns are: taskID, podNamespace/podName, state, offerID


On Mon, Mar 16, 2015 at 1:28 PM, Brandon <notifications@github.com> wrote:

> As an aside, is there any link between a Kubernetes pod and a Mesos
> PodTask which I can query? For example, I'm trying to show the makeup of a
> PodTask, so I want to be able to look at the Task from Mesos and know
> exactly to which Kubernetes pod it corresponds, so I can then go into
> Kubernetes and look at the containers within.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/148#issuecomment-81823528>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by brandon-adams** [comment]
That's perfect, but I don't seem to have that endpoint. I'm getting a 404
when I try and curl it. I can see the scheduler bound to the port, but
nothing comes back from a curl.

On Mon, Mar 16, 2015 at 1:35 PM, James DeFelice <notifications@github.com>
wrote:

> There's an undocumented debugging endpoint here:
>
> curl http://$servicehost:10251/debug/registry/tasks
>
> The columns are: taskID, podNamespace/podName, state, offerID
>
>
> On Mon, Mar 16, 2015 at 1:28 PM, Brandon <notifications@github.com> wrote:
>
> > As an aside, is there any link between a Kubernetes pod and a Mesos
> > PodTask which I can query? For example, I'm trying to show the makeup of
> a
> > PodTask, so I want to be able to look at the Task from Mesos and know
> > exactly to which Kubernetes pod it corresponds, so I can then go into
> > Kubernetes and look at the containers within.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mesosphere/kubernetes-mesos/issues/148#issuecomment-81823528
> >
>
> > .
> >
>
>
>
> --
> James DeFelice
> 585.241.9488 (voice)
> 650.649.6071 (fax)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/148#issuecomment-81829718>
> .
>



-- 
*Brandon Marcellus Adams*
Research & Development Engineer


NewWave Telecom & Technologies, Inc.
6518 Meadowridge Road, Suite 100
Elkridge, MD 21075
Phone: (410) 782-0476 ext. 2032
E-mail: brandon.adams@newwave-technologies.com
Website: www.newwave-technologies.com

**Comment by jdef** [comment]
If you're building from master, or from release-0.4 that's very strange.

An alternative (that also requires master or release-0.4) is to query the
pod metadata from kubernetes directly and look for "taskId" annotation.

curl http://$servicehost:8888/api/v1beta1/pods/redis-slave-controller-ho0xu

should yield JSON that includes something like:

...
  "annotations": {
    "k8s.mesosphere.io/bindingHost": "10.150.52.19",
    "k8s.mesosphere.io/executorId": "KubeleteExecutorID",
    "k8s.mesosphere.io/offerId":
"20150311-194734-3815890698-5050-5519-O124373",
    "k8s.mesosphere.io/slaveId": "20150221-134408-3815890698-5050-18127-S7",
    "k8s.mesosphere.io/taskId": "e4d904c9-cbdb-11e4-a396-42010adf71e3"
  },
...


On Mon, Mar 16, 2015 at 1:46 PM, Brandon <notifications@github.com> wrote:

> That's perfect, but I don't seem to have that endpoint. I'm getting a 404
> when I try and curl it. I can see the scheduler bound to the port, but
> nothing comes back from a curl.
>
> On Mon, Mar 16, 2015 at 1:35 PM, James DeFelice <notifications@github.com>
> wrote:
>
> > There's an undocumented debugging endpoint here:
> >
> > curl http://$servicehost:10251/debug/registry/tasks
> >
> > The columns are: taskID, podNamespace/podName, state, offerID
> >
> >
> > On Mon, Mar 16, 2015 at 1:28 PM, Brandon <notifications@github.com>
> wrote:
> >
> > > As an aside, is there any link between a Kubernetes pod and a Mesos
> > > PodTask which I can query? For example, I'm trying to show the makeup
> of
> > a
> > > PodTask, so I want to be able to look at the Task from Mesos and know
> > > exactly to which Kubernetes pod it corresponds, so I can then go into
> > > Kubernetes and look at the containers within.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/mesosphere/kubernetes-mesos/issues/148#issuecomment-81823528
> > >
> >
> > > .
> > >
> >
> >
> >
> > --
> > James DeFelice
> > 585.241.9488 (voice)
> > 650.649.6071 (fax)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mesosphere/kubernetes-mesos/issues/148#issuecomment-81829718
> >
> > .
> >
>
>
>
> --
> *Brandon Marcellus Adams*
> Research & Development Engineer
>
>
> NewWave Telecom & Technologies, Inc.
> 6518 Meadowridge Road, Suite 100
> Elkridge, MD 21075
> Phone: (410) 782-0476 ext. 2032
> E-mail: brandon.adams@newwave-technologies.com
> Website: www.newwave-technologies.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/148#issuecomment-81836771>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by brandon-adams** [comment]
Thanks for the pointers. It looks like upgrading to the latest version solved both of the problems I was having, this original one and the missing endpoint one.
