### ISSUE TITLE
Scheduler HA

### ISSUE THREAD

**Issue by nqn** [mesosphere/kubernetes-mesos#15]
We need to test and verify scheduler HA
- [x] preliminary scheduler lifecycle support
- [x] preliminary graceful failover support
- [x] we probably suffer from a similar issue https://github.com/mesosphere/marathon/issues/1063
  - potential solution: defer `buildFrameworkInfo()`/driver initialization until post-election
- [x] scheduler leader election
- [x] wire up leader election to graceful failover
- [x] executors commit suicide once they've "outlived their usefulness"
  - [x] multiple suicide attempts within 60s? see https://gist.github.com/jdef/70925988d01027a6fd8f
- [x] prevent multiple HA schedulers that will generate conflicting ExecutorInfo
  - [x] hash potentially conflicting `ExecutorInfo` and prepend to leader UID
  - [x] validate that current master has matching UID prefix, otherwise terminate
  - [x] what if all schedulers crash (there is no leader) then we start a new scheduler w/ diff params?
- [x] pass DNS parameters from scheduler to executor
  - [x] pass `Cluster{DNS,Domain}` from scheduler to executor
- [x] document how to make use of HA mode, requirements, etc.
  - `--ha` and `--km_path=hdfs:///...` is the easiest way to get started
  - if starting a secondary scheduler on the same host, use a different `--port`
  - all `--auth_path`, `--etcd_*`, `--executor_*`, and `--proxy_*` options must be identical
- [x] failover cleanup (lots of TODOs)
- [x] sync to latest version of osext to pick up https://github.com/kardianos/osext/commit/e61421bbfae9c64ff5836c1776b58b2deb34269f

Related upstream discussion
- https://github.com/GoogleCloudPlatform/kubernetes/issues/473

**Comment by jdef** [comment]
the election interface was removed upstream because they're not ready to implement it yet. but that doesn't mean that we can't use it before they get back it it.

xref: https://github.com/GoogleCloudPlatform/kubernetes/commit/858b557bbbd48d2908495865fafd7c6ebce5041a

**Comment by jdef** [comment]
Considering how to deal with Stop() if master leadership changes. Something like this?
```go
func (s *schedulerService) Stop() {
  s.driver.Stop() // **really** needs to make best effort to stop things (that log)
  log.Flush()

  // run the same command that we were launched with
  cmd := exec.Command(...)
  cmd.Stdout = os.Stdout
  cmd.Stderr = os.Stderr
  cmd.SysProcAttr = &syscall.SysProcAttr{
    Setpgid: true, // disown
  }
  exitcode := 0
  if err := cmd.Start(); err != nil {
    exitcode = -1
  }
  os.Exit(exitcode)
}
```

perhaps we add a `-startupDelay` so that the newly launched scheduler sleeps for X before doing anything else (to give it's parent a chance to terminate first, avoid logging overlap).

perhaps we could even preserve the HTTP listener socket:
* http://grisha.org/blog/2014/06/03/graceful-restart-in-golang/

xref: https://groups.google.com/forum/#!topic/golang-nuts/shST-SDqIp4

**Comment by jdef** [comment]
Current implementation of driver.Stop() seems a little racy: the UnregisterFramework message may not get sent because the driver is already terminated. This seems like a bindings problem:
```
I0317 14:54:58.415063   29346 service.go:321] received failover signal
I0317 14:54:58.415125   29346 scheduler.go:815] Stopping the scheduler driver
I0317 14:54:58.415187   29346 messenger.go:166] Sending message mesos.internal.UnregisterFrameworkMessage to master@10.223.113.227:5050
I0317 14:54:58.415378   29346 service.go:449] spawning scheduler for graceful failover: /home/jclouds/bin/km [scheduler --address=10.223.113.227 --checkpoint=true --driver_port=9876 --executor_logv=2 --mesos_master=zk://10.223.113.227:2181/mesos --mesos_user=root --v=2 --graceful --api_servers=10.223.113.227:8888 --etcd_servers=http://10.223.113.227:4001]
I0317 14:54:58.416774   29346 messenger.go:337] exiting decodeLoop, transport shutting down
I0317 14:54:58.416988   29346 http_transporter.go:107] Sending message to master@10.223.113.227:5050 via http
I0317 14:54:58.417043   29346 http_transporter.go:343] libproc target URL http://10.223.113.227:5050/master/mesos.internal.UnregisterFrameworkMessage
I0317 14:54:58.417112   29346 messenger.go:279] Failed to send message mesos.internal.UnregisterFrameworkMessage: discarding message because transport is shutting down
E0317 14:54:58.417197   29346 messenger.go:291] failed to report error Failed to send message mesos.internal.UnregisterFrameworkMessage: discarding message because transport is shutting down due to: discarding message because transport is shutting down
I0317 14:54:58.417265   29346 ha.go:75] scheduler process entered fin stage
```

**Comment by jdef** [comment]
Attempted hot-failover and got an error because of ExecutorInfo incompatibility. The URI is different because it's a different scheduler instance serving up the binary that will run the executor.
```
I0317 20:43:40.383052   27455 scheduler.go:264] Received status update &TaskStatus{TaskId:&TaskID{Value:*41dad84a-cce6-11e4-b38b-42010adf71e3,XXX_unrecognized:[],},State:*TASK_LOST,Message:*Task has invalid ExecutorInfo (existing ExecutorInfo with same ExecutorID is not compatible).
------------------------------------------------------------
Existing ExecutorInfo:
executor_id {
  value: "KubeleteExecutorID"
}
command {
  uris {
    value: "http://10.223.113.227:10251/km"
    executable: true
  }
  value: "./km"
  shell: false
  arguments: "executor"
  arguments: "--api_servers=10.223.113.227:8888"
  arguments: "--v=2"
  arguments: "--allow_privileged=false"
  arguments: "--proxy_bindall=false"
  arguments: "--run_proxy=true"
  arguments: "--etcd_servers=http://10.223.113.227:4001"
}
framework_id {
  value: "20150221-134408-3815890698-5050-18127-0041"
}
name: "Kubelet Executor"
source: "kubernetes"

------------------------------------------------------------
Task's ExecutorInfo:
executor_id {
  value: "KubeleteExecutorID"
}
command {
  uris {
    value: "http://10.223.113.227:20002/km"
    executable: true
  }
  value: "./km"
  shell: false
  arguments: "executor"
  arguments: "--api_servers=10.223.113.227:8888"
  arguments: "--v=2"
  arguments: "--allow_privileged=false"
  arguments: "--proxy_bindall=false"
  arguments: "--run_proxy=true"
  arguments: "--etcd_servers=http://10.223.113.227:4001"
}
framework_id {
  value: "20150221-134408-3815890698-5050-18127-0041"
}
name: "Kubelet Executor"
source: "kubernetes"

------------------------------------------------------------
,Source:*SOURCE_MASTER,Reason:*REASON_TASK_INVALID,Data:nil,SlaveId:&SlaveID{Value:*20150311-194734-3815890698-5050-5519-S0,XXX_unrecognized:[],},ExecutorId:nil,Timestamp:*1.426625020365037e+09,Healthy:nil,XXX_unrecognized:[],}
```

**Comment by jdef** [comment]
re: the above, URI comparison is handled here:
* https://github.com/apache/mesos/blob/master/src/common/type_utils.cpp#L32
```c++
bool operator == (const CommandInfo& left, const CommandInfo& right)
{
  if (left.uris().size() != right.uris().size()) {
    return false;
  }

  // TODO(vinod): Factor out the comparison for repeated fields.
  for (int i = 0; i < left.uris().size(); i++) {
    bool found = false;
    for (int j = 0; j < right.uris().size(); j++) {
      if (left.uris().Get(i) == right.uris().Get(j)) {
        found = true;
        break;
      }
    }
    if (!found) {
      return false;
    }
  }
//...
```

**Comment by jdef** [comment]
Random thoughts around a wacky solution:
* assume that proxy runs on every slave, outside the context of the kubelet-executor: services are available everywhere
* framework/scheduler is discoverable
  * FrameworkInfo doesn't provide DiscoveryInfo yet, so...
  * k8sm scheduler instances register as service endpoints in the k8s Service registry (analogous to what the API server does): scheduling is a proper service!
  * mesos-dns has a plugin that supports k8s services, exposing them to all mesos nodes, e.g. `k8sm-scheduler.mesos` resolves to the k8s Service IP
* mesos slave fetcher will do SRV lookups to determine `service-ip:port` for http addresses like this: `http://_k8sm-scheduler._tcp.mesos/abc/123/km` (SRV lookup triggered by leading underscore)
  * this allows URIs spec'd for executors to remain the same

**Comment by jdef** [comment]
Forcing HA mode to require proxy pre-deployed on slaves isn't that bad since we can solve it with Marathon. However, running the proxy that way will change the kubelet-executor flags (`--run_proxy=false`) which will trigger an ExecutorInfo incompatibility if there are already executors running. So it makes upgrading from non-HA-mode to HA-mode a little trickier since you have to ensure that all prior kubelet-executors are dead.

**Comment by davidopp** [comment]
I didn't read the whole issue, but just curious, what did you end up doing about leader election?

**Comment by jdef** [comment]
Imported some older code from k8s (that had been removed due to lack of
use?):

https://github.com/mesosphere/kubernetes-mesos/tree/master/pkg/election


On Sun, Apr 19, 2015 at 6:28 PM, David Oppenheimer <notifications@github.com
> wrote:

> I didn't read the whole issue, but just curious, what did you end up doing
> about leader election?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/15#issuecomment-94319924>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by davidopp** [comment]
OK. FWIW it appears that we are going to re-implement master election in a
new way in k8s for HA in k8s...
https://github.com/GoogleCloudPlatform/kubernetes/pull/6995/files
