### ISSUE TITLE
refactor slave tracking in scheduler

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#194]
the `KubernetesScheduler` maintains a slave index and uses it's "master lock" to control access to that index. The index really should be broken out into its own registry, similar to what's been done for offers and pod tasks. Then we can probably eliminate the big ugly lock at the top-level scheduler (or at least get closer to that point).

**Comment by jdef** [comment]
I already ripped out the slave's embedded offer list as part of #207. Should be trivial at this point to write a slaveStorage struct and move the lock in there.

**Comment by jdef** [comment]
this issue needs review .. anything left?

**Comment by karlkfi** [comment]
I think this is done, since https://github.com/mesosphere/kubernetes-mesos/pull/220 has long since been merged. Feel free to make a new ticket if you don't agree, @jdef

**Comment by jdef** [comment]
sgtm
