### ISSUE TITLE
unable to deploy pod / documentation

### ISSUE THREAD

**Issue by jaychris** [mesosphere/kubernetes-mesos#219]
I followed the documentation [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/mesos.md) in an effort to test out Kubernetes on top of Mesos.  

Everything seemed to go correctly and according to the guide, but I get this when I attempt to deploy the pod:
```
E0410 21:49:58.511438   12358 reflector.go:118] watch of *api.Pod ended with error: unexpected end of JSON input
I0410 21:50:11.520945   12358 scheduler.go:537] implicit reconcile tasks
I0410 21:50:12.821047   12358 plugin.go:249] Try to schedule pod nginx-id-01
I0410 21:50:12.821132   12358 plugin.go:503] Error scheduling nginx-id-01: No suitable offers for pod/task; retrying
I0410 21:50:45.233232   12358 plugin.go:249] Try to schedule pod nginx-id-01
I0410 21:50:45.233322   12358 plugin.go:503] Error scheduling nginx-id-01: No suitable offers for pod/task; retrying
I0410 21:51:45.253524   12358 plugin.go:249] Try to schedule pod nginx-id-01
```

Here are the commands I used to start services:
```
# export servicehost=$(hostname -i)
# export mesos_master=${servicehost}:5050
# export KUBERNETES_MASTER=http://${servicehost}:8888
```

```
# bin/km apiserver --address=${servicehost} --mesos_master=${mesos_master} --etcd_servers=http://${servicehost}:4001 --portal_net=10.10.10.0/24 --port=8888 --cloud_provider=mesos > apiserver.log 2>&1 &
# bin/km controller-manager --master=$servicehost:8888 --mesos_master=${mesos_master} > controller.log 2>&1 &
# bin/km scheduler --address=${servicehost} --mesos_master=${mesos_master} --etcd_servers=http://${servicehost}:4001 --mesos_user=root --api_servers=$servicehost:8888 > scheduler.log 2>&1 &
# bin/km proxy --bind_address=${servicehost} --etcd_servers=http://${servicehost}:4001 --logtostderr=true --v=2 > proxy.log 2>&1 &
```

Output from kubectl:
```
[root@mesos01 ~]# kubectl get services
NAME                LABELS                                    SELECTOR            IP                  PORT
kubernetes          component=apiserver,provider=kubernetes   <none>              10.10.10.2          443
kubernetes-ro       component=apiserver,provider=kubernetes   <none>              10.10.10.1          80

[root@mesos01 ~]# kubectl get pods
POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                LABELS              STATUS
nginx-id-01                             nginx-01            dockerfile/nginx    <unassigned>        name=foo            Pending
```

I don't see anything in the logs, other than the scheduler error listed above, that looks like a problem, so I am not really sure where to go from here.

**Comment by jdef** [comment]
Thanks for reporting this. Some questions for you:

(1) what is your mesos cluster configuration (# masters, # slaves)

(2) is there anything informative in the mesos error logs?
/var/log/mesos/mesos-master.*

(3) how many connections to zookeeper are there? you can check this like so
(on a master node):

$ sudo netstat -natlop|grep -e 2181
tcp        0      0 0.0.0.0:2181            0.0.0.0:*               LISTEN
     1820/java        off (0.00/0/0)
tcp        0      0 10.1.121.213:2181       10.121.155.241:47027
 ESTABLISHED 1820/java        off (0.00/0/0)
tcp        0      0 10.1.121.213:2181       10.1.121.213:50198
 ESTABLISHED 1820/java        off (0.00/0/0)
...

You can also try increasing the verbosity of the scheduler logging with
--v=2


On Fri, Apr 10, 2015 at 5:39 PM, jaychris <notifications@github.com> wrote:

> I followed the documentation here
> <https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/mesos.md>
> in an effort to test out Kubernetes on top of Mesos.
>
> Everything seemed to go correctly and according to the guide, but I get
> this when I attempt to deploy the pod:
>
> I0410 21:28:29.357595   11450 plugin.go:503] Error scheduling nginx-id-01: No suitable offers for pod/task; retrying
> I0410 21:28:30.557979   11450 plugin.go:249] Try to schedule pod nginx-id-01
> I0410 21:28:30.558071   11450 plugin.go:503] Error scheduling nginx-id-01: No suitable offers for pod/task; retrying
> I0410 21:28:32.958876   11450 plugin.go:249] Try to schedule pod nginx-id-01
> I0410 21:28:32.958971   11450 plugin.go:503] Error scheduling nginx-id-01: No suitable offers for pod/task; retrying
>
> Here are the commands I used to start services:
>
> # export servicehost=$(hostname -i)
> # export mesos_master=${servicehost}:5050
> # export KUBERNETES_MASTER=http://${servicehost}:8888
>
> # bin/km apiserver --address=${servicehost} --mesos_master=${mesos_master} --etcd_servers=http://${servicehost}:4001 --portal_net=10.10.10.0/24 --port=8888 --cloud_provider=mesos > apiserver.log 2>&1 &
> # bin/km controller-manager --master=$servicehost:8888 --mesos_master=${mesos_master} > controller.log 2>&1 &
> # bin/km scheduler --address=${servicehost} --mesos_master=${mesos_master} --etcd_servers=http://${servicehost}:4001 --mesos_user=root --api_servers=$servicehost:8888 > scheduler.log 2>&1 &
> # bin/km proxy --bind_address=${servicehost} --etcd_servers=http://${servicehost}:4001 --logtostderr=true --v=2 > proxy.log 2>&1 &
>
> Output from kubectl:
>
> [root@mesos01 ~]# kubectl get services
> NAME                LABELS                                    SELECTOR            IP                  PORT
> kubernetes          component=apiserver,provider=kubernetes   <none>              10.10.10.2          443
> kubernetes-ro       component=apiserver,provider=kubernetes   <none>              10.10.10.1          80
>
> [root@mesos01 ~]# kubectl get pods
> POD                 IP                  CONTAINER(S)        IMAGE(S)            HOST                LABELS              STATUS
> nginx-id-01                             nginx-01            dockerfile/nginx    <unassigned>        name=foo            Pending
>
> I don't see anything in the logs, other than the scheduler error listed
> above, that looks like a problem, so I am not really sure where to go from
> here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/219>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by jaychris** [comment]
1.  I'm using a basic 3-node Master cluster, where the current master is 10.50.22.10.  When I encountered the issue, I backed off to a single node cluster, but ran into the same problem, so I figured the issue wasn't related.  FWIW, I'm testing this out on AWS, using t2.small instances.  If you feel that I need to go back to troubleshooting on the single node cluster, I can do that.

2.  There are no current messages in the mesos logs (all 4+ hours old, from the initial setup of Mesos, and all (I)nformational).

3.  Connections:
```
[root@mesos01 mesos]# netstat -natlop|grep -e 2181
tcp        0      0 10.50.22.9:57174        10.50.22.10:2181        ESTABLISHED 794/mesos-master     off (0.00/0/0)
tcp        0      0 10.50.22.9:49778        10.50.22.11:2181        ESTABLISHED 794/mesos-master     off (0.00/0/0)
tcp        0      0 10.50.22.9:57959        10.50.22.10:2181        ESTABLISHED 12358/bin/km         off (0.00/0/0)
tcp        0      0 10.50.22.9:57956        10.50.22.10:2181        ESTABLISHED 12354/bin/km         off (0.00/0/0)
tcp        0      0 10.50.22.9:57953        10.50.22.10:2181        ESTABLISHED 12350/bin/km         off (0.00/0/0)
tcp        0      0 10.50.22.9:57215        10.50.22.10:2181        ESTABLISHED 1249/java            off (0.00/0/0)
tcp        0      0 10.50.22.9:57175        10.50.22.10:2181        ESTABLISHED 794/mesos-master     off (0.00/0/0)
tcp        0      0 10.50.22.9:49781        10.50.22.11:2181        ESTABLISHED 794/mesos-master     off (0.00/0/0)
tcp6       0      0 :::2181                 :::*                    LISTEN      798/java             off (0.00/0/0)
tcp6       0      0 10.50.22.9:57214        10.50.22.10:2181        ESTABLISHED 1249/java            off (0.00/0/0)
```

I'll turn up the logging on the scheduler and report back.

**Comment by jaychris** [comment]
Here is the verbose scheduler output:
```
W0410 22:12:24.423999   18770 service.go:258] Could not load kubernetes auth path: stat : no such file or directory. Continuing with defaults.
I0410 22:12:24.424149   18770 service.go:169] Hosting artifact '/root/bin/km' at 'http://10.50.22.9:10251/km'
I0410 22:12:24.424168   18770 service.go:242] prepared executor command '0xc208113b20' with args '+[executor --api_servers=10.50.22.9:8888 --v=0 --allow_privileged=false --proxy_bindall=false --run_proxy=true --etcd_servers=http://10.50.22.9:4001]'
I0410 22:12:24.425250   18770 service.go:388] configuring FrameworkInfo with Id found in etcd: '20150410-200807-169226762-5050-14527-0001'
I0410 22:12:24.425266   18770 service.go:404] Framework configured with mesos user root
I0410 22:12:24.426168   18770 scheduler.go:187] found failover_timeout = 1281023h53m38.427387904s
I0410 22:12:24.426206   18770 detect.go:70] Created new detector, watching  [mesos01:2181 mesos02:2181 mesos03:2181] /mesos
I0410 22:12:24.426280   18770 scheduler.go:232] Initializing mesos scheduler driver
I0410 22:12:24.432189   18770 pod_task.go:210] skipping recovery for unbound pod default/nginx-id-01
I0410 22:12:24.432207   18770 scheduler.go:640] Starting the scheduler driver...
I0410 22:12:24.432255   18770 http_transporter.go:275] http transport listening on 10.50.22.9:40572
I0410 22:12:25.432444   18770 scheduler.go:659] Mesos scheduler driver started with PID=scheduler(1)@10.50.22.9:40572
I0410 22:12:25.432502   18770 scheduler.go:670] starting master detector *zoo.MasterDetector: &{client:0xc208063ea0 leaderNode: bootstrap:{m:{state:0 sema:0} done:0} ignoreInstalled:0}
I0410 22:12:25.432540   18770 scheduler.go:673] master detector started
I0410 22:12:25.432564   18770 service.go:367] Spinning up scheduling loop
I0410 22:12:25.432636   18770 service.go:363] Starting HTTP interface
I0410 22:12:25.432767   18770 plugin.go:446] attempting to yield a pod
I0410 22:12:25.432815   18770 client.go:245] connecting to zookeeper..
I0410 22:12:25.432916   18770 plugin.go:398] Watching for newly created pods
I0410 22:12:25.437716   18770 client.go:193] zookeeper client connected
I0410 22:12:25.437757   18770 client.go:282] Watching children for path /mesos
I0410 22:12:25.458003   18770 detect.go:171] detector listener installed
I0410 22:12:25.458046   18770 detect.go:99] fetching children at path '/mesos'
I0410 22:12:25.458590   18770 detect.go:113] changing leader node from  -> info_0000000015
I0410 22:12:25.459168   18770 detect.go:131] detected master info: &MasterInfo{Id:*20150410-200807-169226762-5050-14527,Ip:*169226762,Port:*5050,Pid:*master@10.50.22.10:5050,Hostname:*mesos02,XXX_unrecognized:[],}
I0410 22:12:25.459292   18770 messenger.go:343] Receiving message mesos.internal.InternalMasterChangeDetected from scheduler(1)@10.50.22.9:40572
I0410 22:12:25.459322   18770 scheduler.go:272] New master master@10.50.22.10:5050 detected
I0410 22:12:25.459334   18770 scheduler.go:331] No credentials were provided. Attempting to register scheduler without authentication.
I0410 22:12:25.459355   18770 scheduler.go:765] Reregistering with master: master@10.50.22.10:5050
I0410 22:12:25.459392   18770 messenger.go:166] Sending message mesos.internal.ReregisterFrameworkMessage to master@10.50.22.10:5050
I0410 22:12:25.459495   18770 scheduler.go:730] will retry registration in 1.329120106s if necessary
I0410 22:12:25.459512   18770 http_transporter.go:107] Sending message to master@10.50.22.10:5050 via http
I0410 22:12:25.459539   18770 http_transporter.go:343] libproc target URL http://10.50.22.10:5050/master/mesos.internal.ReregisterFrameworkMessage
I0410 22:12:25.462505   18770 http_transporter.go:328] Receiving message from master@10.50.22.10:5050, length 127
I0410 22:12:25.462610   18770 messenger.go:343] Receiving message mesos.internal.FrameworkRegisteredMessage from master@10.50.22.10:5050
I0410 22:12:25.462649   18770 scheduler.go:415] Handling scheduler driver framework registered event.
I0410 22:12:25.462657   18770 scheduler.go:441] Framework registered with ID=20150410-200807-169226762-5050-14527-0001
I0410 22:12:25.463155   18770 scheduler.go:144] Scheduler registered with the master: &MasterInfo{Id:*20150410-200807-169226762-5050-14527,Ip:*169226762,Port:*5050,Pid:*master@10.50.22.10:5050,Hostname:*mesos02,XXX_unrecognized:[],} with frameworkId: &FrameworkID{Value:*20150410-200807-16
9226762-5050-14527-0001,XXX_unrecognized:[],}
I0410 22:12:25.463218   18770 scheduler.go:183] will perform implicit task reconciliation at interval: 5m0s
I0410 22:12:25.463339   18770 scheduler.go:417] explicit reconcile tasks
I0410 22:12:25.463359   18770 messenger.go:166] Sending message mesos.internal.ReconcileTasksMessage to master@10.50.22.10:5050
I0410 22:12:25.463439   18770 http_transporter.go:107] Sending message to master@10.50.22.10:5050 via http
I0410 22:12:25.463462   18770 http_transporter.go:343] libproc target URL http://10.50.22.10:5050/master/mesos.internal.ReconcileTasksMessage
I0410 22:12:25.833247   18770 plugin.go:249] Try to schedule pod nginx-id-01
I0410 22:12:25.833345   18770 fcfs.go:49] failed to find a fit for pod: nginx-id-01
I0410 22:12:25.833354   18770 scheduler.go:74] Failed to schedule: &{{ } {nginx-id-01  default /api/v1beta1/pods/nginx-id-01?namespace=default 879c1378-dfc8-11e4-9312-0a7a01caff03 15 2015-04-10 21:28:28 +0000 UTC map[name:foo] map[]} {[] [{nginx-01 dockerfile/nginx []  [{ 31000 80 TCP }]
[] {map[]} [] 0xc20828aba0 <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] {0x18f9158 <nil> <nil>} ClusterFirst map[] } {Pending []     map[]}}
I0410 22:12:25.833541   18770 plugin.go:503] Error scheduling nginx-id-01: No suitable offers for pod/task; retrying
I0410 22:12:25.833582   18770 plugin.go:446] attempting to yield a pod
I0410 22:12:26.788797   18770 scheduler.go:754] skipping registration request: stopped=false, connected=true, authenticated=true
I0410 22:12:27.033998   18770 plugin.go:249] Try to schedule pod nginx-id-01
I0410 22:12:27.034046   18770 fcfs.go:49] failed to find a fit for pod: nginx-id-01
I0410 22:12:27.034064   18770 scheduler.go:74] Failed to schedule: &{{ } {nginx-id-01  default /api/v1beta1/pods/nginx-id-01?namespace=default 879c1378-dfc8-11e4-9312-0a7a01caff03 15 2015-04-10 21:28:28 +0000 UTC map[name:foo] map[]} {[] [{nginx-01 dockerfile/nginx []  [{ 31000 80 TCP }]
[] {map[]} [] 0xc20828aba0 <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] {0x18f9158 <nil> <nil>} ClusterFirst map[] } {Pending []     map[]}}
I0410 22:12:27.034163   18770 plugin.go:503] Error scheduling nginx-id-01: No suitable offers for pod/task; retrying
I0410 22:12:27.034205   18770 plugin.go:446] attempting to yield a pod
I0410 22:12:29.434860   18770 plugin.go:249] Try to schedule pod nginx-id-01
I0410 22:12:29.434905   18770 fcfs.go:49] failed to find a fit for pod: nginx-id-01
I0410 22:12:29.434924   18770 scheduler.go:74] Failed to schedule: &{{ } {nginx-id-01  default /api/v1beta1/pods/nginx-id-01?namespace=default 879c1378-dfc8-11e4-9312-0a7a01caff03 15 2015-04-10 21:28:28 +0000 UTC map[name:foo] map[]} {[] [{nginx-01 dockerfile/nginx []  [{ 31000 80 TCP }]
[] {map[]} [] 0xc20828aba0 <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] {0x18f9158 <nil> <nil>} ClusterFirst map[] } {Pending []     map[]}}
```

**Comment by jdef** [comment]
It sounds like you're not getting offers for some reason, though I'm not
sure why. Can you dump some metrics from the scheduler? For example...

$ curl -f http://$servicehost:10251/metrics|egrep -e '^(scheduler|offer)'
offers_acquired{hostname="10.174.158.91"} 55
offers_acquired{hostname="10.34.128.223"} 71
...
scheduler_bind_latency_microseconds{quantile="0.5"} 0
scheduler_bind_latency_microseconds{quantile="0.9"} 0
...


On Fri, Apr 10, 2015 at 6:14 PM, jaychris <notifications@github.com> wrote:

> Here is the verbose scheduler output:
>
> W0410 22:12:24.423999   18770 service.go:258] Could not load kubernetes auth path: stat : no such file or directory. Continuing with defaults.
> I0410 22:12:24.424149   18770 service.go:169] Hosting artifact '/root/bin/km' at 'http://10.50.22.9:10251/km'
> I0410 22:12:24.424168   18770 service.go:242] prepared executor command '0xc208113b20' with args '+[executor --api_servers=10.50.22.9:8888 --v=0 --allow_privileged=false --proxy_bindall=false --run_proxy=true --etcd_servers=http://10.50.22.9:4001]'
> I0410 22:12:24.425250   18770 service.go:388] configuring FrameworkInfo with Id found in etcd: '20150410-200807-169226762-5050-14527-0001'
> I0410 22:12:24.425266   18770 service.go:404] Framework configured with mesos user root
> I0410 22:12:24.426168   18770 scheduler.go:187] found failover_timeout = 1281023h53m38.427387904s
> I0410 22:12:24.426206   18770 detect.go:70] Created new detector, watching  [mesos01:2181 mesos02:2181 mesos03:2181] /mesos
> I0410 22:12:24.426280   18770 scheduler.go:232] Initializing mesos scheduler driver
> I0410 22:12:24.432189   18770 pod_task.go:210] skipping recovery for unbound pod default/nginx-id-01
> I0410 22:12:24.432207   18770 scheduler.go:640] Starting the scheduler driver...
> I0410 22:12:24.432255   18770 http_transporter.go:275] http transport listening on 10.50.22.9:40572
> I0410 22:12:25.432444   18770 scheduler.go:659] Mesos scheduler driver started with PID=scheduler(1)@10.50.22.9:40572
> I0410 22:12:25.432502   18770 scheduler.go:670] starting master detector *zoo.MasterDetector: &{client:0xc208063ea0 leaderNode: bootstrap:{m:{state:0 sema:0} done:0} ignoreInstalled:0}
> I0410 22:12:25.432540   18770 scheduler.go:673] master detector started
> I0410 22:12:25.432564   18770 service.go:367] Spinning up scheduling loop
> I0410 22:12:25.432636   18770 service.go:363] Starting HTTP interface
> I0410 22:12:25.432767   18770 plugin.go:446] attempting to yield a pod
> I0410 22:12:25.432815   18770 client.go:245] connecting to zookeeper..
> I0410 22:12:25.432916   18770 plugin.go:398] Watching for newly created pods
> I0410 22:12:25.437716   18770 client.go:193] zookeeper client connected
> I0410 22:12:25.437757   18770 client.go:282] Watching children for path /mesos
> I0410 22:12:25.458003   18770 detect.go:171] detector listener installed
> I0410 22:12:25.458046   18770 detect.go:99] fetching children at path '/mesos'
> I0410 22:12:25.458590   18770 detect.go:113] changing leader node from  -> info_0000000015
> I0410 22:12:25.459168   18770 detect.go:131] detected master info: &MasterInfo{Id:*20150410-200807-169226762-5050-14527,Ip:*169226762,Port:*5050,Pid:*master@10.50.22.10:5050,Hostname:*mesos02,XXX_unrecognized:[],}
> I0410 22:12:25.459292   18770 messenger.go:343] Receiving message mesos.internal.InternalMasterChangeDetected from scheduler(1)@10.50.22.9:40572
> I0410 22:12:25.459322   18770 scheduler.go:272] New master master@10.50.22.10:5050 detected
> I0410 22:12:25.459334   18770 scheduler.go:331] No credentials were provided. Attempting to register scheduler without authentication.
> I0410 22:12:25.459355   18770 scheduler.go:765] Reregistering with master: master@10.50.22.10:5050
> I0410 22:12:25.459392   18770 messenger.go:166] Sending message mesos.internal.ReregisterFrameworkMessage to master@10.50.22.10:5050
> I0410 22:12:25.459495   18770 scheduler.go:730] will retry registration in 1.329120106s if necessary
> I0410 22:12:25.459512   18770 http_transporter.go:107] Sending message to master@10.50.22.10:5050 via http
> I0410 22:12:25.459539   18770 http_transporter.go:343] libproc target URL http://10.50.22.10:5050/master/mesos.internal.ReregisterFrameworkMessage
> I0410 <http://10.50.22.10:5050/master/mesos.internal.ReregisterFrameworkMessageI0410> 22:12:25.462505   18770 http_transporter.go:328] Receiving message from master@10.50.22.10:5050, length 127
> I0410 22:12:25.462610   18770 messenger.go:343] Receiving message mesos.internal.FrameworkRegisteredMessage from master@10.50.22.10:5050
> I0410 22:12:25.462649   18770 scheduler.go:415] Handling scheduler driver framework registered event.
> I0410 22:12:25.462657   18770 scheduler.go:441] Framework registered with ID=20150410-200807-169226762-5050-14527-0001
> I0410 22:12:25.463155   18770 scheduler.go:144] Scheduler registered with the master: &MasterInfo{Id:*20150410-200807-169226762-5050-14527,Ip:*169226762,Port:*5050,Pid:*master@10.50.22.10:5050,Hostname:*mesos02,XXX_unrecognized:[],} with frameworkId: &FrameworkID{Value:*20150410-200807-16
> 9226762-5050-14527-0001,XXX_unrecognized:[],}
> I0410 22:12:25.463218   18770 scheduler.go:183] will perform implicit task reconciliation at interval: 5m0s
> I0410 22:12:25.463339   18770 scheduler.go:417] explicit reconcile tasks
> I0410 22:12:25.463359   18770 messenger.go:166] Sending message mesos.internal.ReconcileTasksMessage to master@10.50.22.10:5050
> I0410 22:12:25.463439   18770 http_transporter.go:107] Sending message to master@10.50.22.10:5050 via http
> I0410 22:12:25.463462   18770 http_transporter.go:343] libproc target URL http://10.50.22.10:5050/master/mesos.internal.ReconcileTasksMessage
> I0410 <http://10.50.22.10:5050/master/mesos.internal.ReconcileTasksMessageI0410> 22:12:25.833247   18770 plugin.go:249] Try to schedule pod nginx-id-01
> I0410 22:12:25.833345   18770 fcfs.go:49] failed to find a fit for pod: nginx-id-01
> I0410 22:12:25.833354   18770 scheduler.go:74] Failed to schedule: &{{ } {nginx-id-01  default /api/v1beta1/pods/nginx-id-01?namespace=default 879c1378-dfc8-11e4-9312-0a7a01caff03 15 2015-04-10 21:28:28 +0000 UTC map[name:foo] map[]} {[] [{nginx-01 dockerfile/nginx []  [{ 31000 80 TCP }]
> [] {map[]} [] 0xc20828aba0 <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] {0x18f9158 <nil> <nil>} ClusterFirst map[] } {Pending []     map[]}}
> I0410 22:12:25.833541   18770 plugin.go:503] Error scheduling nginx-id-01: No suitable offers for pod/task; retrying
> I0410 22:12:25.833582   18770 plugin.go:446] attempting to yield a pod
> I0410 22:12:26.788797   18770 scheduler.go:754] skipping registration request: stopped=false, connected=true, authenticated=true
> I0410 22:12:27.033998   18770 plugin.go:249] Try to schedule pod nginx-id-01
> I0410 22:12:27.034046   18770 fcfs.go:49] failed to find a fit for pod: nginx-id-01
> I0410 22:12:27.034064   18770 scheduler.go:74] Failed to schedule: &{{ } {nginx-id-01  default /api/v1beta1/pods/nginx-id-01?namespace=default 879c1378-dfc8-11e4-9312-0a7a01caff03 15 2015-04-10 21:28:28 +0000 UTC map[name:foo] map[]} {[] [{nginx-01 dockerfile/nginx []  [{ 31000 80 TCP }]
> [] {map[]} [] 0xc20828aba0 <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] {0x18f9158 <nil> <nil>} ClusterFirst map[] } {Pending []     map[]}}
> I0410 22:12:27.034163   18770 plugin.go:503] Error scheduling nginx-id-01: No suitable offers for pod/task; retrying
> I0410 22:12:27.034205   18770 plugin.go:446] attempting to yield a pod
> I0410 22:12:29.434860   18770 plugin.go:249] Try to schedule pod nginx-id-01
> I0410 22:12:29.434905   18770 fcfs.go:49] failed to find a fit for pod: nginx-id-01
> I0410 22:12:29.434924   18770 scheduler.go:74] Failed to schedule: &{{ } {nginx-id-01  default /api/v1beta1/pods/nginx-id-01?namespace=default 879c1378-dfc8-11e4-9312-0a7a01caff03 15 2015-04-10 21:28:28 +0000 UTC map[name:foo] map[]} {[] [{nginx-01 dockerfile/nginx []  [{ 31000 80 TCP }]
> [] {map[]} [] 0xc20828aba0 <nil> <nil> /dev/termination-log false IfNotPresent {[] []}}] {0x18f9158 <nil> <nil>} ClusterFirst map[] } {Pending []     map[]}}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/219#issuecomment-91706382>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by jaychris** [comment]
Here is the output:

```
[root@mesos01 ~]# curl -s -f http://$servicehost:10251/metrics|egrep -e '^(scheduler|offer)'
scheduler_bind_latency_microseconds{quantile="0.5"} 0
scheduler_bind_latency_microseconds{quantile="0.9"} 0
scheduler_bind_latency_microseconds{quantile="0.99"} 0
scheduler_bind_latency_microseconds_sum 0
scheduler_bind_latency_microseconds_count 0
scheduler_queue_wait_time_microseconds{quantile="0.5"} 0
scheduler_queue_wait_time_microseconds{quantile="0.9"} 0
scheduler_queue_wait_time_microseconds{quantile="0.99"} 0
scheduler_queue_wait_time_microseconds_sum 0
scheduler_queue_wait_time_microseconds_count 0
```

**Comment by jaychris** [comment]
James, apologies for the false alarm, but it looks like the slave in use was having a problem.  My fault for not double checking it.  I resolved it and pod looks to be deploying successfully.

**Comment by jdef** [comment]
No worries. Glad the problem is resolved.

--sent from my phone
