### ISSUE TITLE
Remove google.mesosphere.com from documentation

### ISSUE THREAD

**Issue by joerg84** [mesosphere/kubernetes-mesos#223]
As google.mesosphere.com will be shutdown end of this week we should remove these references from the documentation (including upstream).

**Comment by jdef** [comment]
what about digitalocean.mesosphere.com? someone (michael?) was working on
some command-line based aws tooling -- is that available yet?

if there's no easy way to run this stuff on the cloud then #48 becomes a
high priority I think

On Mon, Apr 13, 2015 at 9:49 PM, Joerg Schad <notifications@github.com>
wrote:

> As google.mesosphere.com will be shutdown end of this week we should
> remove these references from the documentation (including upstream).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/223>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by joerg84** [comment]
Afaik digitalocean.mesosphere.com will be shutdown as well.
@guenter Could you briefly comment on this?

**Comment by joerg84** [comment]
Short collection of affected documentation

https://docs.mesosphere.com/tutorials/kubernetes-mesos-gcp/
https://github.com/mesosphere/kubernetes-mesos
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/mesos.md

**Comment by jdef** [comment]
FWIW there's a link at the top of
https://docs.mesosphere.com/tutorials/kubernetes-mesos-gcp/ that points to
the updated guide in k8s. However, it looks like the markdown wasn't
actually translated properly (see UPDATE:... at the the top of the page).

On Tue, Apr 14, 2015 at 8:45 PM, Joerg Schad <notifications@github.com>
wrote:

> Short collection of affected documentation
>
> https://docs.mesosphere.com/tutorials/kubernetes-mesos-gcp/
> https://github.com/mesosphere/kubernetes-mesos
>
> https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/mesos.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/223#issuecomment-93125525>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by joerg84** [comment]
@jdef Thanks, already submitted a fix.

**Comment by ssk2** [comment]
Closed for now. Looks like we're good apart from the guide in GoogleCloudPlatform/Kubernetes. We'll update that when we have an alternative.
