### ISSUE TITLE
make api_servers flag consistent between scheduler and controller manager

### ISSUE THREAD

**Issue by joerg84** [mesosphere/kubernetes-mesos#236]
We should make the flagname used to specify the apiserver consistent (i.e. currently _master_ in controller-manger and _api-servers_ in scheduler). 

 $ ./bin/km controller-manager \
   *--master=$servicehost:8888 \*
  --cloud_config=./mesos-cloud.conf
 
 $ ./bin/km scheduler \
   --address=${servicehost} \
   --etcd_servers=http://${servicehost}:4001 \
   --mesos_user=root \
   *--api_servers=$servicehost:8888*

**Comment by jdef** [comment]
As per offline discussion this is an upstream issue

--sent from my phone
