### ISSUE TITLE
docker images referenced in examples/ no longer work

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#241]
for example, dockerfile/nginx has been superseded by library/nginx

**Comment by jayunit100** [comment]
Great catch!!!! 

This really needs to he addressed.  I've suggested before and so have others like @Timothysc . . that example images should be in a kubernetes namespace.

I personally think all build requirements should also be committed to the code itself.

Who owns the kubernetes images namespace on docker? Can we create a top level images/ directory that pushes to it...and builds images?  That would make things a lot cleaner and simpler.  It also would allow us to more confidently include examples into e2e tests

**Comment by jdef** [comment]
self-assigning this since i've incorporated a fix into #242

**Comment by jdef** [comment]
@jayunit100 not sure who specifically owns the k8s namespace on dockerhub, though I suspect that @brendandburns may know.

**Comment by tomuench** [comment]
@jdef maybe you can fix the controller-nginx.json-Definition, too. There is the "old" Docker-Image  **dockerfile/nginx** defined. 

Thanks

**Comment by jdef** [comment]
done
