### ISSUE TITLE
publish service discovery info for pod-tasks

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#256]
- dependent upon (blocked) mesos-go protobuf updates

**Comment by jdef** [comment]
what we really want is service discovery info for kubernetes **services**. it might be nice if we could tell mesos-dns to ignore k8s pod tasks by setting their `discoveryInfo.visibility` to `FRAMEWORK`.

**Comment by jdef** [comment]
experimental support for taskInfo.discoveryInfo : https://github.com/kubernetes/kubernetes/pull/19696

**Comment by sttts** [comment]
Note that it is not enough to resolve k8s service names using mesos-Dns. We
also have to launch kube-proxy on each host to create the iptables rules.

**Comment by jdef** [comment]
correct @sttts, the above experimental support is expose records at a per-pod level via mesos-dns (which is better than what we support right now .. which is nothing for pods or services)

**Comment by jdef** [comment]
cherry-picked into v0.7.2
