### ISSUE TITLE
Config file configuration

### ISSUE THREAD

**Issue by altvnk** [mesosphere/kubernetes-mesos#267]
Is there any examples of configuring kuberenetes-mesos via config-files? I'm trying to write some unit files to start kubernetes services as daemons, so specifying options in exec command is a bad way i suppose.

**Comment by jdef** [comment]
Mostly flag-based at this point. We just introduced a config file for
low-level (evil) tuning stuff, but that's it. Could you use something like
envdir to scan the filesystem and then build a list of args based on the
environment? Don't have much experience with unit files.

**Comment by jdef** [comment]
Closing this out for now. Please re-open if needed.
