### ISSUE TITLE
Log Rotation within containers

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#287]
The `./docker/bin/km-local` & `./docker/bin/km-complete` scripts currently log component STDOUT/STDERR to files. If run for long enough, these logs will grow to fill the hard drive. They will need to be rotated and culled after a certain size/date.

These scripts were added with https://github.com/mesosphere/kubernetes-mesos/pull/282

The mesosphere/kubernetes-mesos-complete image is also affected, because it runs `./docker/bin/km-complete`. 

The mesosphere/kubernetes-mesos image is not affected, because it just logs to STDOUT/STDERR. By association, docker-compose is also not affected, because docker-compose streams STDOUT/STDERR to the user (with prefix based on container name).

**Comment by sttts** [comment]
The minion does logrotation now for the proxy and the executor+kubelet. I guess this ticket is solved.

**Comment by jdef** [comment]
the scheduler, apiserver, and controller-manager also have log files. in
k8s/dcos these are rotated by s6

**Comment by sttts** [comment]
Right.

I guess the kubernetes-mesos-complete container is not used anymore. The docker-compose cluster has containers logging to stderr. So this does not apply, at least not to our e2e test setup.

**Comment by karlkfi** [comment]
I just nuked the dockerhub mesosphere/kubernetes-mesos-complete, since it's not being used.

No other deployments currently need rotation, afaik. We can re-open this when one does.
