### ISSUE TITLE
Add /snapshot support to docker image build scripts

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#288]
The docker image build scripts (both km & complete) invoke mesosphere/kubernetes-complete:build (built via `./hack/dockerbuild/build`) in order to build the k8sm binaries. This currently defaults to cloning master. These build scripts should be made more flexible in order to handle some user input that enables  optionally using a local workspace (`-v ${project_dir}:/snapshot`).

These scripts were added in https://github.com/mesosphere/kubernetes-mesos/pull/282

**Comment by jdef** [comment]
do we still need this?

**Comment by jdef** [comment]
the k8s/dcos packaging scripts support building from a local source repo.

**Comment by jdef** [comment]
@karlkfi still needed for mesos-docker?

**Comment by sttts** [comment]
mesos-docker is build in the snapshot itself. So I guess does not apply. In the repo there are some (old?) docker container sources. I guess this issue was meant about them.

**Comment by karlkfi** [comment]
obsolete, since we moved to using k8s's build image
