### ISSUE TITLE
Smoke-test kubelet executor

### ISSUE THREAD

**Issue by guenter** [mesosphere/kubernetes-mesos#291]
James tested the kubelet executor in https://github.com/mesosphere/kubernetes/commits/upstream_k8sm with the nginx pod. Need to smoke-test it with replicated pods and the guestbook example.

- [x] run `examples/pod-nginx.json` from k8sm repo
- [x] run `examples/controller-nginx.json` from k8sm repo
- run `examples/guestbook` from k8s repo
  - [x] run `kubectl create -f redis-master-controller.json` and check that redis pod is started
  - [x] run `kubectl create -f redis-master-service.json` and check that service is started
  - [x] check that the service port is accessible with redis-cli on the slave
  - [x] run `kubectl create -f examples/guestbook/redis-slave-controller.json` and check that 2 redis slaves are started
  - [x] run `kubectl create -f examples/guestbook/redis-slave-service.json`and check that the service is started
  - [x] check that the service port is accessible with redis-cli on the slave
  - [x] run `kubectl create -f examples/guestbook/frontend-controller.json` and check that 3 backend pods are started
  - [x] check that the php script works
  - [x] run `kubectl create -f examples/guestbook/frontend-service.json`and check the service is started
  - [x] check that the php script can be accessed via the service on the slave

**Comment by sttts** [comment]
Taking over from @spacejam, who is busy with finishing up the executor tests.

**Comment by sttts** [comment]
Successfully retested `examples/pod-nginx.json`.

**Comment by sttts** [comment]
Also `examples/controller-nginx.json` comes up as expected.

**Comment by sttts** [comment]
Resizing the nginxcontroller from 2 to 4 works

**Comment by sttts** [comment]
The service port is accessible with the virtual (iptables based) IPs 10.10.10.* on the slave.

**Comment by sttts** [comment]
Looks all good. Only issue I was falling over is this: #297. Closing.
