### ISSUE TITLE
Move executor code to upstream fork and add tests

### ISSUE THREAD

**Issue by guenter** [mesosphere/kubernetes-mesos#293]
Move to https://github.com/mesosphere/kubernetes/commits/upstream_k8sm

**Comment by spacejam** [comment]
executor code already in place, just need to add tests

**Comment by sttts** [comment]
@spacejam and myself started yesterday with tests.

**Comment by spacejam** [comment]
up to 68.5% coverage in the executor, up from 10.3%.  https://github.com/mesosphere/kubernetes/pull/10

**Comment by spacejam** [comment]
up to 71.1% https://github.com/mesosphere/kubernetes/pull/14

**Comment by spacejam** [comment]
tests merged
