### ISSUE TITLE
Node controller doesn't list nodes via mesos cloud provider if --minion-regexp is not set

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#297]
Is this a bug of Kubernetes or a lack of documentation on our side?

Compare https://github.com/mesosphere/kubernetes/blob/master/pkg/cloudprovider/nodecontroller/nodecontroller.go#L707

Might be just a matter of a rebase, compare upstream master which changed completely: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/nodecontroller/nodecontroller.go#L404

/cc @jdef

**Comment by jdef** [comment]
the k8sm-controller-manager actually hardcodes the regular expression:
```go
// NewCMServer creates a new CMServer with a default config.
func NewCMServer() *CMServer {
        s := &CMServer{
                CMServer: app.NewCMServer(),
        }
        s.CloudProvider = mesos.PluginName
        s.UseHostPortEndpoints = true
        s.MinionRegexp = "^.*$"
        // if the kubelet isn't running on a slave we don't want the resources to show up on the node
        s.NodeMilliCPU = 0
        s.NodeMemory = *resource.NewQuantity(0, resource.BinarySI)
        return s
}
```
but .. we could need a rebase to fix an upstream issue

**Comment by jdef** [comment]
rebased version deprecates the regexp node filter, no longer used for the nodecontroller.

@sttts is it the case that nodes are not listed *before* you spin up any pod/rc? but then they show up after?

I'm running the k8sm apps as follows:
```shell
$ jobs
[1]   Running                 ./bin/km apiserver --address=${servicehost} --etcd-servers=http://${servicehost}:4001 --portal-net=10.10.10.0/24 --port=8888 --cloud-provider=mesos --cloud-config=./mesos-cloud.conf --v=2 > apiserver.log 2>&1 &
[2]-  Running                 ./bin/km controller-manager --master=$servicehost:8888 --cloud-config=./mesos-cloud.conf --v=2 > controller.log 2>&1 &
[3]+  Running                 ./bin/km scheduler --mesos-master=${mesos_master} --address=${servicehost} --etcd-servers=http://${servicehost}:4001 --mesos-user=root --api-servers=$servicehost:8888 --v=2 > scheduler.log 2>&1 &
```

**Comment by sttts** [comment]
@jdef even after a pod was launched the node was not there. For that reason the executor could not get the node info from the apiserver and was throwing plenty of error messages.

Let me test after your rebase.

**Comment by sttts** [comment]
@jdef Moved to you rebased version, cannot see any nodes now.

**Comment by sttts** [comment]
Started from scratch with a clean etcd. No nodes visible via `kubectl get nodes` after launching a pod (successfully).

**Comment by sttts** [comment]
A brief code study of the new nodecontroller suggests that the kubelet is responsible for updating the node entry on the apiserver. Moreover, it makes heavy use of the cloud provider (e.g. https://github.com/mesosphere/kubernetes/blob/upstream_k8sm/pkg/kubelet/kubelet.go#L688) which we set to nil for good reasons: https://github.com/mesosphere/kubernetes/blob/upstream_k8sm/plugin/contrib/mesos/pkg/executor/service/service.go#L237

**Comment by jdef** [comment]
So even though we set the cloud provider to nil, we should get the default behavior which sets the node externalID to kl.hostname. And that should work just fine for us. I'm going to start over with a clean etcd and see where I end up.

**Comment by jdef** [comment]
Looks like I fudged the latest rebase, forgot to forward along the RegisterNode flag value to KubeletConfig ... working on it now.

**Comment by jdef** [comment]
fixed in https://github.com/mesosphere/kubernetes/commit/5e8c9897cbef407947417608e2989589f662bfed, changes pulled into upstream_k8sm branch here.

**Comment by jdef** [comment]
Thanks!
