### ISSUE TITLE
Typo in launching scheduler - README.md

### ISSUE THREAD

**Issue by parikhyash** [mesosphere/kubernetes-mesos#298]
Command to launch the scheduler has a typo and hence fails:
./bin/km scheduler \
  --mesos_master=${mesos_masster} \     <-----------------------SHOULD BE mesos_master
  --address=${servicehost} \
  --etcd_servers=http://${servicehost}:4001 \
  --mesos_user=root \
  --api_servers=$servicehost:8888 \
  --v=2 >scheduler.log 2>&1 &

**Comment by jdef** [comment]
thanks for reporting this
