### ISSUE TITLE
Multi-port services - Using k8s v0.15.0

### ISSUE THREAD

**Issue by sanjana-bhat** [mesosphere/kubernetes-mesos#301]
We are trying to run a zookeeper quorum on k8sm which requires multi-port services. In order to support this, k8sm needs to pull in k8s v0.15.0. 

https://github.com/GoogleCloudPlatform/kubernetes/issues/1802
https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.15.0

**Comment by jdef** [comment]
we're in the process of submitting the scheduler and executor upstream.
we've rebased as part of that process.

https://github.com/GoogleCloudPlatform/kubernetes/pull/8882

changes are being tracked here:
* https://github.com/mesosphere/kubernetes-mesos/tree/upstream_k8sm (you
can use the km binary from this)

**Comment by sushantk** [comment]
@jdef any idea when this may get merged upstream? does this mean that "km" will ship as part of k8s in future?

**Comment by jdef** [comment]
Hopefully sooner than later. We're aiming for the scheduler and executor to
be included as part of k8s 1.0.  The 'km' binary may not make the official
'1.0' release, but we're aiming for it to (eventually) be included as part
of the core distribution.

**Comment by karlkfi** [comment]
We now support multi-port services in the upstream repo.
