### ISSUE TITLE
Upstream km binary

### ISSUE THREAD

**Issue by guenter** [mesosphere/kubernetes-mesos#308]
The km binary makes development much easier. Base it on the `upstream_k8sm` branch.

**Comment by jdef** [comment]
cmd/km

* package names will change (in upstream we're in plugin/contrib/mesos)
* need to list the binary in the targets list:
  * https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/lib/golang.sh#L22
* drop any references our pkg/version, use the upstream one instead

**Comment by spacejam** [comment]
still needs to be tested, and is dependent on the controller manager being in place:
https://github.com/mesosphere/kubernetes/commit/ebd1e2971b1401ad6634447bbb93192eacf0e98b

**Comment by spacejam** [comment]
https://github.com/mesosphere/kubernetes/pull/16

**Comment by tsenart** [comment]
Merged with: https://github.com/mesosphere/kubernetes/pull/15

**Comment by jdef** [comment]
blocks #340

**Comment by jdef** [comment]
merged upstream
