### ISSUE TITLE
Flannel or other networking support

### ISSUE THREAD

**Issue by sushantk** [mesosphere/kubernetes-mesos#312]
Hello,

I am looking for information on what networking solutions are supported by k8s-mesos. Any pointer will be appreciated.

Regards,
Sushant

**Comment by jdef** [comment]
Two options right now:

1) default docker networking, using the k8sm controller-manager (default
flags)

2) default k8s networking, using the k8sm controller-manager running in
"stock" mode (--host_port_endpoints=false). this assumes that you or your
infra scripts are doing something to ensure that docker-assigned pod IP's
are LAN-routable (and not host-private, as is the default for docker).

If you need/want an overlay network to achieve LAN-routable IP's you must
bring/roll your own.

**Comment by sushantk** [comment]
@jdef thanks for responding. are there any plans to support or document any of the overlay network solution specifically for k8sm?

**Comment by jdef** [comment]
Mesos developers are investigating a global resource allocator for the
purposes of managing IP allocations across the cluster with the intent of
supporting a IP-per-executor and/or IP-per-task model. At a high level this
effort is being tracked here:
https://issues.apache.org/jira/browse/MESOS-2728

The tentative plan is to leverage Mesos global IP resource allocation to
avoid the current workaround implementation that creates endpoints bound to
HostPort:HostIP.

**Comment by jdef** [comment]
xref #5 -- networking TBD

**Comment by sushantk** [comment]
@jdef FYI, we were able to bring up flannel overlay after few fixes from the flannel team.

**Comment by jdef** [comment]
Great - thanks for the update!

**Comment by thilinapiy** [comment]
@sushantk Do you have a public document or a blog post on how to achieve this? Any known issues or side effects? Its great if you can share that!! Thanks!

**Comment by mysterytree** [comment]
@thilinapiy  +1

**Comment by gopinatht** [comment]
@sushantk +1 for @thilinapiy request. Can you share some details of how you got flannel working on Mesos for k8s? We are planning on going the mesos route for k8s and are struggling with having an overlay network solution for k8s

**Comment by mysterytree** [comment]
@gopinatht  Same demand with you . Flannel need close the iptables and  reload it automaticlly. I was concerned about the mesos iptables  may conflict with it .

**Comment by mjschmidt** [comment]
@sushantk +1 for @thilinapiy request. Can you share some details of how you got flannel working on Mesos for k8s? We are planning on going the mesos route for k8s and are struggling with having an overlay network solution for k8s
