### ISSUE TITLE
smoke guestbook example with latest upstream build

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#316]
https://github.com/GoogleCloudPlatform/kubernetes/pull/8882

- run `examples/guestbook` from k8s repo
  - [x] run `kubectl create -f redis-master-controller.json` and check that redis pod is started
  - [x] run `kubectl create -f redis-master-service.json` and check that service is started
  - [x] check that the service port is accessible with redis-cli on the slave
  - [x] run `kubectl create -f redis-slave-controller.json` and check that 2 redis slaves are started
  - [x] run `kubectl create -f redis-slave-service.json`and check that the service is started
  - [x] check that the service port is accessible with redis-cli on the slave
  - [x] run `kubectl create -f frontend-controller.json` and check that 3 backend pods are started
  - [x] check that the php script works
  - [x] run `kubectl create -f frontend-service.json`and check the service is started
  - [x] check that the php script can be accessed via the service on the slave

**Comment by sttts** [comment]
redis-slave service is extremely slow, but works eventually

**Comment by sttts** [comment]
Works as expected.

**Comment by jdef** [comment]
It would be awesome if we had an automated e2e test for this smoke test. I'll file a separate issue.

**Comment by sttts** [comment]
Good idea. Shouldn't be hard with @karlkfi's docker compose scripts.

**Comment by sttts** [comment]
Found an issue I think. Investigating:

The redis-slave's `run.sh` accesses the hostname redis-master. But redis-master is not defined anymore (i.e. in /etc/hosts). Should it? Don't understand how the redis-slave is supposed to resolve the redis-master server by name and not by IP.

**Comment by jdef** [comment]
there are two redis-slave controller examples, one ends with -dns -- that's
only useful when running w/ the kube-dns add-on. You're probably not
testing with kube-dns. The non -dns example should be using environment
variables to locate the redis-master, not dns name.
