### ISSUE TITLE
automated e2e test for guestbook example smoke testing

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#317]
Currently, testing is manual (e.g. see #316). Let's get an automated version of this going so that we're not needless consuming developer cycles as the k8s master baseline keeps shifting.

**Comment by jayunit100** [comment]
Fyi,  iust recently updated the k8petstore shell scripts so it can be easily parameterized. It implements the same architecture as guest book but automatically generates transactions.  It's easy enough to run - just one she'll script - so you can use it as a smoke test with no modifications at all.

**Comment by sttts** [comment]
What's the plan here? Sounds like another (short running) CI job on Teamcity.

**Comment by karlkfi** [comment]
I think what we'll want to do is carve out some basic "smoke tests" from the existing e2e tests and make them easily executable to test that a cluster is up, accessible, and has at least minimal functionality. 

If there aren't good enough existing tests we can add an automated test that uses the guestbook or petstore.

**Comment by jayunit100** [comment]
if your not running all the tests, then at a minimum would suggest to start with 
- networking.go, kubectl.go as the bare minimum to verify cluster functionality from a user 
perspective.   
- then from there, you may want to run the hostDir and emptyDir tests.

**Comment by sttts** [comment]
Fixed with https://github.com/kubernetes/kubernetes/pull/12947 and CI in #305.

**Comment by sttts** [comment]
https://github.com/kubernetes/kubernetes/pull/12947 was merged. Setting `GINKGO_FOCUS=Guestbook.application` will smoke test with the guestbook.
