### ISSUE TITLE
upstream PR (8882): should *not* integrate into core k8s build process

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#329]
Details reasons appear at the end of this comment. Since we're not allowed to hook into the build process, we'll need some way to actually allow users to build the components separately for now. This could mean using a script (Makefile) of some sort in `contrib/mesos`, or else adding new build flags to the k8s build scripts that can flip on (defaulting to off) compilation of k8s-mesos binaries.

PR files affected:
- build/common.sh
  - https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875202
- hack/lib/golang.sh
  - https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875261
  - https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875262

New files (maybe?) needed:
- contrib/mesos/Makefile

@thockin has indicated that we can still push our deps into the upstream Godeps since sub-vendoring is nightmarish given the current tooling.

To quote David (https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion_r31875202):
> For the very short-term (so we can get this submitted now), please comment this out, and we can work on a good plan for making build/test of this code optional. I think there are some good reasons why we don't want to build/test this code by default:
1) it slows down the builds (pointed out by @thockin)
2) it pulls in a bunch of open-source dependencies; even though this code won't run unless the user is running k8s under mesos, I could see some security-conscious people being concerned; OTOH if this code only builds when specifically requested, it increases the security profile of k8s-by-itself slightly
3) although we should make every effort to avoid it, it is conceivable that we might temporarily need to break compatibility between the two codebases in the interest of expediency or exigency; making the default not try to build them together will limit the impact of these temporary events to only people using k8s-on-mesos, rather than everyone using k8s [of course this is a somewhat weak argument, as we could disable building them together in the same PR that introduces the incompatible change; but it might be confusing to users depending on how it is done]

xref https://github.com/GoogleCloudPlatform/kubernetes/pull/8882

**Comment by thockin** [comment]
Sub-vendoring is something very much on my mind right now. It is not well
supported by the myriad deps tools. Also, if there are deps that are not
already covered by the vendored kubernetes deps, you need those either way,
no?

**Comment by jdef** [comment]
@thockins Yes, we'll need them either way. Are you saying that it's OK to
push our Godeps into k8s proper so that we don't have to maintain them
separately? That would be awesome.

**Comment by thockin** [comment]
I am saying I don't think you have a choice :)

**Comment by karlkfi** [comment]
I'm a little nervous about pulling mesos contrib builds/tests out of the vanilla k8s path. I worry that it will mean that no one other than mesosphere will be running those builds/tests, increasing the potential for breakage on master from the onslaught of k8s PRs. If we put in a new build path, is it going to be run in the k8s CI, and as a gate for PRs?

**Comment by thockin** [comment]
We need a general answer for contrib/, but jamming it in every build is not
the answer.

**Comment by karlkfi** [comment]
Sure, I understand not wanting to bog down the vanilla build. We're going to need a mesos-specific build, either with its own makefile or with an env var we sprinkle throughout the build process. I just want to make sure that we're not finding out build/test failures after PRs have already been merged. Would it be possible to add a parallel build for each contrib that still gets run on every PR?

**Comment by thockin** [comment]
Building in CI seems reasonable.

**Comment by karlkfi** [comment]
`KUBERNETES_PROVIDER=vagrant` is used to switch the cluster deploy target and e2e target. How about `KUBERNETES_CONTRIB=mesos` to enable building/testing of contrib/mesos?

**Comment by karlkfi** [comment]
Proposed Solution: https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#issuecomment-110507270
