### ISSUE TITLE
upstream PR (8882): documentation updates

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#330]
David has made a number of suggestions for improvement w/ respect to the docs:
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875208
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875226
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875227
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875228
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875234
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875237
  - responded inline to comments
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875239
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875243
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875246
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875256
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#issuecomment-109802201
  - cmd/kubelet/app/server.go --> contrib/mesos/pkg/executor/service/
  - /pkg/kubelet/ --> contrib/mesos/pkg/executor/
  - plugin/pkg/scheduler/ --> contrib/mesos/pkg/scheduler/plugin.go
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875255
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/8882#discussion-diff-31875251
  - we need to make it clear in comments that we've hard-coded the cpu/memory requirements for now, but only until parent-cgroup integration has been implemented for k8s-mesos (which would allow the executor to parent pods and then be compatible/compliant with expectations of mesos executors w/ respect to resource allocation/management)

xref https://github.com/GoogleCloudPlatform/kubernetes/pull/8882

**Comment by sttts** [comment]
PTAL @jdef

**Comment by sttts** [comment]
Merged #33. Two comments still open.
