### ISSUE TITLE
upstream PR (8882): new PR needed for testify godep upgrade

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#333]
Since upgrading `stretchr/testify` necessitates changes to core k8s code it should be broken out into a standalone PR, separate from the mega-PRs. Once accepted, the mega PR's should be adjusted accordingly (probably via `git rebase HEAD~`)
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#discussion-diff-31859106

I've labeled this as 8882 instead of 9265 because even though the comment was made against 9265, the initial mega-PR is where the change was made.

**Comment by tsenart** [comment]
PTAL

**Comment by jdef** [comment]
LGTM. leaving as WIP until accepted upstream

**Comment by jdef** [comment]
@tsenart i'm adding WIP to this because we've submitted it upstream and are awaiting merge. i've done this with the PR's that I've already submitted. and it's helping me to retain some sanity around PR searches in GH. Please leave the WIP label in place for now.

**Comment by tsenart** [comment]
@jdef: In no way do I want to deprive you of your sanity! Sorry if I took the WIP away :smile:
