### ISSUE TITLE
upstream PR (9265): documentation updates needed

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#335]
David left a lot of review feedback related to code docs:
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558844
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558845
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558847
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558849
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558850
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558851
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558852
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558853
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558854
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558855
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11558864
- [x] https://github.com/GoogleCloudPlatform/kubernetes/pull/9265#commitcomment-11559038

xref https://github.com/GoogleCloudPlatform/kubernetes/pull/9265

**Comment by sttts** [comment]
PTAL @jdef
