### ISSUE TITLE
k8s e2e tests should run on kubernetes-mesos

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#339]
From @davidopp:
> make as many of our existing e2e tests work on k8sm. this is not trivial, but @lavalamp convinced me it is important if we want to keep this working long-term. it will also reveal whether the k8sm stuff is breaking parts of kubernetes that we didn't realize.

**Comment by karlkfi** [comment]
There are a few tickets for this already:
- https://github.com/mesosphere/kubernetes-mesos/issues/307
- https://github.com/mesosphere/kubernetes-mesos/issues/306
- https://github.com/mesosphere/kubernetes-mesos/issues/305
- https://github.com/mesosphere/kubernetes-mesos/issues/303

**Comment by karlkfi** [comment]
As an aggregate status update:
I've mostly tabled the docker-compose solution for now. It fails about 1/3 of the e2e tests because of some serious problems involving networking and disk mounting. AFAIK it needs a networking overlay (like openvswitch) and docker-in-docker (to allow pods to see secret mounts created by the kubelet). These probably aren't impossible, but would require significant investment to get working.

So I'm switching gears and focussing more on the Vagrant option, which has more of a flushed out solution in the vanilla kubernetes repo. Unfortunately, the vagrant provider on master also doesn't fully pass e2e. So I will need to create issues for those problems and get them resolved. In the mean time I'm researching openvswitch and vagrant-mesos. It's worth noting that we can't use playa-mesos because the k8s e2e tests need at least 2 minions.

**Comment by sttts** [comment]
Why does it need a network overlay? Routable IPs in a DinD setup are possible in the 172.17.0.0/42 port range.

**Comment by sttts** [comment]
...172.17.0.0/16 ip range.

**Comment by karlkfi** [comment]
I'm not 100% certain of this. So feel free to correct me.

If you run the tests on the docker host, there shouldn't be a networking issue. The primary issue is that boot2docker on a mac runs the docker server in a vm. 

The simplest solution I could come up with was to run the e2e tests in a docker container. This is the way I got 2/3 of the tests to pass. However, there are still some networking issues (see TeamCity kubernetes-mesos e2e build) that I haven't been able to investigate.

The only other IP-per-container solution that I can think of that allows the containers to be reached from the host on the IPs they broadcast would be to set up OVS on the host so that the docker IPs are on the same virtual switch as the host machine.

**Comment by lavalamp** [comment]
> Unfortunately, the vagrant provider on master also doesn't fully pass e2e. 

@karlkfi Which tests don't pass?

> ...172.17.0.0/16 ip range.

I believe you can configure the range from which apiserver distributes CIDRs to kubelets with startup flags.

**Comment by karlkfi** [comment]
The failures I've seen are now listed here: https://github.com/GoogleCloudPlatform/kubernetes/issues/9681

**Comment by sttts** [comment]
I have run the e2e suite with a DinD setup. Here is the complete output:

  https://gist.github.com/sttts/e5fb813311bb3193357e

Kube-dns is running.

The 12 failures:

* [Fail] ~~Cadvisor [It] should be healthy on every node.~~
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/cadvisor.go:77
* [Fail] **DNS [It] should provide DNS for the cluster**
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/dns.go:138
* [Fail] **Services [It] should release the load balancer when Type goes from LoadBalancer -> NodePort**
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:542
* [Fail] ~~Nodes Resize [BeforeEach] should be able to add nodes.~~ 
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/resize_nodes.go:252
* [Fail] **Density [It] [Performance suite] should allow starting 10 pods per node**
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:188
* [Fail] **Networking [It] should function for intra-pod communication** 
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/networking.go:136
* [Fail] **ServiceAccounts [It] should mount an API token into pods**
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service_accounts.go:58
* [Fail] **Density [It] [Performance suite] should allow starting 3 pods per node** 
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:188
* [Fail] ~~Nodes Network [BeforeEach] should survive network partition.~~ 
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/resize_nodes.go:340
* [Fail] **Nodes Resize [BeforeEach] should be able to delete nodes.*** 
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/resize_nodes.go:252
* [Fail] **Services [It] should be able to change the type and nodeport settings of a service** 
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:413
* **[Fail] DNS [It] should provide DNS for services** 
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/dns.go:138

**Comment by sttts** [comment]
Created issues for those failing tests above:
#345
#346
#347
#348
#349

**Comment by karlkfi** [comment]
Vanilla Kubernetes Vagrant failures (13) are being triaged here: https://github.com/GoogleCloudPlatform/kubernetes/issues/9681

**Comment by karlkfi** [comment]
Crossover between vagrant and docker-in-docker e2e test failures:

### Both
- Cadvisor [It] should be healthy on every node.
- Nodes Network [BeforeEach] should survive network partition.
- Nodes Resize [BeforeEach] should be able to delete nodes.
- Nodes Resize [BeforeEach] should be able to add nodes.
- Services [It] should be able to change the type and nodeport settings of a service
- Services [It] should release the load balancer when Type goes from LoadBalancer -> NodePort

### Docker-In-Docker
- Density [It] [Performance suite] should allow starting 3 pods per node
- Density [It] [Performance suite] should allow starting 10 pods per node
- DNS [It] should provide DNS for the cluster
- Networking [It] should function for intra-pod communication
- ServiceAccounts [It] should mount an API token into pods

### Vagrant
- Density [AfterEach] [Performance suite] should allow starting 30 pods per node
- Kubectl client Update Demo [It] should scale a replication controller
- Kubectl client Update Demo [It] should do a rolling update of a replication controller
- Kubectl client Update Demo [It] should create and stop a replication controller
- PreStop [It] should call prestop when killing a pod
- ReplicationController [It] should serve a basic image on each replica with a public image
- Services [It] should be able to create a functioning NodePort service

I think the density test may have been changed between the branches being tested on either platform. I would expect docker-in-docker to fail 30 if it failed 3 & 10 (if 30 is even still a test).

**Comment by sttts** [comment]
The 10 in the density test was a modification by me due to a lack of resources on my MacBook.

**Comment by jdef** [comment]
this hasn't seen an update in a while. i thought e2e tests were running now via mesos-docker.

can this be closed?

**Comment by karlkfi** [comment]
Well, it's kind of a parent ticket for several other tickets... I believe everything is covered by other open tickets. Any new e2e failures should be covered by new tickets. However, we technically don't have e2e working on CI yet...

**Comment by davidopp** [comment]
Are you guys saying you are running all the k8s e2e tests successfully under k8s-mesos?

**Comment by karlkfi** [comment]
e2e tests are running on the mesos/docker cluster, but they're not all passing yet. Many of the tests take 5m to time out. So the whole suite takes like 5 hours right now. 

We were having unrelated CI issues recently, so they're not running continuously yet, but should be soon. 

I haven't tried running e2e against a DCOS kubernetes deployment recently. Still on the todo list.

**Comment by jdef** [comment]
we're tracking this via milestone E2E Testing Green
