### ISSUE TITLE
move docs from kubernetes-mesos to upstream/contrib/mesos

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#340]
once the code PR's are merged (and this project is rebased to upstream/master) create a PR to move the docs upstream. More specifically all of the items in PROJECT-ROOT/docs including, but not limited to:

- diagrams (arch, network, etc)
- markdowns (overview, ha, etc)

These should be moved upstream to `contrib/mesos/docs`

**Comment by jdef** [comment]
from https://github.com/GoogleCloudPlatform/kubernetes/pull/9667#issuecomment-111232651
> I think we want to somehow merge the docs hosted in the Kubernetes project and the docs hosted in the Mesos project. I think having two sets of docs is just asking for confusion. I can't remember if you filed an issue for this, but if not, can you please do it? I don't care where the merged docs end up being hosted.

**Comment by jdef** [comment]
xref #358

**Comment by sttts** [comment]
done.
