### ISSUE TITLE
executor does not launch if slave hostname is an IP

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#343]
It fails with:

```
service.go:403] failed to create executor driver: lookup 192.168.33.67: invalid domain name
```

The reason is that in `pod_task.go` the `--hostname-override=192.168.33.67` parameter is appended to the executor's command line. This is then passed to the `MesosExecutorDriver` in `NewMesosExecutorDriver` in `executor.go`. Mesos.go's `messenger.ForHostname` finally tries to resolve the IP hostname and fails.

Workaround: set the mesos-slave --ip explicitly, then the hostname is not used to get the binding address.

**Comment by sttts** [comment]
I guess this can be considered a mesos.go issue

**Comment by jdef** [comment]
do we need to update the godeps to pull the mesos-go changes in? or has this already been done?

**Comment by sttts** [comment]
We need the godeps update. Just fall over this bug again.
