### ISSUE TITLE
e2e: Density tests fail due to failedScheduling events

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#346]
source: test/e2e/density.go:188
log: https://gist.github.com/sttts/e5fb813311bb3193357e#file-gistfile1-txt-L1385

**Comment by jdef** [comment]
This test is trying to spin up 20 pods. Possible that there are not enough resources in the testing env to accommodate?

**Comment by sttts** [comment]
They come up successfully (line 1414). But still there are those events.

**Comment by sttts** [comment]
Can it be something around offers which are only accepted for one pod at a time, then waiting for the next offer? just a guess

**Comment by sttts** [comment]
Seems to be gone with latest master. Will reopen if it happens again.
