### ISSUE TITLE
e2e: Networking should function for intra-pod communication

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#347]
source: test/e2e/networking.go:136
log: https://gist.github.com/sttts/e5fb813311bb3193357e#file-gistfile1-txt-L1462

**Comment by sttts** [comment]
The test sets the `NodeName` in the spec explicitly. k8sm uses this though to mark scheduled pods. Hence, the pod never reaches our scheduler.

**Comment by sttts** [comment]
Maybe `NodeName` is not the right property to flag that a pod is scheduled.

**Comment by sttts** [comment]
Ok, same thing is done by k8s's scheduler:
```golang
cache.NewListWatchFromClient(factory.Client, "pods", api.NamespaceAll, fields.Set{client.PodHost: ""}.AsSelector())
```

and in the kubelet itself:
```golang
lw := cache.NewListWatchFromClient(c, "pods", api.NamespaceAll, fields.OneTermEqualSelector(client.PodHost, nodeName))
	newSourceApiserverFromLW(lw, updates)
```

**Comment by sttts** [comment]
All green with GoogleCloudPlatform/kubernetes#11156:

```
Ran 1 of 98 Specs in 32.458 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 97 Skipped PASS
```

**Comment by jdef** [comment]
@sttts can this be closed?

**Comment by sttts** [comment]
Fixed in upstream master.
