### ISSUE TITLE
e2e: ServiceAccounts should mount an API token into pods

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#348]
source: test/e2e/service_accounts.go:58
logs: https://gist.github.com/sttts/e5fb813311bb3193357e#file-gistfile1-txt-L1796

**Comment by sttts** [comment]
All green since we have service accounts:

```
• [SLOW TEST:45.705 seconds]
ServiceAccounts
/Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service_accounts.go:94
  should mount an API token into pods
  /Users/sts/Quellen/mesos/kubernetes/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service_accounts.go:93
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 98 Specs in 45.708 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 97 Skipped PASS
```

**Comment by sttts** [comment]
Fixed in master with docker-compose. DCOS still need service accounts to be enabled.

**Comment by jdef** [comment]
still catching up .. what's required for service accounts to function in
DCOS?

**Comment by sttts** [comment]
We have to pass a service account key to the scheduler and controller manager. All that is implemented in the docker-compose setup. We just have to copy some code from there.

**Comment by sttts** [comment]
also admission plugins must be activated, and something with the root-ca crt. So it's a bit more than the service account key.

**Comment by jdef** [comment]
if e2e is working then can we close this out and open a new issue for the problem in the DCOS packaging?

**Comment by sttts** [comment]
This feature is even used in kube-dns in the mesos-docker cluster. But let's wait until we have a confirmation about the e2e test in CI.
