### ISSUE TITLE
Do kubernetes-mesos slaves need an additional functional networking layer (such as Flannel, OpenVSwitch, ..) installed for their running Pods to communicate with each other? 

### ISSUE THREAD

**Issue by kcao3** [mesosphere/kubernetes-mesos#350]
Hello,

I am currently having a kubernetes-mesos cluster running. I have a question about some networking configuration in a kubernetes-mesos cluster. I would like to know in order to run the Cassandra example, which can be obtained from this link: https://github.com/GoogleCloudPlatform/kubernetes/tree/release-0.18/examples/cassandra, WITH THE NUMBER OF Cassandra REPLICAS MORE THAN ONE, each running on DIFFERENT MESOS-SLAVE machines, and if I would like THESE Cassandra Replicas (or Pods) to SEE EACH OTHER, do I really need to set up an additional networking layer (via the use of technologies such as Flannel, OpenVSwitch, ...) in my kubernetes-mesos cluster? 
Thank you in advance for your help. I really appreciate it. Best regards.

**Comment by jdef** [comment]
Great question. I don't think anyone on the team has tried that yet.

The k8s-mesos scheduler doesn't implement pod-placement constraints right now. One way to force a single instance of a pod per slave is to allocate fixed host ports from the slave's ports range in the replicated pod spec. This should force the scheduler to pick a unique slave for each replicated pod.

I'm not super-familiar with cassandra, but would that be enough to get started with what you're trying to do?

**Comment by sttts** [comment]
The Kubernetes networking documentation discusses the necessary network layout:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/networking.md

Depending on your environment you don't need a full blown overlay network. Instead you might be able to configure docker with disjunct network ranges on each host which are routable between slaves. This can be done in GCE and in setups where you can use arbitrary IP ranges, compare:

  http://sttts.github.io/docker/network/2015/01/31/poor-mens-cluster-container-ips.html.

**Comment by jdef** [comment]
Closing this out for now, please re-open if the original question was not answered.
