### ISSUE TITLE
Docker build container is not working anymore

### ISSUE THREAD

**Issue by altvnk** [mesosphere/kubernetes-mesos#359]
Due to deletion of all code from kubernetes-mesos repo docker image `mesosphere/kubernetes-mesos-build` is not working for now. Is there any similar way to build framework such simple as it was?

**Comment by sttts** [comment]
This is being worked on for the version in the k8s upstream repo.

**Comment by altvnk** [comment]
Thanks for your answer!
I have one more question - does it possible to build framework via kubernetes build image? [k8s guide](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/build)
I need to export environment variable `KUBERNETES_CONTRIB=mesos` to build framework?

**Comment by sttts** [comment]
This could work. I think nobody tried. `KUBERNETES_CONTRIB=mesos` is correct.

**Comment by altvnk** [comment]
Many thanks! I will try it in short.

**Comment by altvnk** [comment]
Unfortunately that doesn't worked, because somehow `contrib` dir is not copied into docker image and build fails. Trying to investigate that and find a way to build binaries. If it would possible i think then your build image will not be needed at all, all the things will be in one place.

**Comment by sttts** [comment]
That would be great. Looking forward to what you find out. We need this for running e2e tests against a docker compose setup of k8sm.

**Comment by jdef** [comment]
I just pushed a new kubernetes-mesos-build image up to dockerhub:

https://registry.hub.docker.com/u/mesosphere/kubernetes-mesos-build/

**Comment by altvnk** [comment]
Oh that's great! Will test it now.

**Comment by altvnk** [comment]
Worked for me, thank you!

**Comment by sttts** [comment]
```
KUBERNETES_CONTRIB=mesos bash -x build/run.sh hack/build-go.sh
```

builds the k8sm binaries just fine.

**Comment by altvnk** [comment]
I was trying to provide env variable via Dockerfile, that's was my mistake...
