### ISSUE TITLE
Scheduler driver address in Docker

### ISSUE THREAD

**Issue by chixq** [mesosphere/kubernetes-mesos#368]
Hi there,

We knew that we could run K8SM in docker so far, but I found that the K8SM container should be placed on the same node of Mesos master.

If I try to launch K8SM framework in Docker on another node, it couldn't be registered successfully. 
Registration works well, but the following not.

```
I0616 08:12:04.770715 18260 master.cpp:1574] Received registration request for framework 'Kubernetes_Docker_1' at scheduler(1)@172.17.0.41:10255
I0616 08:12:04.770828 18260 master.cpp:1638] Registering framework 20150616-075238-1459547402-5050-18247-0000 (Kubernetes_Docker_1) at scheduler(1)@172.17.0.41:10255
I0616 08:12:04.771013 18260 hierarchical.hpp:321] Added framework 20150616-075238-1459547402-5050-18247-0000
I0616 08:12:04.771234 18260 master.cpp:3755] Sending 2 offers to framework 20150616-075238-1459547402-5050-18247-0000 (Kubernetes_Docker_1) at scheduler(1)@172.17.0.41:10255
I0616 08:12:04.816072 18265 http.cpp:516] HTTP request for '/master/state.json'
I0616 08:12:05.371984 18264 master.cpp:1574] Received registration request for framework 'Kubernetes_Docker_1' at scheduler(1)@172.17.0.41:10255
I0616 08:12:05.372086 18264 master.cpp:1625] Framework 20150616-075238-1459547402-5050-18247-0000 (Kubernetes_Docker_1) at scheduler(1)@172.17.0.41:10255 already registered, resending acknowledgement
I0616 08:12:09.166950 18266 master.cpp:1574] Received registration request for framework 'Kubernetes_Docker_1' at scheduler(1)@172.17.0.41:10255
I0616 08:12:09.167044 18266 master.cpp:1625] Framework 20150616-075238-1459547402-5050-18247-0000 (Kubernetes_Docker_1) at scheduler(1)@172.17.0.41:10255 already registered, resending acknowledgement
I0616 08:12:10.641739 18266 master.cpp:1574] Received registration request for framework 'Kubernetes_Docker_1' at scheduler(1)@172.17.0.41:10255
I0616 08:12:10.641834 18266 master.cpp:1625] Framework 20150616-075238-1459547402-5050-18247-0000 (Kubernetes_Docker_1) at scheduler(1)@172.17.0.41:10255 already registered, resending acknowledgement
```

Scheduler driver is binded on Docker container's IP(**172.17.0.4**) which is not accessible from Mesos master.
I've tried set ENV  variable LIBPROCESS_IP=<Node_EXT_IPv4> referred to [ Random IP publishing - Marathon Scheduler #1198 ](https://github.com/mesosphere/marathon/issues/1198), but it seems not work under Docker container environment.

and, at last I had to take the dirty way  to launch the framework container with **Host networking** mode via `docker run --net=host ... `, so that scheduler driver address's is accessible. 

After digging the codes I can't found a flag to set scheduler driver publish(not bind address) address.

Seemed that Mesos is not able to handle driver callback address. [Allow libprocess ip and port to be configured](https://issues.apache.org/jira/browse/MESOS-2376)

Any suggestions ? 
Thank you!

**Comment by karlkfi** [comment]
Not entirely sure what your setup looks like, but I'm working on getting a docker-compose cluster set up. You might be able to reverse engineer what I've done to figure out the configurations you need.

https://github.com/GoogleCloudPlatform/kubernetes/pull/10049
https://github.com/mesosphere/kubernetes/tree/docker-compose
https://github.com/mesosphere/kubernetes/blob/docker-compose/docs/getting-started-guides/mesos-docker.md
https://github.com/mesosphere/kubernetes/blob/docker-compose/cluster/mesos/docker/docker-compose.yml

**Comment by chixq** [comment]
@karlkfi Thanks for your reply.
I've walked through what you have done. But I found that your docker-compose cluster was "All in One" solution, did you try to run a km-scheduler container on Host A, Mesos master ran on Host B?

As I mentioned above,  km-scheduler register itself with container's IP (scheduler(1)@172.17.0.41:10255 ) which Mesos master on another Host can not reach. 

I know maybe several ways (like add routes) to get it work, but could you give me some suggestion on K8SM side, such as scheduler register/report ip could be configured under Docker container env.

**Comment by jdef** [comment]
the mesos/docker cluster just merged upstream. please review to see if your concerns are addressed there. thanks!

**Comment by jdef** [comment]
this issue hasn't been updated in quite some time, closing out. please re-open if needed.
