### ISSUE TITLE
Status of pods on Mesos UI shows STAGING until slave restart 

### ISSUE THREAD

**Issue by sanjana-bhat** [mesosphere/kubernetes-mesos#370]
I have noticed this issue quite often during pod launch. They do not get deployed to mesos slaves until the mesos-slave service is restarted on these hosts. Soon after the restart, the status changes to STARTING. 

I build k8sm from the upstream repo.

**Comment by jdef** [comment]
Could this be related to #367 ?

**Comment by sanjana-bhat** [comment]
Are you suggesting that the issue would go away if we use the latest code?

**Comment by sanjana-bhat** [comment]
@jdef, I have also noticed that sometimes the pods go into LOST state and they are not re-deployed or recovered. I launch pods using replication controller.

**Comment by sanjana-bhat** [comment]
Here is what I see in the scheduler log:

I0625 23:30:45.480677    3353 messenger.go:166] Sending message mesos.internal.LaunchTasksMessage to master@<ip>:5050
I0625 23:30:45.480937    3353 http_transporter.go:107] Sending message to master@<ip>:5050 via http
I0625 23:30:45.481025    3353 http_transporter.go:343] libproc target URL http://<ip>:5050/master/mesos.internal.LaunchTasksMessage
I0625 23:30:48.501025    3353 messenger.go:166] Sending message mesos.internal.LaunchTasksMessage to master@<ip>:5050
I0625 23:30:48.501338    3353 http_transporter.go:107] Sending message to master@<ip>:5050 via http
I0625 23:30:48.501431    3353 http_transporter.go:343] libproc target URL http://<ip>:5050/master/mesos.internal.LaunchTasksMessage
I0625 23:30:51.516510    3353 http_transporter.go:328] Receiving message from master@<ip>:5050, length 285
I0625 23:30:51.516644    3353 messenger.go:343] Receiving message mesos.internal.ResourceOffersMessage from master@<ip>:5050
I0625 23:30:51.516763    3353 scheduler.go:481] Handling resource offers.
I0625 23:30:51.516808    3353 scheduler.go:503] Cached offer 20150625-230151-3218626570-5050-10491-O316 from SlavePID slave(1)@10.88.216.232:5051
I0625 23:30:51.516918    3353 scheduler.go:365] Received offers [&Offer{Id:&OfferID{Value:*20150625-230151-3218626570-5050-10491-O316,XXX_unrecognized:[],},FrameworkId:&FrameworkID{Value:*20150625-230151-3218626570-5050-10491-0001,XXX_unrecognized:[],},SlaveId:&SlaveID{Value:*20150625-230151-3218626570-5050-10491-S0,XXX_unrecognized:[],},Hostname:*host1,Resources:[&Resource{Name:*cpus,Type:*SCALAR,Scalar:&Value_Scalar{Value:*2,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:nil,XXX_unrecognized:[],} &Resource{Name:*mem,Type:*SCALAR,Scalar:&Value_Scalar{Value:*2929,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:nil,XXX_unrecognized:[],} &Resource{Name:*ports,Type:*RANGES,Scalar:nil,Ranges:&Value_Ranges{Range:[&Value_Range{Begin:*31000,End:*32000,XXX_unrecognized:[],}],XXX_unrecognized:[],},Set:nil,Role:nil,XXX_unrecognized:[],} &Resource{Name:*disk,Type:*SCALAR,Scalar:&Value_Scalar{Value:*20046,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],}],Attributes:[],ExecutorIds:[],XXX_unrecognized:[],}]
I0625 23:30:53.728152    3353 standalone.go:161] no change to master leadership: 'master@<ip>:5050'
I0625 23:30:54.519745    3353 http_transporter.go:328] Receiving message from master@<ip>:5050, length 328
I0625 23:30:54.519902    3353 messenger.go:343] Receiving message mesos.internal.ResourceOffersMessage from master@<ip>:5050
I0625 23:30:54.519971    3353 scheduler.go:481] Handling resource offers.
I0625 23:30:54.519992    3353 scheduler.go:503] Cached offer 20150625-230151-3218626570-5050-10491-O317 from SlavePID slave(1)@10.88.217.162:5051
I0625 23:30:54.520033    3353 scheduler.go:365] Received offers [&Offer{Id:&OfferID{Value:*20150625-230151-3218626570-5050-10491-O317,XXX_unrecognized:[],},FrameworkId:&FrameworkID{Value:*20150625-230151-3218626570-5050-10491-0001,XXX_unrecognized:[],},SlaveId:&SlaveID{Value:*20150625-230151-3218626570-5050-10491-S1,XXX_unrecognized:[],},Hostname:*host2,Resources:[&Resource{Name:*cpus,Type:*SCALAR,Scalar:&Value_Scalar{Value:*1.75,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],} &Resource{Name:*mem,Type:*SCALAR,Scalar:&Value_Scalar{Value:*2865,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],} &Resource{Name:*disk,Type:*SCALAR,Scalar:&Value_Scalar{Value:*20046,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],} &Resource{Name:*ports,Type:*RANGES,Scalar:nil,Ranges:&Value_Ranges{Range:[&Value_Range{Begin:*31002,End:*32000,XXX_unrecognized:[],}],XXX_unrecognized:[],},Set:nil,Role:**,XXX_unrecognized:[],}],Attributes:[],ExecutorIds:[&ExecutorID{Value:*c8a10f2355ff98cc_k8sm-executor,XXX_unrecognized:[],}],XXX_unrecognized:[],}]

**Comment by jdef** [comment]
There was a recent bugfix that was merged that fixed a problem with very
similar symptoms. Please pull the latest code and test to see if that
resolves the problem you're experiencing.

https://github.com/GoogleCloudPlatform/kubernetes/pull/10219

**Comment by sanjana-bhat** [comment]
@jdef, I pulled in the latest code and I continue to see this issue.

**Comment by jdef** [comment]
Is it possible that you have stale executors running on the slaves? There's normally a suicide timeout threshold that, once expired, shuts down the executor. The timeout only applies if there are no pods running in the system. So if you have pods running, and rebuild the binaries, and redeploy the framework the old executors won't be upgraded if they're still running (lack of auto-upgrade support is also a known issue).

**Comment by sanjana-bhat** [comment]
@jdef, I pulled in the latest code and setup new mesos slaves. I don't see this issue anymore. Although when I launch quite a few pods at the same time for the first time (which need downloading of docker images), some of them get lost and are not recovered. 

I see this error message:
test-controller-nwhzu      0/1      API error (500): Cannot start container 8f27ef1485d35bdcefb0c4e2dd44c877572579222400604086fcb9a20369a329: cannot join network of a non running container: 5cf8978e7e5f3bdc5259b98258bc5478fd1942498987210453e38e3283e0faa9
                                    0        20m

**Comment by jdef** [comment]
I think tasks have 5m to download requisite images. If they haven't started
after that time then they'll either be flagged as FAILED or LOST. If
they're backed by a replication controller then they should spin up
somewhere else in the cluster -- if that's not the case then something is
wrong with RC. Generally speaking, pods without an RC have fewer
availability guarantees.

/cc @sttts @karlkfi

**Comment by sanjana-bhat** [comment]
@jdef, these pods are backed by RC

**Comment by sanjana-bhat** [comment]
rc spec we are using
```json
{
    "kind": "ReplicationController",
    "apiVersion": "v1beta3",
    "metadata": {
        "name": "nimbus-zk-controller"
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "name": "nimbus-zk-container"
        },
        "template": {
            "metadata": {
                "labels": {
                    "name": "nimbus-zk-container"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "zookeeper",
                        "image": "zookeeper:latest",
                        "ports": [
                            {
                                "containerPort": 2181
                            },
                            {
                                "containerPort": 2182
                            },
                            {
                                "containerPort": 2183
                            }
                        ],
                        "env": [
                            {
                                "name": "ZK_SERVER_ID",
                                "value": "1"
                            },
                            {
                                "name": "ZK_SERVER_COUNT",
                                "value": "1"
                            }
                        ]
                    },
                    {
                        "name": "nimbus",
                        "image": "nimbus:latest",
                        "privileged": true,
                        "ports": [
                            {
                                "containerPort": 6627
                            },
                            {
                                "containerPort": 9999
                            }
                        ]
                    }
                ]
            }
        }
    }
}
```

**Comment by sanjana-bhat** [comment]
@jdef, any suggestions on how to fix this? Any timeout setting that we can increase? We keep seeing pods getting lost often when the images are downloaded for the first time and they don't seem to recover even though they are backed by an RC.

**Comment by karlkfi** [comment]
I haven't had a change to debug, but we saw this a lot building our gophercon vm with one local slave. It seemed the docker pull was taking so long (all networking in the VM was slow for hopefully unrelated reasons) that the task lost track of it, but didn't itself get lost or fail, staying staging until you killed the slave. The only workaround was to do a docker pull manually first.

**Comment by jdef** [comment]
this sounds like a problem in the kubelet-executor, which is responsible for monitoring pod/task status and failing after a given timeout window expires if the pod isn't yet operational.

**Comment by hrishimantri** [comment]
@jdef @sttts can we expose a config to override this timeout ?

**Comment by jdef** [comment]
we could probably expose a flag at the executor level. given that the task is stuck in STAGING and not STARTING i'm wondering if there's not another bug at play here. the kubelet-executor sends a STARTING status after the pod has been bound. so stuck in STAGING means that something bad happened between the executor receiving the initial LaunchTask call, and processing the binding. Upon a quick inspection of the code, the other statuses a task could be assigned are KILLED (if the executor received a KillTask during the launch sequence) or else FAILED (internal system error during the launch sequence).

Has this been observed in recent k8s-mesos builds? There have been a number of fixes over the past month, some of which were related to metadata stored in the pod-task structure that's used by the scheduler during reconciliation (and tasks were being killed inappropriately); also related to proper death of the executor process and closure of the pod status updates chan (otherwise the executor process could linger and this could possibly result a delay in the slave deciding that a task had been LOST).

**Comment by hrishimantri** [comment]
@jdef we are still using v1.0.3. @ravilr had filed a bunch of issues in the last week or two. We see that most of them have been addressed but they are not a part of the release v1.1.0-alpha.1. Do we have an ETA on when these changes will be released as a version'd tag ?

**Comment by jdef** [comment]
there's a v1.0.5-based RC. should have been tagged. will double-check

**Comment by jdef** [comment]
https://github.com/mesosphere/kubernetes/releases/tag/untagged-c9d781582625c06084e3

**Comment by sanjana-bhat** [comment]
@jdef the task gets stuck in STARTING and not STAGING. I believe that's the expected behavior. It will be great if the timeout can be exposed as a flag since our docker images are huge and can take more than 5 min for the first docker pull.

**Comment by jdef** [comment]
added #492 to track the request for adding a flag.

is there anything else on this ticket that needs to be addressed?

**Comment by hrishimantri** [comment]
Thanks for the tag @jdef. We are testing out tag v1.0.5-v0.6.4 on our platform. Will keep you posted if we see any issues/regressions.

**Comment by jdef** [comment]
launch timeout is now configurable, closing this out; please re-open if needed.
