### ISSUE TITLE
e2e: Addon update should propagate add-on file changes

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#374]
GoogleCloudPlatform/kubernetes/test/e2e/ad
don_update.go:204

**Comment by jdef** [comment]
- is there an upstream issue filed for this?
- is this blocking any of our e2e testing?

**Comment by sttts** [comment]
It's one of the e2e tests failing. Actually, I am waiting for CI running continuously to get a complete picture (again). Since June several e2e have been added probably. Some we have to skip, some we have to create tickets for to fix on our side. This one would be one to fix in our current cluster state.

**Comment by jdef** [comment]
closing out because it's currently being skipped (for other providers too)
