### ISSUE TITLE
Create docker-compose based e2e test setup without Mesos

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#383]
This would help to verify easily in the same environment how our changes influence the upstream version. Would be very helpful for e2e test debugging.

**Comment by jdef** [comment]
I don't understand this. Mesos is required for k8s-mesos. Can you elaborate?

**Comment by karlkfi** [comment]
The point was that once we created a mesos/docker cluster automation we could backport it to vanilla k8s and just have docker cluster automation. Currently there's no docker-compose automation upstreamed, just a manual setup guide. 

Reasons:
- make testing/developing vanilla k8s easier
- use it to compare our test failures against to rule out docker and shared config as the problem
- the community would be motivated to keep it working (once it exists), which would make it easier for us to keep mesos/docker in sync (compared to all the other clusters that are radically different in setup)

**Comment by sttts** [comment]
As the effort is not that high, I think it would be great to finish this one, for the reasons Karl listed.

**Comment by jdef** [comment]
duplicate of #303
