### ISSUE TITLE
Which binaries needed to run k8sm framework?

### ISSUE THREAD

**Issue by altvnk** [mesosphere/kubernetes-mesos#385]
Which binaries is needed to successfully run framework? Is `km` binary is enough?
Also i'm wondering how executor and proxy get's on mesos-slave? How binaries are transferred there and from where? In case of original k8s it's all clear, binaries are installed and running on node as services. Have some misunderstanding...

**Comment by sttts** [comment]
Most of the logic can be found here: https://github.com/GoogleCloudPlatform/kubernetes/blob/241e87cf9b4bfd810fcd92141ee70ff7a201a96b/contrib/mesos/pkg/scheduler/service/service.go#L262

The km binary will include everything necessary. So if you run the scheduler via km the proxy and the executor are also part of the km binary, compare: https://github.com/GoogleCloudPlatform/kubernetes/blob/18a3932585df6a77e4229849caf1b591ed34b526/contrib/mesos/cmd/km/km.go#L30

The files are served by the mesos scheduler driver http server, usually listening on port 5000, compare https://github.com/GoogleCloudPlatform/kubernetes/blob/241e87cf9b4bfd810fcd92141ee70ff7a201a96b/contrib/mesos/pkg/scheduler/service/service.go#L232
The URIs for the files to transfer to the slave are listed in the CommandInfo which is part of the ExecutorInfo that the scheduler provides. Prior running the executor, the slave will fetch all those files, compare the comment at https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L223

**Comment by altvnk** [comment]
Well, that's explains the process.
Correct me if i wrong - if `km-scheduler` runs in a docker container `mesos-slave` need to know and reach external container address and port to fetch binaries? Or under `mesos-scheduler` you mean service on `mesos-master`?

**Comment by sttts** [comment]
With Mesos scheduler I meant the k8sm scheduler implementing the mesos scheduler interface. So yes, the slave needs routing to that process.

**Comment by altvnk** [comment]
Thanks for your answers! Now i have much more questions than earlier ) On architecture scheme i found some "slave-managed executor container". Now i totally confused. Is this actual information? If `mesos-slave` downloads `km` binary from `km-scheduler` http endpont, where the container comes in??

**Comment by sttts** [comment]
which architecture scheme do you mean?

**Comment by altvnk** [comment]
This one - https://github.com/mesosphere/kubernetes-mesos/tree/master/docs#architecture

**Comment by sttts** [comment]
That's not a docker container. That should be the Linux namespace the executor is started in by the slave, AFAIK.

**Comment by altvnk** [comment]
Oh, okay, that's make sense now. Thank you again.
