### ISSUE TITLE
Container resource values can be used for memory and cpu accounting during a pod schedule

### ISSUE THREAD

**Issue by sanjana-bhat** [mesosphere/kubernetes-mesos#387]
We have encountered cases where mesos slave accepts to schedule pod tasks even though it does not have sufficient resources because of this: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/mesos/pkg/scheduler/podtask/pod_task.go#L241

I know that this is a todo, to use the pod resource settings instead of using hardcoded default values. Until that is implemented, can we sum up the resource limits specified for all the containers under the pod and use that to check against the offered resources? k8s does support specifying resource requirements at the container level.

**Comment by jdef** [comment]
fix has been merged upstream, closing
