### ISSUE TITLE
Service type:"Nodeport" does not open a port on slaves that aren't running any tasks

### ISSUE THREAD

**Issue by sanjana-bhat** [mesosphere/kubernetes-mesos#389]
According to the k8s documentation, nodeport exposes a service on an external port on all nodes in the cluster. This port is a redirect to the port on which km proxy is running. But on mesos slaves that aren't running any tasks, km proxy executor doesn't run and hence connection to the nodeport fails.

**Comment by sttts** [comment]
This is by design I guess. Why would you want to have those ports open on slaves without a running k8sm executor? The k8s apiserver does not even know about those mesos nodes before the first k8s task is started.

**Comment by karlkfi** [comment]
Mesos Slave nodes are not necessarily Kubernetes Minion nodes (running kubelet and kube-proxy) until a kubernetes-mesos task has been scheduled on them. In fact, the the mesos slave node is only really guaranteed to be a Kubernetes Minion while pods are deployed on that minion, tho for now they stay a part of the cluster afterwards. 

We're still trying to figure out how to document these kinds of differences inside the k8s repo, and the docs in this repo are in the process of being migrated to the upstream k8s repo.

**Comment by sanjana-bhat** [comment]
Thanks!
