### ISSUE TITLE
Missing documentation on installation on Mesos Slave

### ISSUE THREAD

**Issue by dmeytin** [mesosphere/kubernetes-mesos#391]
Hi there,
All documentation is about single node deployment and there are no examples of kubelet-executor installation jointly with kube-proxy and pause.
Is it possible to get any help on this?

Thanks a lot,
Dmitry

**Comment by karlkfi** [comment]
the documentation is in a sad state, it's true.
We also have a PR out to upstream most of it: https://github.com/GoogleCloudPlatform/kubernetes/pull/10613
We're unlikely to make big changes until that goes through, but it's definitely on the TODO list.

**Comment by dmeytin** [comment]
Maybe you can refer to some blog/email which could help me to install kubelet-executors?
Thanks!

**Comment by sttts** [comment]
Short answer: you basically need a normal mesos-slave setup and mesos' fetcher transfers the executor and proxy to the slave node when the first task is launched. You shouldn't need "to install the kubelet-executor".

You find some background and pointers here: https://github.com/mesosphere/kubernetes-mesos/issues/385

Also our docker compose setup might help to understand what is needed: https://github.com/mesosphere/kubernetes/blob/docker-compose/cluster/mesos/docker/docker-compose.yml

**Comment by dmeytin** [comment]
Thank you very much!
