### ISSUE TITLE
Apiserver proxy does not work in version 0.6 dcos packages

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#393]
During smoke testing of the latest 0.6 dcos packages, we deployed the guestbook example with kube-dns support and tried to access the frontend service at end via:

    http://<dcos-cluster>/service/kubernetes/api/v1/proxy/namespaces/default/services/frontend

This redirected back to

    http://<dcos-cluster>/api/v1/proxy/namespaces/default/services/frontend/

Moreover, entering the full url with a / at the end did not work either:

    http://<dcos-cluster>/service/kubernetes/api/v1/proxy/namespaces/default/services/frontend

Giving an 404 of openresty.

**Comment by sttts** [comment]
Another day, another cluster.... and it works:

```
curl -i http://52.28.32.237/service/kubernetes/api/v1/proxy/namespaces/default/services/frontend/
HTTP/1.1 200 OK
...
```

We should watch this. Maybe it's just flaky.

**Comment by karlkfi** [comment]
FWIW: I could not repo this issue.

**Comment by sttts** [comment]
Closing this one. Moved the first issue into #396. If we see it again, we reopen it.
