### ISSUE TITLE
DCOS apiserver proxy redirects to wrong url if trailing / is missing

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#396]
http://<dcos-cluster>/service/kubernetes/api/v1/proxy/namespaces/default/services/frontend

redirects to 

http://<dcos-cluster>/api/v1/proxy/namespaces/default/services/frontend/

**Comment by jdef** [comment]
does this break e2e or unit tests? why is this a priority issue?

**Comment by sttts** [comment]
It's priority because it's pretty visible as a bug in the dcos package. In fact we had this very URL in the DCOS k8s docs (no we put the trailing / there to workaround the bug)

**Comment by jdef** [comment]
so why is this a bug if the docs aren't broken?

**Comment by sttts** [comment]
We updated the docs to workaround the bug. The bug is still there.

**Comment by jdef** [comment]
OK. It's not clear to me that this is a k8s bug that we can possibly fix
ourselves. We can leave this here for tracking purposes, but I'm not
convinced that this is a priority to address given that it has DCOS
dependencies (that don't appear likely to change).

**Comment by sttts** [comment]
The admin router should probably fix the redirect. I wonder why it doesn't.

**Comment by sttts** [comment]
@jdef Who might know about this in the DCOS team?

**Comment by jdef** [comment]
ping sebastian

**Comment by sttts** [comment]
Fixed by https://github.com/mesosphere/adminrouter/pull/9
