### ISSUE TITLE
kube-ui does not work with DCOS admin router prefix

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#398]
UI comes up, but doesn't show data.

Launching the image outside of DCOS works fine. So probably it's the admin router prefix.

**Comment by karlkfi** [comment]
Discussion with Cody & Thomas seemed to indicate that they have no intention of adding src/href url-rewriting the same way the kube-proxy does. Further discussion with Thomas is required to determine our recourse.

**Comment by sttts** [comment]
Any chance to add a prefix to kube-ui somehow or relative URLs?

**Comment by sttts** [comment]
Does kube-ui speak directly with the apiserver or does it have an internal proxy somehow?

**Comment by karlkfi** [comment]
The method I used to "fix" guestbook to work through both apiserver's proxy and dcos's proxy was to use exclusively relative links. `/script.js` -> `script.js`

**Comment by sttts** [comment]
Did the same for the non-go guestbook today. Can you take a look at that for kube-ui? Would be great to redirect the service link inside the dcos ui to kube-ui when this is fixed.

**Comment by sttts** [comment]
Fixed in https://github.com/kubernetes/kube-ui/pull/19
