### ISSUE TITLE
TODO: Change all Id to ID.

### ISSUE THREAD

**Issue by yifan-gu** [mesosphere/kubernetes-mesos#4]
In mesos, we use Id which is short for Identification.
But in go's style[1], ID is preferred, so we will consider to change all 'Id' to 'ID'.
[1]
 https://code.google.com/p/go-wiki/wiki/CodeReviewComments#Initialisms

**Comment by jdef** [comment]
this has been low priority for a long, long time. closing out. we can re-open later if we want to address it.

**Comment by tsenart** [comment]
This is a few go-renames away.
