### ISSUE TITLE
download kubectl from apiserver

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#408]
Compare https://github.com/mesosphere/dcos-kubernetes-cli

- dcos image PR: https://github.com/mesosphere/kubernetes-mesos/pull/519
- subcommand release: https://github.com/mesosphere/dcos-kubernetes/releases/tag/v0.1.0
- multiverse PR: https://github.com/mesosphere/multiverse/pull/23

TODO:
- [x] merge mesosphere/kubernetes-mesos PR
- [x] rebuild dcos docker container
- [ ] merge multiverse PR

**Comment by jdef** [comment]
is this still targeting "round 1"? if not, let's move to "round 2"

**Comment by sttts** [comment]
round 2

**Comment by sttts** [comment]
- dcos image PR: https://github.com/mesosphere/kubernetes-mesos/pull/519
- subcommand release: https://github.com/mesosphere/dcos-kubernetes/releases/tag/v0.1.0
- multiverse PR: https://github.com/mesosphere/multiverse/pull/23

**Comment by sttts** [comment]
Who can go through this for a review? @karlkfi @jdef @sur

**Comment by karlkfi** [comment]
Does the release need to say something about `dcos kubectl` too?

The https://github.com/mesosphere/dcos-kubectl readme definitely needs work....

**Comment by jdef** [comment]
we should probably add a ticket somewhere to update the mesosphere-docs
repo with a doc (or updated steps) to make use of the new CLI subcommand. i
don't see such a doc update as a blocker for adding support for it here,
unless this PR negatively interacts with the steps in our current
mesosphere-docs guide.
