### ISSUE TITLE
--log_dir option for k8sm processes doesn't work

### ISSUE THREAD

**Issue by parikhyash** [mesosphere/kubernetes-mesos#427]
While launching the k8sm processes, I'm specifying the --log_dir option to a folder instead of redirecting output. However, I don't see any log files created under the specified path even after disowning the process. Any idea about how the --log_dir option can be used?

I'm also working towards launching all the k8sm processes through systemctl by creating service files under /usr/lib/systemd/system. The processes would then be be launched with "sudo systemctl start k8sm-apiserver". With this approach, I can't redirect output and can only specify the log directory.

The process looks like this after launching..
```
km apiserver --address=x.x.x.x --etcd-servers=http://x.x.x.x:4001 --service-cluster-ip-range=10.10.10.0/24 --insecure-port=6443 --cloud-provider=mesos --cloud-config=mesos-cloud.conf --log_dir=/home/yparikh/log-test --v=1
```

@jdef @karlkfi @sttts

**Comment by hrishimantri** [comment]
@jdef @sttts any updates here ?

**Comment by jdef** [comment]
this combination of flags worked for me:

--v=1 --log_dir=/tmp/apilogs --logtostderr=false

**Comment by parikhyash** [comment]
Yup, it works with both the flags set. Earlier, I wasn't setting the --logtostderr=false flag. Thanks @jdef
