### ISSUE TITLE
k8s v1 guestbook fails with latest k8s/dcos v1.0.x builds 

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#434]

**Comment by karlkfi** [comment]
hmm, PTAL looks kinda silly on an issue. We just using this as a proxy for the k8s PR?

**Comment by jdef** [comment]
yes, waffle added the PTAL since i flagged this as "in review"

**Comment by jdef** [comment]
upstream has merged this, needs cherry-picking into v1.0.x-v0.6.x release

**Comment by karlkfi** [comment]
Should be fixed by https://github.com/kubernetes/kube-ui/pull/19, but we'll need a new kube-ui version published.

**Comment by karlkfi** [comment]
New release requested in https://github.com/kubernetes/kube-ui/issues/23

**Comment by jdef** [comment]
push for new release was promised for today

**Comment by jdef** [comment]
new release has been pushed. kube-ui team is requesting that we test

**Comment by sttts** [comment]
Tested with nginx reverse proxy. I guess in DCOS we cannot test right now due to the systemd/docker issues.

**Comment by sttts** [comment]
Tested in dcos v1.0.5-v0.6.4. Works fine. Closing.

**Comment by sttts** [comment]
This is important for our dcos release.

**Comment by sttts** [comment]
I tested this again. And it seems that master go broken again last night due to https://github.com/kubernetes/kubernetes/pull/12497. Fixed in https://github.com/kubernetes/kubernetes/pull/13738, when merged.

**Comment by sttts** [comment]
Fixed with https://github.com/kubernetes/kubernetes/pull/13758
