### ISSUE TITLE
[e2e] Enforce pod resource limits

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#437]
```
[Fail] SchedulerPredicates [It] validates resource limits of pods that are allowed to run.
/Users/sts/Quellen/mesos/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:86
```

**Analysis**:

The e2e tests use Nodes.Status.Capacity to calculate how many pods with cpu limit 0.1 can be deployed. They expect that the next pod must fail.

In the case of Mesos the capacity of a k8s node is just the raw capacity and strictly larger than the resources Mesos offers. This is because the master itself and the executor also reserve some amount of resources and the e2e expect those to be free.

**Comment by jdef** [comment]
when a slave is started up it's configured with a some subset of resources available on the host. by default, the slave will assume something along the lines of 90% of the resources are available (i don't know the exact number). this forms the basis of the resource pool from which offered resources are drawn from.

it sounds like we need to align nod.status.capacity with the resource capacity reported by the slave (as opposed to the raw capacity of the node).

**Comment by sttts** [comment]
For e2e I expect it's enough to subtract the executor resources from the capacity.

**Comment by sttts** [comment]
The actual test is fixed in master.

The support for labels is added in https://github.com/kubernetes/kubernetes/pull/13036

**Comment by sttts** [comment]
This commit https://github.com/mesosphere/kubernetes/commit/3a9b9777ebcf864411c5bc26dd90af29690fb472 can fix this e2e test by avoid waste of cpu resources due to cpu rounding error in connection with the executor resources.

**Comment by sttts** [comment]
@jdef @karlkfi I would consider the wordaround in https://github.com/mesosphere/kubernetes/commit/3a9b9777ebcf864411c5bc26dd90af29690fb472 as good enough for conformance testing. What do you think? I don't have a better idea on our side or how to modify the test.

Was also thinking about changing the number of cores (i.e. cadvisor MachineInfo) into float, but that would need bigger changes in k8s and the cadvisor sources.

**Comment by jdef** [comment]
I think I need more context w/ respect to the rounding problem. What's the
difference between 1.0 and 0.5 for executor resources? Does 0.5 round off
to 0 in some calculation? where?

**Comment by sttts** [comment]
We tell cadvisor via the MachineInfo how many cores are available. This value is an int.

The e2e test takes this value, subtracts the resources taken by running pods and then tries to launch 10*remainingCores many pods, each with 0.1 cpu shares. remainingCore is float. Then is check that one pod more is not possible.

If we use 0.25 executorCPUs, the remainingCore will not reflect this value because our code only report less node capacity if executorCPUs is at least 1. Otherwise, we waste 0.75 core. Moreover, the e2e test would fail as well because it could launch more pods than expected.

**Comment by jdef** [comment]
I'm fine hacking in the workaround for now, but it sounds like we need to open another ticket to track a proposal/PR against cadvisor/MachineInfo, changing cores from an int to float

**Comment by sttts** [comment]
I have my doubt that such a change will make it into the cadvisor sources. I just saw that they have a concept of cpu/memory layout just next to the cores number. Each cpu core creates a node etc. Having non-int cores does not really fit there.

**Comment by karlkfi** [comment]
This seems like faking the test result, not fixing the problem. Do we really want to claim to be v1.0 conformant when the resource accounting is incompatible?

**Comment by sttts** [comment]
The test is wrong in our context. We don't fake the test result, we fake an environment which matches that of upstream.

**Comment by sttts** [comment]
In other words: Mesos is a dynamic environment in the eyes of a framework, not static as for the kubelet on a cluster without load.

**Comment by karlkfi** [comment]
I still think it's pointless to make the test pass for the sake of having passing tests. If it doesn't match expected behavior and that behavior is part of the spec, then we don't satisfy the spec. We either need to get the spec changed or modify the way the test verifies the spec to ensure that it supports our environment.

**Comment by sttts** [comment]
Yeah, I totally agree. That's why we started the discussion right now.
