### ISSUE TITLE
Report and enforce resource constraints

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#447]
When we launch pods , we'll want to confirm that memory, disk, cpu and so on constraints are honored. Frameworks like mesos will translate these parameters.

**Comment by sttts** [comment]
The resource accounting feature is implemented. Moreover, it is tested (but not successfully yet, compare #437). For the moment it must be deactivated due to #460.

Hence, let's close this issue in favor of these two follow-ups.
