### ISSUE TITLE
Add Mesosphere solution to kubernetes.io

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#449]

**Comment by karlkfi** [comment]
The content that was previously in https://github.com/kubernetes/kubernetes/pull/8832 has been accidentally deleted by force-push, but was probably hopelessly out of date anyway.

If we want to include DCOS as a first class cloud provider then we need to make an upstream getting started guide. That will get it listed on http://kubernetes.io/gettingstarted/.

**Comment by davidopp** [comment]
Note that we already have a Kubernetes-on-Mesos getting started guide (both at the URL @karlkfi mentioned and also https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/mesos.md ) , but we're certainly happy to take updates/improvements to it. (It was written by Mesosphere oflks.)

**Comment by karlkfi** [comment]
DCOS guide (docs): https://github.com/kubernetes/kubernetes/pull/17198
DCOS guide in guide list (docs): https://github.com/kubernetes/kubernetes/pull/17689
DCOS guide in guide list (website): https://github.com/kubernetes/kubernetes/pull/17695

Parent Issue: #617

**Comment by karlkfi** [comment]
Cherry Picks to release-1.1:
DCOS guide (docs): https://github.com/kubernetes/kubernetes/pull/17712
DCOS guide in guide list (docs): https://github.com/kubernetes/kubernetes/pull/18034

TODO: New PR to re-generate the dcos and readme pages in the gh-pages branch per steps in https://github.com/kubernetes/kubernetes/pull/17983

**Comment by karlkfi** [comment]
Turns out #17712 (cherry pick of the new doc) to release-1.1 had bad headers, which had to be fixed by #18051

**Comment by karlkfi** [comment]
gh-pages PR to add dcos docs to website: https://github.com/kubernetes/kubernetes/pull/18048

**Comment by karlkfi** [comment]
ALL DONE!
http://kubernetes.io/gettingstarted/
http://kubernetes.io/v1.1/docs/getting-started-guides/dcos.html
http://kubernetes.io/v1.1/docs/getting-started-guides/README.html
