### ISSUE TITLE
Add slave attributes as node labels

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#452]
Follow-up of #438 to add actual support for node labels.

Impl: https://github.com/kubernetes/kubernetes/pull/13857

**Comment by karlkfi** [comment]
Is this required for k8s v1 conformance?

**Comment by sttts** [comment]
Yes. NodeSelector support.

**Comment by jdef** [comment]
why was this closed? the upstream ticket hasn't been merged yet

**Comment by sttts** [comment]
My mistake. I thought it was.

**Comment by ravilr** [comment]
@sttts this doesn't seem to be part of release-1.1 branch in upstream. Any chances of cherry picking it there. or is there going to be a mesosphere-kubernetes release soon? Thanks.

**Comment by sttts** [comment]
@ravilr we will create our release branch on-top of release-1.1 and cherry-pick a number of patches from master, including this one.

**Comment by jdef** [comment]
xref #338
