### ISSUE TITLE
v1.0.3-v0.6.3 package not using latest kubeui image

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#455]
... because I forgot to update the rc yaml. the kubeui-v1.0.3-v0.6.3 image was already pushed.

**Comment by jdef** [comment]
need to test the latest kube-ui image and give feedback upstream

**Comment by karlkfi** [comment]
v2 request: https://github.com/kubernetes/kube-ui/issues/23
v2 release: https://github.com/kubernetes/kube-ui/pull/27
v2 bump in k8s: https://github.com/kubernetes/kubernetes/pull/13274

Put a lgtm on the above PRs after testing.

**Comment by jdef** [comment]
Looks like this is the commit that we want? https://github.com/mesosphere/kubernetes/commit/c64d0d56ddcd891ab4f2552393ca7d430f37cb6f

**Comment by sttts** [comment]
Yes.
