### ISSUE TITLE
kubelet no longer supports SET updates, pod sync is broken

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#463]
upstream PR that broke it:
- https://github.com/kubernetes/kubernetes/pull/13003

they changed the SyncHandler interface.

xref https://github.com/kubernetes/kubernetes/pull/13549

**Comment by jdef** [comment]
part of this fix should include a unit test that ensures that we catch things like this in the future.

**Comment by jdef** [comment]
todo: raise awareness to the google team

**Comment by sttts** [comment]
I don't think any non-e2e test would have caught this issue. In the mentioned PR they essentially ripped out the code which handled PodConfigNotificationSnapshotAndUpdates config sources in the kubelet, replaced with some log.Error if a kubelet.SET update still arrives. No compilation error whatsoever.

The only point we can make is that there was a change in the patch in our contrib directory, but we did not get included in the review process.
