### ISSUE TITLE
Executor suicide doesn't result in its child process kube-proxy getting killed

### ISSUE THREAD

**Issue by ravilr** [mesosphere/kubernetes-mesos#464]
@jdef 
using k8sm v1.0.3 version (kubernetes release)

we are seeing this behaviour:
when k8sm scheduler framework issues killTask for all pods launched by a slave executor, the executor seems to start a suicide timer countdown. Eventually the executor process exits, but the kube-proxy process it had launched remains running.
when the master launches a new executor on that slave node, the new kube proxy fails to bind to its listen port due to the address/port being already in use.

Isn't the executor shutdown (abnormal or normal exit) supposed to cleanup the kube-proxy process also.

**Comment by jdef** [comment]
thanks for reporting this. should be resolved with #458
