### ISSUE TITLE
k8sm scheduler restart seems to be killing all pod tasks in the cluster

### ISSUE THREAD

**Issue by ravilr** [mesosphere/kubernetes-mesos#466]
xref https://github.com/kubernetes/kubernetes/pull/13566

@jdef 
Observed in kubernetes v1.0.3 release.  Is this an expected current behaviour? are we missing any setting that is preventing the framework to recover the executor tasks on re-registration:

KUBE_SCHEDULER_ARGS="--mesos-user=mesos --reconcile-interval=60 --executor-suicide-timeout=2m0s --ha --km-path=file:///usr/bin/km --cluster-dns=10.10.10.10 --cluster-domain=k8sm.local --api-servers=apiserver:6443 --allow-privileged=true"

On scheduler restart, we are seeing that issues killTask of all pods:
    E0830 07:48:17.291873   31546 scheduler.go:500] killing non-terminal, unrecoverable task pod.2c9d1fd9-4e91-11e5-b2d5-fa163e976c04
    E0830 07:48:17.293458   31546 scheduler.go:500] killing non-terminal, unrecoverable task pod.2c8d6e5f-4e91-11e5-b2d5-fa163e976c04
    E0830 07:48:17.354724   31546 registry.go:319] task killed: &TaskStatus{TaskId:&TaskID{Value:*pod.2c9d1fd9-4e91-11e5-b2d5-fa163e976c04,XXX_unrecognized:[],},State:*TASK_KILLED,Message:*task-killed,Source:*SOURCE_EXECUTOR,Reason:nil,Data:nil,SlaveId:&SlaveID{Value:*20150829-020427-2741915146-5050-11362-S1,XXX_unrecognized:[],},ExecutorId:nil,Timestamp:*1.440920897e+09,Healthy:nil,XXX_unrecognized:[],}, task <nil>
    E0830 07:48:17.354869   31546 registry.go:319] task killed: &TaskStatus{TaskId:&TaskID{Value:*pod.2c8d6e5f-4e91-11e5-b2d5-fa163e976c04,XXX_unrecognized:[],},State:*TASK_KILLED,Message:*task-killed,Source:*SOURCE_EXECUTOR,Reason:nil,Data:nil,SlaveId:&SlaveID{Value:*20150829-020427-2741915146-5050-11362-S1,XXX_unrecognized:[],},ExecutorId:nil,Timestamp:*1.440920897e+09,Healthy:nil,XXX_unrecognized:[],}, task <nil>

Also, in the mesos-slave logs, slave seems to log these lines at every 5 minutes interval, when the podTasks are running:

I0830 21:17:57.341548   430 status_update_manager.cpp:394] Received status update acknowledgement (UUID: f0720454-b67f-0000-2000-0060b67f0000) for task pod.c71238c8-4f03-11e5-9aba-fa163e976c04 of framework 20150829-020427-2741915146-5050-11362-0001
E0830 21:17:57.341737   430 slave.cpp:2266] Failed to handle status update acknowledgement (UUID: f0720454-b67f-0000-2000-0060b67f0000) for task pod.c71238c8-4f03-11e5-9aba-fa163e976c04 of framework 20150829-020427-2741915146-5050-11362-0001: Unexpected status update acknowledgment (UUID: f0720454-b67f-0000-2000-0060b67f0000) for task pod.c71238c8-4f03-11e5-9aba-fa163e976c04 of framework 20150829-020427-2741915146-5050-11362-0001

**Comment by jdef** [comment]
re: the slave logs: I strongly suspect bugs in the mesos-go driver are leading to the appearance of these messages in the slave logs. there's a huge PR in the works for mesos-go that attempts to fix a number of communication problems at the driver level (see https://github.com/mesos/mesos-go/pull/159).

re: scheduler HA, your args look OK to me. Are your mesos slaves set up to support checkpointing of HA frameworks?

http://mesos.apache.org/documentation/latest/slave-recovery/

Also, what version of mesos are you running?

**Comment by ravilr** [comment]
we're running latest mesos-0.23.0. the above doc page says that the checkpointing is enabled by default on slaves in this version. i also see a /meta dir under slave's workdir.

i enabled verbose logs, and i think the issue is the recoverTasks() method during scheduler plugin init() is calling kube api for pods in default namespace (but the pods could belong to multiple namespaces):

I0831 05:32:40.930984   12152 proc.go:148] started process 1
I0831 05:32:40.931048   12152 ha.go:132] scheduler process entered standby stage
I0831 05:32:40.931213   12152 service.go:451] Starting HTTP interface
I0831 05:32:40.931615   12152 service.go:460] registering for election at /mesos/k8sm/framework/Kubernetes/leader with id ef029bd628b31c1f_b2d3976b-499e-4bfb-9778-744c7bffc11d
I0831 05:33:04.940397   12152 service.go:515] validating leadership transition
I0831 05:33:04.940412   12152 election.go:58] elected as master
I0831 05:33:04.940470   12152 ha.go:154] scheduler process entered master stage
I0831 05:33:04.940479   12152 service.go:620] performing deferred initialization
I0831 05:33:04.940511   12152 scheduler.go:220] initializing kubernetes mesos scheduler
I0831 05:33:04.940746   12152 debugging.go:101] curl -k -v -XGET  -H "User-Agent: km/v1.0.3 (linux/amd64) kubernetes/e32fdb5" http://10.78.110.163:6443/api/v1/namespaces/default/pods
I0831 05:33:04.942659   12152 debugging.go:120] GET http://10.78.110.163:6443/api/v1/namespaces/default/pods 200 OK in 1 milliseconds
I0831 05:33:04.942671   12152 debugging.go:126] Response Headers:
I0831 05:33:04.942679   12152 debugging.go:129]     Content-Type: application/json
I0831 05:33:04.942687   12152 debugging.go:129]     Date: Mon, 31 Aug 2015 05:33:04 GMT
I0831 05:33:04.942694   12152 debugging.go:129]     Content-Length: 131
I0831 05:33:04.942721   12152 request.go:779] Response Body: {"kind":"PodList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/default/pods","resourceVersion":"20003"},"items":[]}
I0831 05:33:04.942999   12152 service.go:624] deferred init complete

in my test cluster, i had 2 pods running in kube-system namespace. they were killed during explicit reconciliation:

I0831 05:33:06.078389   12152 scheduler.go:693] explicit reconcile tasks
I0831 05:33:06.078424   12152 messenger.go:187] Sending message mesos.internal.ReconcileTasksMessage to master@10.78.110.163:5050
I0831 05:33:06.078546   12152 http_transporter.go:107] Sending message to master@10.78.110.163:5050 via http
I0831 05:33:06.078576   12152 http_transporter.go:358] libproc target URL http://10.78.110.163:5050/master/mesos.internal.ReconcileTasksMessage
I0831 05:33:06.078799   12152 debugging.go:101] curl -k -v -XGET  -H "User-Agent: km/v1.0.3 (linux/amd64) kubernetes/e32fdb5" http://10.78.110.163:6443/api/v1/pods
I0831 05:33:06.078820   12152 plugin.go:409] Watching for newly created pods
I0831 05:33:06.080109   12152 http_transporter.go:343] Receiving message from master@10.78.110.163:5050, length 279
I0831 05:33:06.080316   12152 http_transporter.go:343] Receiving message from master@10.78.110.163:5050, length 279
I0831 05:33:06.080361   12152 messenger.go:364] Receiving message mesos.internal.StatusUpdateMessage from master@10.78.110.163:5050
I0831 05:33:06.082029   12152 scheduler.go:567] Received status update from  master@10.78.110.163:5050  status source: 
I0831 05:33:06.082052   12152 scheduler.go:586] Sending status update ACK to  master@10.78.110.163:5050
I0831 05:33:06.082075   12152 messenger.go:187] Sending message mesos.internal.StatusUpdateAcknowledgementMessage to master@10.78.110.163:5050
I0831 05:33:06.082173   12152 debugging.go:101] curl -k -v -XGET  -H "User-Agent: km/v1.0.3 (linux/amd64) kubernetes/e32fdb5" http://10.78.110.163:6443/api/v1/namespaces/default/services/k8sm-scheduler
I0831 05:33:06.082126   12152 scheduler.go:403] task status update "TASK_RUNNING" from "SOURCE_MASTER" for task "pod.c71238c8-4f03-11e5-9aba-fa163e976c04" on slave "20150829-020427-2741915146-5050-11362-S1" executor "" for reason "REASON_RECONCILIATION"
W0831 05:33:06.082223   12152 registry.go:240] Ignore status TASK_RUNNING because the task pod.c71238c8-4f03-11e5-9aba-fa163e976c04 is discarded
I0831 05:33:06.082223   12152 messenger.go:364] Receiving message mesos.internal.StatusUpdateMessage from master@10.78.110.163:5050
E0831 05:33:06.082235   12152 scheduler.go:500] killing non-terminal, unrecoverable task pod.c71238c8-4f03-11e5-9aba-fa163e976c04

**Comment by ravilr** [comment]
GET http://apiserver:6443/api/v1/pods returns everything across all namespaces.

**Comment by jdef** [comment]
sounds like a bug to me. thanks so much for digging into this.

**Comment by ravilr** [comment]
One more issue i observed was if the podTask failed for some reason before the executor could add the k8sm meta annotation bindings in the api pod, the scheduler fails to reschedule that pod for ever, unless it is restarted. it fails complaining 'pod reconciliation does not support updates'. 

I0831 05:39:49.009107   12152 http_transporter.go:343] Receiving message from master@master:5050, length 311
I0831 05:39:49.009327   12152 messenger.go:364] Receiving message mesos.internal.StatusUpdateMessage from master@master:5050
I0831 05:39:49.009408   12152 scheduler.go:567] Received status update from  master@master:5050  status source: slave(1)@master:5051
I0831 05:39:49.009480   12152 scheduler.go:586] Sending status update ACK to  master@master:5050
I0831 05:39:49.009549   12152 messenger.go:187] Sending message mesos.internal.StatusUpdateAcknowledgementMessage to master@master:5050
I0831 05:39:49.009650   12152 scheduler.go:403] task status update "TASK_FAILED" from "SOURCE_EXECUTOR" for task "pod.aac3488f-4fa2-11e5-80c1-fa163e976c04" on slave "20150829-020427-2741915146-5050-11362-S1" executor "" for reason "none"
I0831 05:39:49.009782   12152 plugin.go:771] reconcile pod kube-ui-v1-hfoio
I0831 05:39:49.009938   12152 debugging.go:101] curl -k -v -XGET  -H "User-Agent: km/v1.0.3 (linux/amd64) kubernetes/e32fdb5" http://apiserver:6443/api/v1/namespaces/kube-system/pods/kube-ui-v
1-hfoio
I0831 05:39:49.010096   12152 http_transporter.go:107] Sending message to master@master:5050 via http
I0831 05:39:49.010381   12152 http_transporter.go:358] libproc target URL http://master:5050/master/mesos.internal.StatusUpdateAcknowledgementMessage
I0831 05:39:49.013522   12152 debugging.go:120] GET http://master:6443/api/v1/namespaces/kube-system/pods/kube-ui-v1-hfoio 200 OK in 3 milliseconds
I0831 05:39:49.013540   12152 debugging.go:126] Response Headers:
I0831 05:39:49.013549   12152 debugging.go:129]     Content-Type: application/json
I0831 05:39:49.013558   12152 debugging.go:129]     Date: Mon, 31 Aug 2015 05:39:49 GMT
I0831 05:39:49.013566   12152 debugging.go:129]     Content-Length: 1167
I0831 05:39:49.013598   12152 request.go:779] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"kube-ui-v1-hfoio","generateName":"kube-ui-v1-","namespace":"kube-system","selfLink"
:"/api/v1/namespaces/kube-system/pods/kube-ui-v1-hfoio","uid":"aa92d7d8-4fa2-11e5-b450-fa163e976c04","resourceVersion":"20148","creationTimestamp":"2015-08-31T05:39:36Z","labels":{"k8s-app":"kube-
ui","kubernetes.io/cluster-service":"true","version":"v1"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationC
ontroller\",\"namespace\":\"kube-system\",\"name\":\"kube-ui-v1\",\"uid\":\"d43d2202-4f01-11e5-b450-fa163e976c04\",\"apiVersion\":\"v1\",\"resourceVersion\":\"523\"}}"}},"spec":{"containers":[{"na
me":"kube-ui","image":"gcr.io/google_containers/kube-ui:v1.1","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"100m","memory":"50Mi"}},"livenessProbe":{"httpGet":{"p
ath":"/","port":8080,"scheme":"HTTP"},"initialDelaySeconds":30,"timeoutSeconds":5},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","dnsP
olicy":"ClusterFirst"},"status":{"phase":"Pending"}}
E0831 05:39:49.015012   12152 plugin.go:824] pod reconciliation does not support updates; not yet implemented

I think this condition is resolved in https://github.com/kubernetes/kubernetes/pull/12535. Please let me know, if this is something else.

**Comment by jdef** [comment]
This sounds like a regression. Would you mind filing a new bug report for
that? Thanks!
