### ISSUE TITLE
k8sm scheduler never re-schedules pod tasks in its in-memory registry on certain scenarios

### ISSUE THREAD

**Issue by ravilr** [mesosphere/kubernetes-mesos#468]
from https://github.com/mesosphere/kubernetes-mesos/issues/466#issuecomment-136405166:
seen with v1.0.3 kubernetes release

One more issue i observed was if the podTask failed for some reason before the executor could add the k8sm meta annotation bindings in the api pod, the scheduler fails to reschedule that pod for ever, unless it is restarted. it fails complaining 'pod reconciliation does not support updates'. Looks like the scheduler registry has the task with nodeName/slave node missing and when it tries to reconcile the pod, the comparison at https://github.com/kubernetes/kubernetes/blob/v1.0.3/contrib/mesos/pkg/scheduler/plugin.go#L787 fails.

I0831 05:39:49.009107 12152 http_transporter.go:343] Receiving message from master@master:5050, length 311
I0831 05:39:49.009327 12152 messenger.go:364] Receiving message mesos.internal.StatusUpdateMessage from master@master:5050
I0831 05:39:49.009408 12152 scheduler.go:567] Received status update from master@master:5050 status source: slave(1)@master:5051
I0831 05:39:49.009480 12152 scheduler.go:586] Sending status update ACK to master@master:5050
I0831 05:39:49.009549 12152 messenger.go:187] Sending message mesos.internal.StatusUpdateAcknowledgementMessage to master@master:5050
I0831 05:39:49.009650 12152 scheduler.go:403] task status update "TASK_FAILED" from "SOURCE_EXECUTOR" for task "pod.aac3488f-4fa2-11e5-80c1-fa163e976c04" on slave "20150829-020427-2741915146-5050-11362-S1" executor "" for reason "none"
I0831 05:39:49.009782 12152 plugin.go:771] reconcile pod kube-ui-v1-hfoio
I0831 05:39:49.009938 12152 debugging.go:101] curl -k -v -XGET -H "User-Agent: km/v1.0.3 (linux/amd64) kubernetes/e32fdb5" http://apiserver:6443/api/v1/namespaces/kube-system/pods/kube-ui-v
1-hfoio
I0831 05:39:49.010096 12152 http_transporter.go:107] Sending message to master@master:5050 via http
I0831 05:39:49.010381 12152 http_transporter.go:358] libproc target URL http://master:5050/master/mesos.internal.StatusUpdateAcknowledgementMessage
I0831 05:39:49.013522 12152 debugging.go:120] GET http://master:6443/api/v1/namespaces/kube-system/pods/kube-ui-v1-hfoio 200 OK in 3 milliseconds
I0831 05:39:49.013540 12152 debugging.go:126] Response Headers:
I0831 05:39:49.013549 12152 debugging.go:129] Content-Type: application/json
I0831 05:39:49.013558 12152 debugging.go:129] Date: Mon, 31 Aug 2015 05:39:49 GMT
I0831 05:39:49.013566 12152 debugging.go:129] Content-Length: 1167
I0831 05:39:49.013598 12152 request.go:779] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"kube-ui-v1-hfoio","generateName":"kube-ui-v1-","namespace":"kube-system","selfLink"
:"/api/v1/namespaces/kube-system/pods/kube-ui-v1-hfoio","uid":"aa92d7d8-4fa2-11e5-b450-fa163e976c04","resourceVersion":"20148","creationTimestamp":"2015-08-31T05:39:36Z","labels":{"k8s-app":"kube-
ui","kubernetes.io/cluster-service":"true","version":"v1"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationC
ontroller\",\"namespace\":\"kube-system\",\"name\":\"kube-ui-v1\",\"uid\":\"d43d2202-4f01-11e5-b450-fa163e976c04\",\"apiVersion\":\"v1\",\"resourceVersion\":\"523\"}}"}},"spec":{"containers":[{"na
me":"kube-ui","image":"gcr.io/google_containers/kube-ui:v1.1","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"100m","memory":"50Mi"}},"livenessProbe":{"httpGet":{"p
ath":"/","port":8080,"scheme":"HTTP"},"initialDelaySeconds":30,"timeoutSeconds":5},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","dnsP
olicy":"ClusterFirst"},"status":{"phase":"Pending"}}
E0831 05:39:49.015012 12152 plugin.go:824] pod reconciliation does not support updates; not yet implemented

**Comment by ravilr** [comment]
@sttts @jdef asked me to open a new issue for this. please check if this is same as https://github.com/kubernetes/kubernetes/pull/12535 and feel free to mark as duplicate. Thanks!

**Comment by sttts** [comment]
@ravilr the described issue is probably fixed in master by https://github.com/kubernetes/kubernetes/commit/f1a560718c244357ca1ec526cabdfcef74edf64f. It would be great if you could double check that it is really the case.

**Comment by ravilr** [comment]
sure, i had tried to build from master and test this. but, the master branch seems to be broken after sync interface changes in upstream.

**Comment by sttts** [comment]
The sync interface change was merged Aug 26. A version from a day before should work.

**Comment by ravilr** [comment]
Couldn't reproduce this issue with build from git master.  Closing. Thanks!
