### ISSUE TITLE
Investigate overcommitment as an alternative impl for --contain-pod-resources

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#469]
for context, see #460, #461, and the discussion in https://github.com/kubernetes/kubernetes/pull/13421

via @sttts:
>
@jdef I would like to discuss the following temporary solution:
>
we use the full predicate and procurement even in the systemd case we disable cgroup-parent in the systemd case optional: we manually limit cpu+mem of the kube-proxy and kubelet sub-cgroups
optional: we move the minion into a sub-cgroup as well. This way the resource accounting on the Mesos side is fully functional, i.e. Mesos will account for the pod resources correctly. The original executor /mesos/<id> cgroup is resource limited by the mesos containerizer. The pods are resource limited for cpu and memory by Docker.
>
We have two drawbacks (compared to the non-systemd version):
>
- the mesos cgroup isolators do not cover the pods. The pods are only isolated by Docker's built in cgroup logic.
>
- the original executor cgroup /mesos/<id> leads to overcommitment. But this will not harm if we (optionally) isolate the minion and the other process into their own sub-cgroups with manually set cpu+mem limits.
>

via @jdef:
>
Concerns about your proposed approach:
>
- overcomittment: mesos will grow the executor container to consume
resources that will never be used; this takes resources away from what
docker attempts to allocate on the machine. machines with hierarchical
memory policy enforcement will probably be very unhappy with this approach.

via @sttts:
>
The optional items are nothing for this PR of course.
>
About overcommitment:
>
To my understanding of the cpu shares and mem limits of a cgroup is does not "harm" to have one in the system or the hierarchy if the resources are not used. Those resources are not "taken away" from other tasks.
>
On the other hand, ignoring pod limits in the Mesos resource accounting will take away resources (e.g. memory) from the system without Mesos knowing. Mesos will offer those to other tasks and they will die because some k8s pod is using them instead. I don't like that.
>
My expectation (and fear) is that we won't have a better situation regarding systemd, docker and Mesos in the coming months. If my understanding above is correct, telling Mesos about the resources and letting the mesos containerizer assign them to our minion (without actually using them) is the only near-term solution to get any kind of resource accounting for k8sm.

Compare https://github.com/mesosphere/kubernetes-mesos/issues/470 and https://github.com/mesosphere/kubernetes-mesos/issues/471 as optional extensions of this idea.

**Comment by sttts** [comment]
There is `--account-for-pod-resources` now in the scheduler, defaulting to true. If it is false and `--container-pod-resources=false` we use the minimal procurement strategy, i.e. only register the minimum of resources, not the values of the pods.The pod will still be resource limited with the real limits by docker. If `--contain-pod-resources=false` and `--account-for-pod-resources=true` we get the overcommitment described above.

**Comment by sttts** [comment]
Experiments on dcos with `--account-for-pod-resources=true` and `--contain-pod-resource=false` look good.

**Comment by sttts** [comment]
I discussed this topic with @joerg84. Short summary is that this basically works, as long as we (the executor) is aware of the fact that the resources are managed outside of Mesos and that the executor does not use those as well.

**Comment by jdef** [comment]
Sounds like we need a follow-up ticket for making changes in the k8s/dcos
packaging

**Comment by sttts** [comment]
Followed-up by #491. Closing.
