### ISSUE TITLE
scheduler/plugin.go doesn't check for errors during resource allocation

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#475]
Specifically when the Procurement func is invoked (formerly knows as FillFromDetails).

**Comment by jdef** [comment]
see https://github.com/kubernetes/kubernetes/pull/13421/files#r38378360

**Comment by s-urbaniak** [comment]
@jdef I must be missing something or is this all there is to do?
```
        if err := k.api.algorithm().Procurement()(task, details); err != nil {
            return "", err
        }
```

**Comment by jdef** [comment]
yes I think that's all there is to it. we probably should have patched it up when we first noticed it -- not sure why we didn't.

**Comment by s-urbaniak** [comment]
While being there, I'll try to cleanup the `doScheduler` method a bit, it takes an `err`, returns an `err` which seems weird.

**Comment by s-urbaniak** [comment]
xref https://github.com/kubernetes/kubernetes/pull/15976
