### ISSUE TITLE
Vagrant-based setup needs some love

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#48]
* Current box uses an old version of mesos, marathon, docker.io
* Need to add /etc/mesos-master/hostname (to point to the 10.141.141.X address)
* All slaves get the same /etc/mesos-slave/hostname of 10.141.141.10
* In /etc/hosts, mesos-X should resolve to its 10.141.141.X address
* Would be nice to include packer sources to allow for rebuilding the box periodically

**Comment by joerg84** [comment]
Also Golang needs to be updated. 
Does it make sense to use https://github.com/mesosphere/playa-mesos instead of own vagrant setup?

**Comment by jdef** [comment]
I think playa makes sense.

--sent from my phone

**Comment by joerg84** [comment]
Only downside mesos-playa is currently a one node setup...

**Comment by jdef** [comment]
That's unfortunate.

What's the chance that we could get the vagrant image builder scripts
checked into k8sm? That way people could rebuild the image locally to get
the latest version of mesos, et al. running on multiple nodes, and then
deploy k8sm on top of that.

On Tue, Apr 14, 2015 at 11:35 PM, Joerg Schad <notifications@github.com>
wrote:

> Only downside mesos-playa is currently a one node setup...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/48#issuecomment-93176077>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by joerg84** [comment]
Status  Update: 
Mesos-Playa: works (single node setup with GCE Tutorial)
k8m vagrant: updated the box, single node works fine, but multinode does not work (but also with the initial version the multinode mesos cluster does not work for me...)

So if we want a multinode vagrant image we probably have to invest quite some work. So far I only found https://github.com/everpeace/vagrant-mesos to provision multinode vagrant installations...

**Comment by sttts** [comment]
Can all the Vagrant ticket be closed?

**Comment by sttts** [comment]
Can all the Vagrant ticket be closed?

**Comment by karlkfi** [comment]
I believe this ticket was initially to make it easier to install k8s on mesos in vagrant, using playa-mesos (for example), as a kick-the-tires experience. But I think we've moved away from recommending this and are instead recommending DCOS CE. Installation of k8s on custom mesos deployments "should be possible" and is technically supported via open source issues on github or via paid support through Mesosphere, but it not something we're actively investing in.

At some point in the future, it would be nice to improve the open source Mesos getting-started-guide, but we're hoping that the community will contribute once k8s-mesos gains more maturity.
