### ISSUE TITLE
k8s/dcos executors are killed after 5m - 7m, OOM

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#480]
if you watch the mesos console, on the slaves running k8sm executors, you can watch the memory usage slowly creep up. since we allocate 64MB for the executor container, as soon as the memory creep hits 64 .. the executor is killed

the executor is running 3 procs: "minion" bootstrap/controller, kubelet-executor, kube-proxy. we should probably (at least) double the memory that we allocate for the executor

ahh! hard coded values!
```go
        executorCPUs = mresource.CPUShares(0.25) // initial CPU allocated for executor
        executorMem  = mresource.MegaBytes(64.0) // initial memory allocated for executor
//...
        execInfo.Resources = []*mesos.Resource{
                mutil.NewScalarResource("cpus", float64(executorCPUs)+staticPodCPUs),
                mutil.NewScalarResource("mem", float64(executorMem)+staticPodMem),
        }
```

these should be customizable via flag or envvar

**Comment by sttts** [comment]
If the memory grows that much, we should not only make is customizable, but also increase the default to the double.
