### ISSUE TITLE
restarting k8s dcos container is fatal

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#481]
- etcd data is not persisted.
- first task reconciliation kills all running tasks
- kube-dns+kube-ui do not come up again

**Comment by jdef** [comment]
we'll want etcd running outside of k8s-mesos as a first step

**Comment by jdef** [comment]
waiting on #319

**Comment by sttts** [comment]
https://github.com/mesosphere/kubernetes-mesos/issues/319 is resolved. Closing this one because we have persistence now. Further tests are captured in https://github.com/mesosphere/kubernetes-mesos/issues/583.
