### ISSUE TITLE
Support mesos resource roles (public_slave) in k8sm scheduler

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#482]
- As Alice (app dev), using DCOS CE, I want to be able to configure pods to be scheduled on public DCOS slaves.
- As Alice (app dev), using Mesos or DCOS EE, I want to be able to configure pods to be scheduled with resources restricted to specific resource roles. (Not all Mesos clusters have slaves partitioned as "public" using resource roles.)

Note: Alice should _already_ be able to schedule pods using _node selectors_ that map to mesos slave attributes, but only if the resources from those slaves are not restricted to specific roles.

**Comment by jdef** [comment]
it might be fun to run k8s service-loadbalancer on a public slave:
- https://github.com/kubernetes/contrib/tree/master/service-loadbalancer

**Comment by sttts** [comment]
Wondering what the dcos load balancer story is. Having something for k8s is nice, but it's a more general problem.

**Comment by jdef** [comment]
Right now it's "bring your own"

**Comment by sttts** [comment]
Probably the role should be exported as a label to the node. Then the node label predicate can be used to select a role for a pod.

**Comment by jdef** [comment]
a framework should only be offered resources according to the role that the framework registered with. there's no need to label nodes w/ roles

**Comment by sttts** [comment]
can't you schedule some pods on private, some on public slaves? How does marathon do this then?

**Comment by sttts** [comment]
Reading the docs, it seems that you can set the framework role to "public_slave". Then you get offers for "*" **and** "public_slave".

**Comment by jdef** [comment]
Yes, thanks for clarifying. That's because `*` means all roles.

**Comment by s-urbaniak** [comment]
FYI: While doing a first deep-dive I discovered that we are already aware of a mesos role flag in the scheduler.

ref https://github.com/kubernetes/kubernetes/search?q=MesosRole

I'll concentrate on the predicate part.

**Comment by jdef** [comment]
When we claim cpu,mem,port resources (procurement) we may need to set the
role of the Resource's we're using when building up the TaskInfo.

Consider that we also allocate resources for the Executor (and static
pods). If role needs to be set in the Resource's for ExecutorInfo then
we'll have some extra work to do. We probably only want to assign a role to
Resource's of the ExecutorInfo once, for a particular slave - the first
time it's created.

**Comment by s-urbaniak** [comment]
@jdef thanks for the hints, I'll need to read more code to get all the puzzle pieces

**Comment by s-urbaniak** [comment]
Re "Setting roles in the ExecutorInfo's resources": I am collecting collecting infos/docs from core devs since it's not documented very well.

**Comment by s-urbaniak** [comment]
As per discussion w/ @joerg84: The ExecutorInfo's resource roles are independent of launched task resource roles. Executor resources (and their roles) only define its own resource needs. An executor can launch tasks with different resource roles

**Comment by sttts** [comment]
We might pull this into 0.7.0 is it applies easily.
