### ISSUE TITLE
Update `docs/getting-started-guides/README.md` to indicate that k8sm is v1 compliant

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#487]
Blocked by all other tickets in https://github.com/mesosphere/kubernetes-mesos/milestones/EPIC:%20v1.0.x%20Conformance

**Comment by sttts** [comment]
Blocked by lack of compliance.

**Comment by jdef** [comment]
we are conformant on master

**Comment by karlkfi** [comment]
Blocked by getting DCOS added to the guide list: https://github.com/kubernetes/kubernetes/pull/17689
