### ISSUE TITLE
rebase to mesos-go post massive PR159 merge

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#494]
important bug fixes were merged as part of https://github.com/mesos/mesos-go/pull/159; we should update the Godeps accordingly

https://github.com/kubernetes/kubernetes/pull/14524

**Comment by jdef** [comment]
should also update to the latest https://github.com/samuel/go-zookeeper

**Comment by sttts** [comment]
:+1:

**Comment by jdef** [comment]
may want to wait for merge of https://github.com/mesos/mesos-go/pull/189
