### ISSUE TITLE
Pods terminate for minutes on master

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#495]
Staying like that forever:
```
_output/local/go/bin/kubectl get pods  --all-namespaces               
NAMESPACE                 NAME                         READY     STATUS        RESTARTS   AGE
e2e-tests-kubectl-0thiv   update-demo-kitten-l9g7k     1/1       Running       0          4m
e2e-tests-kubectl-0thiv   update-demo-kitten-ltlj4     1/1       Running       0          3m
e2e-tests-kubectl-0thiv   update-demo-nautilus-8zpuj   1/1       Terminating   0          4m
e2e-tests-kubectl-0thiv   update-demo-nautilus-zt9zi   1/1       Terminating   0          4m
kube-system               kube-dns-v9-ttbn9            4/4       Running       0          13m
kube-system               kube-ui-v2-37nqy             1/1       Running       0          13m
```

while seeing this:

```
STEP: Replicas for name=update-demo: expected=2 actual=4
Sep 14 19:42:39.604: INFO: Running '/Users/sts/Quellen/mesos/kubernetes/src/k8s.io/kubernetes/_output/local/bin/darwin/amd64/kubectl --server=https://192.168.65.153:6443 --kubeconfig=/Users/sts/.kube/config get pods -o template --template={{range.items}}{{.metadata.name}} {{end}} --api-version=v1 -l name=update-demo --namespace=e2e-tests-kubectl-0thiv'
Sep 14 19:42:39.686: INFO: update-demo-kitten-l9g7k update-demo-kitten-ltlj4 update-demo-nautilus-8zpuj update-demo-nautilus-zt9zi
```

in

```bash
$ cluster/test-e2e.sh -ginkgo.focus="rolling.update"
```

**Comment by jdef** [comment]
xref https://github.com/kubernetes/kubernetes/pull/13966

**Comment by ravilr** [comment]
@sttts sorry for cross-posting.  still seeing this issue where lost task pods remain in Terminated state:
https://github.com/kubernetes/kubernetes/pull/14614#issuecomment-144605485

**Comment by sttts** [comment]
@ravilr better to continue here:

This patch was only about those pods which were not yet scheduled, i.e. without binding annotation. If you still see this, there is probably another case where the kubelet does not take care of deleting them.

Can you try to follow such a pod in your logs (scheduler, executor and kubelet logs if possible)?

**Comment by ravilr** [comment]
sure, this could be an another case.  It was encountered during below scenario:
1. pod scheduled on to a slave and running.
2. mesos-slave (mesos-0.23 with slave recovery) process on that slave was restarted. killing mesos-slave killed the minion/executor/kubelet also.  docker container(s) still running.
3. mesos-slave on start tries to recover the framework and executor, but fails to do so and issues kill on the docker container(s) belonging to the pod. slave sends task_lost status
4. scheduler sees task_lost status and reconciles the pod (deletes it).  the default gracefulTerminationPeriod is 30secs. 

i'll try to run this scenario again and capture the relevent logs.

**Comment by sttts** [comment]
Thanks for the great analysis. Will create a new ticket for this. Executor recovery is something we have to work on.

**Comment by sttts** [comment]
Follow-up issue: https://github.com/mesosphere/kubernetes-mesos/issues/523

**Comment by ravilr** [comment]
Also, in my setup, mesos-slave is launched as a systemd service. In the default killmode, systemd seems to kill all the processes in the cgroup.
https://issues.apache.org/jira/browse/MESOS-2419 ( note about killMode=process)

i'm going to try with killMode=process  in mesos-slave systemd unit and report back the behavior.

**Comment by jdef** [comment]
There's some ongoing work re: mesos and systemd integration to avoid this
situation. The plan is to run the executor containers in a independent
slice, outside of the slice of mesos-slave; this will allow mesos-slave to
terminate without taking down the executor containers. see
https://issues.apache.org/jira/browse/MESOS-3352
