### ISSUE TITLE
Operation: Ion Cannon

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#496]
Everything Must Go
![tiberium dawn super ion cannon](https://media.giphy.com/media/xTiTnhEVWnNKDJ9ngs/giphy.gif)

- `/examples` - DCOS docs point to the old versioned docs already. New docs have inline examples.
- `/hack/deploy` - Out of sync with current code. need to write docs with marathon examples drawn from the dcos-universe code
- `/hack/lib` - Using upstream binary builder. DCOS image has versioning in the makefile.
- `/hack/patches` - All upstreamed.
- `/hack/build-client-cross.sh`  - Using upstream binary builder.
- `/hack/kube-version.sh`  - DCOS image has versioning in the makefile.
- `/hack/images/km`  - upstreamed as part of mesos/docker cluster
- `/hack/images/etcd`  - obsoleted by etcd-mesos

**Comment by karlkfi** [comment]
![let it burn](http://static.comicvine.com/uploads/original/9/92648/2996484-5171690775-tumbl.gif)

**Comment by air** [comment]
Classic :)
