### ISSUE TITLE
Nodes become "unready" after suicide

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#498]
The node controller in the controller manager updates the "NodeReady" condition of nodes, depending on how long ago the node status was updated by the kubelet (using probeTimestamp).

Hence, a node becomes "unready" when it commits suicide after all pods on it were deleted.

Moreover, with node label support in https://github.com/kubernetes/kubernetes/pull/13857 a node will be "unready" from the first time an offer for it arrives in the scheduler and the scheduler creates the node object.

This is confusing to the user. Moreover, e2e tests check that nodes are ready after the test: https://github.com/kubernetes/kubernetes/blob/750cbe306ee4146cff03e3861e0c8a3a1d2a1c72/test/e2e/util.go#L1779

**Comment by sttts** [comment]
An idea from a discussion with @jdef and @karlkfi:
- add a new node condition "Standby", defaulting to `true` when creating a node from the scheduler.
- the executor will set standby to false.
- on suicide the standby is set to true again.
- add support for proper print out of standby in the kubelet.

Which support is necessary in the node controller?

**Comment by jdef** [comment]
we chatted about this a bit w/ google today. it was suggested that api.Node objects aren't very useful across cloudproviders and that perhaps we should propose making them an optional part of k8s.

**Comment by karlkfi** [comment]
We might actually remove nodes all together from the API if the component registration allows them to be registered as external service targets.

**Comment by sttts** [comment]
Nodes have very specific information like labels and resources. If we want to do scheduling without them, we should drop nodes completely, don't see that having them as external components helps. It would be enough to ask the cloud provider about a node list whereever it is needed (e.g. in e2e tests).

**Comment by jdef** [comment]
kubelet dependency on nodes is the blocker at this point. we'd need to submit a PR to make nodes optional for the kubelet

**Comment by jdef** [comment]
jdef this needs another review

**Comment by sttts** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/16034

**Comment by sttts** [comment]
@jdef PTAL

**Comment by sttts** [comment]
Waiting for review by Google people
