### ISSUE TITLE
Docker illegal flags

### ISSUE THREAD

**Issue by gtcno** [mesosphere/kubernetes-mesos#520]
We are unable to start the nginx pod when following the getting started guide.
We see the following (failing) docker commands being issued. 

```
...
docker -proto tcp -host-ip 0.0.0.0 -host-port 4000 -container-ip 172.17.0.119 -container-port 80
docker -proto tcp -host-ip 0.0.0.0 -host-port 4000 -container-ip 172.17.0.120 -container-port 80
docker -proto tcp -host-ip 0.0.0.0 -host-port 4000 -container-ip 172.17.0.121 -container-port 80
docker -proto tcp -host-ip 0.0.0.0 -host-port 4000 -container-ip 172.17.0.122 -container-port 80
...
```

We also see the following errors in the executor.log

```
...
E0930 12:05:12.153338   21845 pod_workers.go:112] Error syncing pod 158de783-676b-11e5-ab23-0697eafd6b48, skipping: API error (500): Cannot start container 19dec84285ec7471d030ffa42a2fb66a5b5a22e04adefd1bd38cd1a1454e22e2: [8] System error: Invalid argument
E0930 12:05:22.262840   21845 manager.go:1804] Failed to create pod infra container: API error (500): Cannot start container cdaf7ec5fef3b6ee0db91a00d57bfd76863682a97dfd2c41254f64d5e0a88bd7: [8] System error: Invalid argument
; Skipping pod "nginx_default"
...
```

Our docker version is 1.7.0. 
Any help is appreciated.

**Comment by sttts** [comment]
Can you run the dockerd with debugging output? Then you see the exact API calls.

Kubernetes on Mesos uses the normal upstream kubelet runtime, i.e. the code for Docker. Asking in the user channel on the k8s Slack might help.

**Comment by jdef** [comment]
this bug is quite old and numerous bugs have been fixed meanwhile. i'm closing this out for now. please feel free to re-open if this is a problem with the latest release
