### ISSUE TITLE
k8sm scheduler task status update issue

### ISSUE THREAD

**Issue by ravilr** [mesosphere/kubernetes-mesos#522]
@sttts @jdef 
Running upstream kubernetes release-1.1 branch with cherry pick of https://github.com/kubernetes/kubernetes/pull/14614

the scheduler is ignoring status updates from a valid slave.  looks like this change broke this:
https://github.com/kubernetes/kubernetes/pull/14037  (conditional seems wrong , should be hostname == ""/nil)

Seeing this continously every minute in k8sm scheduler logs:

E0930 21:51:46.700403   18605 scheduler.go:383] Ignore status &TaskStatus{TaskId:&TaskID{Value:*pod.766138f1-674f-11e5-a4da-fa163e4a8c06,XXX_unrecognized:[],},State:*TASK_RUNNING,Data:nil,Message:*Reconciliation: Latest task state,SlaveId:&SlaveID{Value:*20150929-020711-628185610-5050-27631-S1,XXX_unrecognized:[],},Timestamp:*1.443649906697952e+09,ExecutorId:nil,Healthy:nil,Source:*SOURCE_MASTER,Reason:*REASON_RECONCILIATION,Uuid:nil,XXX_unrecognized:[],} because the slave does not exist

**Comment by jdef** [comment]
Thanks for reporting, I've cross-ref'd it.

**Comment by jdef** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/14892
