### ISSUE TITLE
liveness probes don't use correct address

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#524]
@karlkfi was testing and we noticed that liveness probes (executed by the kubelet) should have been targeting `containerIP:containerPort` were actually trying to access `containerIP:hostPort`.

**Comment by jdef** [comment]
I'm actually wondering how we possibly pass e2e tests with such a bug

**Comment by karlkfi** [comment]
There are 5 e2e pod tests that test liveness. They're all in conformance. And they seem very flakey when run locally.

```
Pods [Liveness] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe [Conformance]
Pods [Liveness] should have monotonically increasing restart count [Conformance]
Pods [Liveness] should *not* be restarted with a /healthz http liveness probe [Conformance]
Pods [Liveness] should be restarted with a /healthz http liveness probe [Conformance]
Pods [Liveness] should be restarted with a docker exec "cat /tmp/health" liveness probe [Conformance]
```

(I added the `[Liveness]` locally to make focusing easier.)

**Comment by karlkfi** [comment]
Correction: My test cluster was dirty. Testing against a fresh cluster all liveness tests pass.

**Comment by sttts** [comment]
Which means? Do we have a problem or is the issue invalid?

**Comment by jdef** [comment]
needs further investigation, bumping to v0.7.1

**Comment by karlkfi** [comment]
The only conclusion from the prior investigation was that the e2e tests pass fine both in CI and locally.

We originally saw this bug on DCOS. So I'll need to check there.

**Comment by sttts** [comment]
We don't have container IPs on DCOS. maybe that's why.

**Comment by karlkfi** [comment]
Yup. This isn't a bug, technically. It's doing exactly what it's coded to do: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/prober/prober.go#L136-L139

You can override the `HTTPGetAction.Host` in the pod spec, but by default it uses the pod IP.

**Comment by karlkfi** [comment]
I'm not actually sure we want to add a workaround for this... If we fix it and then get pod IP networking in DCOS we'll just have to rip it out again...

**Comment by jdef** [comment]
I remember the problem being the wrong type of port being concatenated with
the IP.

It seems to me that the problem is that PodIP actually references the host
IP (not the container IP) but the **port** that's part of the probed
address is the *container* port, not the associated *host* port.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/prober/prober.go#L161

**Comment by s-urbaniak** [comment]
I am not sure that we have a real issue here, I try to reproduce this and in my test described below everything works as expected.

I followed the instructions as per https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/liveness on a CCM DCOS instance with the freshly released k8sm version (v0.7.0-v1.1.1) and created a livenessProbe'd nginx using:

pod-nginx-healthy.yaml
```
λ cat pod-nginx.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      httpGet:
        path: /
        port: 80
    ports:
    - containerPort: 80
```

As expected I see no liveness errors:
```
λ dcos kubectl describe po nginx
...
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath				Reason			Message
  ─────────	────────	─────	────			─────────────				──────			───────
  34s		33s		3	{scheduler }							FailedScheduling	Error scheduling: No suitable offers for pod/task
  31s		31s		1	{scheduler }							Scheduled		Successfully assigned nginx to 10.0.1.61
  31s		31s		1	{kubelet 10.0.1.61}	implicitly required container POD	Pulled			Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  31s		31s		1	{kubelet 10.0.1.61}	implicitly required container POD	Created			Created with docker id c376b094181d
  31s		31s		1	{kubelet 10.0.1.61}	spec.containers{nginx}			Pulled			Container image "nginx" already present on machine
  31s		31s		1	{kubelet 10.0.1.61}	spec.containers{nginx}			Created			Created with docker id 7c257f33c374
  31s		31s		1	{kubelet 10.0.1.61}	spec.containers{nginx}			Started			Started with docker id 7c257f33c374
  31s		31s		1	{kubelet 10.0.1.61}	implicitly required container POD	Started			Started with docker id c376b094181d
```

Creating an "unhealthy" nginx pod using a liveness URL "/foobar" (implying 404) causes an expected liveness error after the initial delay seconds:

```
λ cat pod-nginx-unhealthy.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-unhealthy
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      httpGet:
        path: /foobar
        port: 80
    ports:
    - containerPort: 80
λ dcos kubectl describe po nginx-unhealthy
...
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath				Reason			Message
  ─────────	────────	─────	────			─────────────				──────			───────
  45s		45s		3	{scheduler }							FailedScheduling	Error scheduling: No suitable offers for pod/task
  42s		42s		1	{scheduler }							Scheduled		Successfully assigned nginx-unhealthy to 10.0.1.61
  42s		42s		1	{kubelet 10.0.1.61}	implicitly required container POD	Pulled			Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  42s		42s		1	{kubelet 10.0.1.61}	implicitly required container POD	Created			Created with docker id 918290efdce6
  42s		42s		1	{kubelet 10.0.1.61}	implicitly required container POD	Started			Started with docker id 918290efdce6
  42s		42s		1	{kubelet 10.0.1.61}	spec.containers{nginx}			Created			Created with docker id 0f278ee510af
  42s		42s		1	{kubelet 10.0.1.61}	spec.containers{nginx}			Started			Started with docker id 0f278ee510af
  21s		21s		1	{kubelet 10.0.1.61}	spec.containers{nginx}			Started			Started with docker id e7863ad31bb4
  21s		21s		1	{kubelet 10.0.1.61}	spec.containers{nginx}			Unhealthy		Liveness probe failed: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.9.7</center>
</body>
</html>

  21s	21s	1	{kubelet 10.0.1.61}	spec.containers{nginx}	Killing	Killing with docker id 0f278ee510af
  21s	21s	1	{kubelet 10.0.1.61}	spec.containers{nginx}	Created	Created with docker id e7863ad31bb4
  42s	21s	2	{kubelet 10.0.1.61}	spec.containers{nginx}	Pulled	Container image "nginx" already present on machine
```

**Comment by s-urbaniak** [comment]
@sttts @jdef @karlkfi as I described above I don't really see a reproducible way, it seems to work as expected. I suggest to close if nobody objects or gives more details on reproducability.

**Comment by karlkfi** [comment]
Can you try with oinker-go? That's where I was seeing the issue. Haven't repro'd in the last few weeks tho.

**Comment by sttts** [comment]
Please extract a minimal (no cassandra, no dependencies) test case from oinker-go which shows the issue. That's good engineering practice. It's not very efficient to debug an app from somebody else.

**Comment by sttts** [comment]
Closing this out. If there is an issue, extract the test case and reopen.

**Comment by jdef** [comment]
re-opening due to premature closure. @karlkfi is toying with readiness/liveness configs and has recently moved oinker-go to mesosphere/. he'll either commit readiness/liveness probe configs, or else submit a PR with the probes (because they're broken and it doesn't make sense to commit broken stuff to master)

**Comment by karlkfi** [comment]
I have confirmed that this bug (as seen by both @jdef and I when prepping for kubecon) has been fixed at some point between then and now.

- Oinker is now in the mesosphere repo: https://github.com/mesosphere/oinker-go
- Oinker has been updated with a new `/ready` endpoint.
- A tcpSocket livenessProbe was added
- A httpGet readinessProbe was added

Minimum steps to show:

```
dcos config prepend package.sources https://github.com/mesosphere/multiverse/archive/version-1.x.zip
dcos package update --validate
dcos package install kubernetes 
# wait for kubernetes to be Running and Healthy
dcos package install cassandra 
# wait for cassandra to be Running and Healthy
go get github.com/mesosphere/oinker-go
dcos kubectl create -f ~/go/src/github.com/mesosphere/oinker-go/kubernetes.yaml
dcos kubectl get pod -l=app=oinker 
# wait for all 3 instances to be Running and then Ready
```

**Comment by jdef** [comment]
awesome. thanks for the follow-up, @karlkfi

**Comment by s-urbaniak** [comment]
cool, thanks @karlkfi !

**Comment by sttts** [comment]
thanks @karlkfi :+1:
