### ISSUE TITLE
add known issue re: broken NodePort accounting

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#530]
this is biting users, we need to doc it: https://github.com/kubernetes/kubernetes/issues/14911

**Comment by karlkfi** [comment]
Also need to add a ticket to actually add nodePort functionality, or link an existing one here.

**Comment by sttts** [comment]
The NodePort functionality works as expected on Mesos. I don't see anything we have to document here. The service ports right now are not controlled by Mesos at all (admittedly they should be controlled as soon as cluster resources are available in Mesos).

**Comment by sttts** [comment]
@jdef @karlkfi I would close this ticket. Is there anything I miss?

**Comment by sttts** [comment]
In fact the issue title does not match the user's bug report IMO. We should clarify the title.

**Comment by sttts** [comment]
Closing this one for the upper reason. Following up: https://github.com/mesosphere/kubernetes-mesos/issues/559
