### ISSUE TITLE
Mesos-DNS is flakey behind Kube-DNS

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#536]
The following output is from k8s on dcos.
- `10.10.10.10` is kube-dns
- `10.0.4.194` is mesos-dns

```
$ kubectl get service kube-dns --namespace=kube-system
NAME       LABELS                                                                           SELECTOR           IP(S)         PORT(S)
kube-dns   k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS   k8s-app=kube-dns   10.10.10.10   53/UDP
                                                                                                                             53/TCP
```

```
$ kubectl exec kube-dns-v8-4nbgq -c skydns --namespace=kube-system -- cat /etc/resolv.conf
options timeout:1
options attempts:3
nameserver 10.0.4.194
nameserver 10.0.0.2
options ndots:5
```

```
$ kubectl get pod oinker-rc-7qmk6 -o template --template='{{.spec.dnsPolicy}}'
ClusterFirst
```

```
$ kubectl exec oinker-rc-7qmk6 -c server -- cat /etc/resolv.conf
nameserver 10.10.10.10
nameserver 10.0.4.194
nameserver 10.0.0.2
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

Digs to kube-dns for k8s targets from k8s pods works fine.
Digs to kube-dns for mesos targets from k8s pods is flakey.
Digs to mesos-dns for mesos targets from k8s pods works fine.

For example, here's two consecutive digs where the second one failed:

```
$ kubectl exec oinker-rc-7qmk6 -c server -- dig @10.10.10.10 leader.mesos

; <<>> DiG 9.9.5-9+deb8u3-Debian <<>> @10.10.10.10 leader.mesos
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57058
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;leader.mesos.			IN	A

;; ANSWER SECTION:
leader.mesos.		60	IN	A	10.0.4.194

;; Query time: 2 msec
;; SERVER: 10.10.10.10#53(10.10.10.10)
;; WHEN: Mon Oct 05 19:22:09 UTC 2015
;; MSG SIZE  rcvd: 46

$ kubectl exec oinker-rc-7qmk6 -c server -- dig @10.10.10.10 leader.mesos

; <<>> DiG 9.9.5-9+deb8u3-Debian <<>> @10.10.10.10 leader.mesos
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 31347
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;leader.mesos.			IN	A

;; AUTHORITY SECTION:
.			3395	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2015100500 1800 900 604800 86400

;; Query time: 1 msec
;; SERVER: 10.10.10.10#53(10.10.10.10)
;; WHEN: Mon Oct 05 19:22:10 UTC 2015
;; MSG SIZE  rcvd: 116
```

However, hitting mesos-dns directly works every time:

```
$ kubectl exec oinker-rc-7qmk6 -c server -- dig @10.0.4.194 leader.mesos

; <<>> DiG 9.9.5-9+deb8u3-Debian <<>> @10.0.4.194 leader.mesos
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38908
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;leader.mesos.			IN	A

;; ANSWER SECTION:
leader.mesos.		60	IN	A	10.0.4.194

;; Query time: 0 msec
;; SERVER: 10.0.4.194#53(10.0.4.194)
;; WHEN: Mon Oct 05 19:27:28 UTC 2015
;; MSG SIZE  rcvd: 46
```

**Comment by karlkfi** [comment]
I was able to make the above work as expected (without flakiness) by explicitly configuring `-nameservers` on skydns. But that isn't a great solution, because it makes the kube-dns config specific to our deployment, instead of just dynamically inheriting the kubelet/mesos-slave dns settings.

**Comment by karlkfi** [comment]
Originally reported in https://github.com/kubernetes/kubernetes/issues/14394 but doesn't seem to be directly related.

**Comment by ArtfulCoder** [comment]
The container image for oinker-rc-7qmk6,. what is it based on ?
I am trying to figure out how dns client is functioning on it.
DNS resolvers (client side) come in multiple flavors..

**Comment by ArtfulCoder** [comment]
https://github.com/mesosphere/kubernetes-mesos/issues/536

**Comment by karlkfi** [comment]
It's a debian ruby/rails image with the oinker app installed: `karlkfi/oinker:shakespeare-k8s`. For more details, see https://github.com/mesosphere/oinker/pull/6

To test dig, I was manually installing dig:

```
kubectl exec oinker-rc-9z441 -c server -- apt-get update
kubectl exec oinker-rc-9z441 -c server -- apt-get install -yyq dnsutils
kubectl exec oinker-rc-9z441 -c server -- dig @10.10.10.10 leader.mesos
```

**Comment by ArtfulCoder** [comment]
Submitted a fix to skydns.
https://github.com/skynetservices/skydns/pull/231

**Comment by ArtfulCoder** [comment]
Closing this issue.
we started off with tracking load related issues on this issue.
it transformed into other skynds flakiness issues too :)

Have a second thread for the flakiness issue..https://github.com/kubernetes/kubernetes/issues/15303

**Comment by ArtfulCoder** [comment]
@karlkfi 
The fix will be in kubernetes 1.1 release.
you can probably close this issue

**Comment by karlkfi** [comment]
https://github.com/kubernetes/kubernetes/pull/15570 upgrades skydns and sets `ns-rotate=false` which should resolve this flakiness. But we'll need to make a new dcos-k8s build to verify.

**Comment by karlkfi** [comment]
I'll test this with oinker now that we have a k8s release with it cherrypicked.

**Comment by karlkfi** [comment]
xref: https://github.com/mesosphere/kubernetes-mesos/issues/537

**Comment by jdef** [comment]
s/k8s release/docker image/

i actually forgot to cherry-pick it into the canonical v1.0.6-v0.6.6 image.
but I did build a dev image shortly after -- you can use by manually
specifying an options file.

at this point i'd rather stop making changes to the open multiverse PR and
just have ken review it as-is so that we can ship something dogfood-able.
then we could bundle this cherry-picked change and the dcos subcommand
stuff together for the next release. i really want to ship the
v1.0.6-v0.6.6 image by the end of the week.

**Comment by jdef** [comment]
karlkfi, does the latest skydns image fix this for you?

**Comment by karlkfi** [comment]
@jdef yes, this issue seems to be resolved with your latest dev image. But it's not clear if we should close this now or wait until it's been cherry-picked into a release branch...

**Comment by jdef** [comment]
It's been cherry-picked: https://github.com/mesosphere/kubernetes/commits/v1.0-v0.6 there's just no "official" image released with it yet. sttts has a multiverse PR in the works - once he builds an image from that it'll carry the commit we want for this issue.

**Comment by karlkfi** [comment]
> "once he builds an image" 

Who's "he"?

Do we have some sort of "master" or nightly builds? If we did I could mark this as done, but if it's pending an official release I'll leave it open.

**Comment by karlkfi** [comment]
auto builds moved to #598

he = @sttts making v0.6.7 PR

Marking as complete.
