### ISSUE TITLE
Update Oinker to deploy on Kubernetes

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#537]
Oinker would be a useful demo for showing a k8s app that depends on another mesos framework (Cassandra).

xref: https://github.com/mesosphere/oinker/pull/6

**Comment by karlkfi** [comment]
https://github.com/mesosphere/oinker/pull/6

**Comment by jdef** [comment]
I backported the skydns container fixes to v1.0-v0.6 branch. you can test it out if you use the `{"kubernetes": { "docker-image": "mesosphere/kubernetes:v1.0.6-v0.6.6-jdef-dev-alpha" } }` image.

**Comment by karlkfi** [comment]
Awesome, thanks!

**Comment by karlkfi** [comment]
```
$ dcos config prepend package.sources \
  https://github.com/mesosphere/multiverse/archive/k8sm-v1.0.6-v0.6.5.zip
$ dcos package update --validate
$ cat >/tmp/options.json <<EOF
{
  "kubernetes": {
    "etcd-mesos-framework-name": "etcd",
    "docker-image": "mesosphere/kubernetes:v1.0.6-v0.6.6-jdef-dev-alpha"
  },
  "marathon": {
    "resource-roles": ["slave_public"]
  }
}
EOF
$ dcos package install etcd-mesos
$ dcos package install --options=/tmp/options.json kubernetes
```

**Comment by karlkfi** [comment]
Oinker still doesn't work, but the dns flakiness seems to be resolved.

On the down side, `kubectl exec` doesn't seem to work even when using the public slave directly, or even from inside the cluster....

```
$ kubectl exec oinker-rc-3g8th -c server -- echo hello
error: Unable to upgrade connection: 404 page not found
```

So i had to ssh into the private slave with an oinker pod running to confirm.

```
$ docker exec de0fc05d99a8 dig cassandra-dcos-node.cassandra.dcos.mesos

; <<>> DiG 9.9.5-9+deb8u3-Debian <<>> cassandra-dcos-node.cassandra.dcos.mesos
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48130
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;cassandra-dcos-node.cassandra.dcos.mesos. IN A

;; ANSWER SECTION:
cassandra-dcos-node.cassandra.dcos.mesos. 60 IN	A 10.0.0.168
cassandra-dcos-node.cassandra.dcos.mesos. 60 IN	A 10.0.0.167
cassandra-dcos-node.cassandra.dcos.mesos. 60 IN	A 10.0.0.169

;; Query time: 2 msec
;; SERVER: 10.10.10.10#53(10.10.10.10)
;; WHEN: Tue Oct 20 01:12:11 UTC 2015
;; MSG SIZE  rcvd: 106
```

```
$ docker exec de0fc05d99a8 cat /etc/resolv.conf
nameserver 10.10.10.10
nameserver 10.0.4.104
nameserver 10.0.0.2
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

**Comment by sttts** [comment]
@karlkfi there is a reason https://github.com/mesosphere/kubernetes-mesos/issues/409 is a prio 1 issue. We need ssl. Otherwise, a number of features are disabled.

**Comment by karlkfi** [comment]
@sttts I got `kubectl exec` and `kubectl logs` working on the previous k8sm release by scheduling the k8s master on the public slave and targeting the IP directly, but that doesn't work now for some reason.

**Comment by karlkfi** [comment]
There seems to be some critical bug related to Rails that doesn't work behind the kubernetes service proxy. Makes it kind of useless. So I rewrote oinker in Go: https://github.com/karlkfi/oinker-go

It currently works through the kube service proxy (when k8s is scheduled on the public slave), but not through the DCOS admin router (because it doesn't do header url rewriting, so redirects break without the path prefix)

**Comment by sttts** [comment]
Where is the connection to a the MVP???

**Comment by karlkfi** [comment]
If we can't deploy an app on k8s that talks to Cassandra via DNS, then I'm not telling anyone to use k8s on Mesos. THAT is pretty much the definition of MVP.

**Comment by sttts** [comment]
Did you fix it?

**Comment by jdef** [comment]
I think the "fix" is a combination of (a) using the go version of oinker,
in conjunction with; (b) deploying on public slaves to avoid the admin
router

**Comment by karlkfi** [comment]
Correct, which is kind of a pain. 

1. The Ruby/Rails version of Oinker doesn't work behind the k8s service proxy, for unknown reasons.
2. Almost nothing works behind the DCOS admin router AND the k8s service proxy.
    - Redirects lose the proxy prefix. So form submissions can't submit to a different url and then redirect back.

**Comment by jdef** [comment]
A better solution would be a way to leverage the new k8s Ingress API and
have something in k8s/dcos that understands how to set up entrypoints on a
dcos cluster.

**Comment by sttts** [comment]
To fix 2. short-term we could do the rewrites in our nginx. Though this will break as soon as the admin router learns rewriting. What do you think?

**Comment by karlkfi** [comment]
cody said he'd accept admin router PRs. apparently if you just make a PR you can have CI build you a dcos image (i think).

**Comment by jdef** [comment]
dcos-image CI will build you an image -- if you use the write builder. the docs were out of date last I checked

**Comment by karlkfi** [comment]
https://github.com/mesosphere/adminrouter/pull/9 fixes oinker through dcos admin router.
Testable with https://github.com/mesosphere/dcos-image/pull/215
