### ISSUE TITLE
Make resource-roles configurable on dcos k8s package

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#538]
xref: ~~https://github.com/mesosphere/multiverse/pull/13~~
* superseded by https://github.com/mesosphere/multiverse/pull/20

This is required in order to allow dcos operators to place the k8s master on specific mesos-slave nodes.

This can be used to put the apiserver on the public slave, for easier testing/debugging/development.

**Comment by jdef** [comment]
Clarification: this is **NOT** for the resource roles to be used when launching pod tasks. This is **only** to allow an operator to specify the `acceptedResourceRoles` setting in the marathon.json that's used to launch the k8s/dcos framework (uber-)container.

**Comment by sttts** [comment]
Any progress here? This is laying around for review for 2 weeks.

**Comment by jdef** [comment]
I'm building a new k8s/dcos image today with 15735 (minion/tasks & mgo fixes) cherry-picked. will also include tyler's changes for etcd-mesos support.

**Comment by karlkfi** [comment]
Is there anything in this or you didn't already canibolize, @jdef?

-Karl

**Comment by jdef** [comment]
The current v1.0.6 PR in mesosphere/multiverse has consumed the changes
from your original PR that introduced support for resource roles w/ respect
to placement of the k8s uber container.

**Comment by karlkfi** [comment]
This can stay open till https://github.com/mesosphere/multiverse/pull/20 is merged then. mesosphere/multiverse#13 is already closed.
