### ISSUE TITLE
Use names of Mesos agents for node names in Kubernetes

### ISSUE THREAD

**Issue by eirslett** [mesosphere/kubernetes-mesos#541]
We have this setup:

```
hostname: worker-001
hostname --fqdn: worker-001.example.com
```

Kubernetes uses `uname -n` to detect node name, which in our case is `worker-001`. The names of the kubernetes nodes don't match the names of the Mesos agents, and I believe that could be the cause of some of our problems.
Kubernetes lets you override node names. Is it possible that this framework can use the agents' names to set kubernetes node names?

**Comment by sttts** [comment]
This should be the case. Which version do you test?

**Comment by eirslett** [comment]
Built right off the master branch. Maybe I've set up something wrong then...

**Comment by sttts** [comment]
Can also be that something got broken on master. We pass the mesos-slave hostname as hostname override to the kubelet.

Do you have the fqdn as mesos-slave hostname? Want to reproduce the issue here.

**Comment by eirslett** [comment]
Yes, the fqdn is the name of the mesos slave. (Both as hostname and also what appears on the Mesos UI's list of slaves.)

**Comment by sttts** [comment]
I have set `--hostname=<IP>.foo` in the mesos-slave command line. The nodes created look like this:
```
_output/local/bin/darwin/amd64/kubectl get nodes
NAME                 LABELS                                                                                                              STATUS    AGE
192.168.65.115.foo   k8s.mesosphere.io/attribute-gen=2011,k8s.mesosphere.io/attribute-rack=1,kubernetes.io/hostname=192.168.65.115.foo   Unknown   12s
192.168.65.120.foo   k8s.mesosphere.io/attribute-gen=2012,k8s.mesosphere.io/attribute-rack=2,kubernetes.io/hostname=192.168.65.120.foo   Unknown   10s
```

Looks good.

**Comment by eirslett** [comment]
Ok, I'll dig in a bit deeper, see if there's something else I've set up wrong!
