### ISSUE TITLE
Conformance/Smoke/Experimental tests should be labeled

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#543]
xref: https://github.com/kubernetes/kubernetes/issues/14763

**Comment by karlkfi** [comment]
One test that is in conformance now, but shouldn't be is called out in #517

**Comment by sttts** [comment]
The important conformance part is done. Experimental and smoke tests are left in kubernetes/kubernetes#14763. Closing this one.
