### ISSUE TITLE
backport minion fixes into v1.0-v0.6 branch

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#549]
MESOS: try not to leave dangling zombie procs when minion controller exits

* xref https://github.com/kubernetes/kubernetes/pull/14489
* [x] TODO: xref #561
* [x] TODO: xref https://github.com/kubernetes/kubernetes/pull/15570

**Comment by sttts** [comment]
Why reopened?

**Comment by sttts** [comment]
got it.
