### ISSUE TITLE
kubelet needs socat and nsenter on slaves

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#553]
We probably need a mechanism to install needed tools on the slave, downloaded via the fetcher.

xref https://github.com/kubernetes/kubernetes/pull/15841

**Comment by sttts** [comment]
/xref https://github.com/mesosphere/docker-containers/pull/30

**Comment by jdef** [comment]
context: supports for ssh-like port forwarding between user's console (via kubectl) and a pod's containers

**Comment by sttts** [comment]
Implemented in https://github.com/kubernetes/kubernetes/pull/16111
