### ISSUE TITLE
Endpoints do not work with udp

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#560]
The port forwarding done by docker is only for tcp by default. Hence, our endpoints which use the host ports do not support udp.

**Comment by jdef** [comment]
we should add this as a known issue

**Comment by sttts** [comment]
This is not true, luckily. The same restriction applies as for tcp ports: they must be declared in the pod. In this case the pods must declare the port as udp. The kubeproxy test forgot to set the protocol such that the port-forwarding was only for tcp.
