### ISSUE TITLE
Kubelet-executor missing privileged flag

### ISSUE THREAD

**Issue by brandon-adams** [mesosphere/kubernetes-mesos#563]
Hi all,
I'm running Kubernetes v1.1 on Mesos 0.23, and I'm trying to launch a few privileged containers on my cluster. I have set *--allow_privileged=true* on my apiserver, but when the kubelet is downloaded and launched on my Mesos slave, it has that flag set to false. As I understand it, Mesos is supposed to start the executor on a node when a Pod is scheduled there, so I can't force the configuration by launching it myself. I appreciate the help.

**Comment by jdef** [comment]
What kubernetes branch are you building from? master? release-1.1?

**Comment by brandon-adams** [comment]
Release-1.1, which gets me the following specific versions:

    kubectl version
    Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-beta.237+be47a12477d436", GitCommit:"be47a12477d436b27b3ed1bd1056a9ac6a641658", GitTreeState:"clean"}
    Server Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-beta.237+be47a12477d436", GitCommit:"be47a12477d436b27b3ed1bd1056a9ac6a641658", GitTreeState:"clean"}

**Comment by jdef** [comment]
As an FYI we're currently focusing our efforts on (a) the master branch,
and; (b) a stable release-1.0 branch. The upstream team is hard at work on
release-1.1 so it's still somewhat in flux. Once release-1.1 is more stable
we'll cut a mesosphere/kubernetes@v1.1-v0.7 branch from it and then
cherry-pick k8s-mesos PR's from kubernetes/kubernetes@master into it.

**Comment by jdef** [comment]
Clarification: "stable release-1.0 branch" == stable
mesosphere/kubernetes@v1.0-v0.6 branch cut from
kubernetes/kubernetes@release-1.0

**Comment by ravilr** [comment]
Besides upstream kubernetes v1.1 might be missing some mesos related fixes as pointed out by @jdef, 
--allow-privileged flag (note it is hyphen not underscore in both apiserver and k8sm-scheduler) needs to be set in k8sm-scheduler service in mesos setup in addition to apiserver.

**Comment by sttts** [comment]
I double checked this: the allow-privileged on the scheduler leads to the same flag on the kubelet. As @ravilr pointed out, the apiserver needs this flags as well.

Closing this issue for the moment. @brandon-adams If you think it's still broken please reopen this ticket.
