### ISSUE TITLE
mesos/pkg/scheduler test failing

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#569]
reported here: https://github.com/kubernetes/kubernetes/issues/16075

**Comment by sttts** [comment]
Where is the connection to the 0.7.0 release?

**Comment by jdef** [comment]
i wanted this fixed for k8s 1.1

**Comment by sttts** [comment]
I wonder whether it makes sense to schedule any maintenance ticket using our releases. It's not really the right place for them IMO. I agree this ticket should be fixed and P1 is fine, but it's not really related to our progress with v0.7.0.

**Comment by jdef** [comment]
I'm open to suggestions.

**Comment by sttts** [comment]
Only alternative I see: make a Maintenance label and keep those tickets out of the milestones, but still keep prioritizing them. It's basically the same as for process issues, CI and so on.

**Comment by jdef** [comment]
OK. we already have a maintenance label.

**Comment by sttts** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/16851
