### ISSUE TITLE
Verify that k8s can scale to at least 20 nodes with k8s e2e tests

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#570]
As a user dogfooding kubernetes on mesos, I want to deploy it on clusters with a two digit number of nodes. While development is mostly done with a one digit number of nodes, testing with a magnitude higher has to be performed.

**Comment by jdef** [comment]
duplicate of https://github.com/mesosphere/kubernetes-mesos-private/issues/27
