### ISSUE TITLE
pods should be able to use both mesos-dns and kube-dns

### ISSUE THREAD

**Issue by spacejam** [mesosphere/kubernetes-mesos#581]
Users need to be able to access processes running on both K8s and the outside mesos cluster.  Pods need to be able to resolve names through both mesos-dns and kube-dns.

**Comment by karlkfi** [comment]
I've been testing this with oinker and cassandra from #537.
We should probably also verify it works with Marathon correctly.

**Comment by karlkfi** [comment]
I have verified that Oinker on K8s on DCOS can find and talk to Cassandra on the same DCOS.

Still need to verify that marathon apps can be discovered from k8s pods, but it should work.

**Comment by karlkfi** [comment]
Verified.
