### ISSUE TITLE
k8sm cluster should survive mesos master failover

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#582]
Dan should stay asleep during a Mesos master failover event because the Kubernetes-Mesos scheduler properly recovers without loss of k8s cluster objects/state.

**Comment by jdef** [comment]
There's definitely underlying mesos-go-related issues here.

**Comment by sttts** [comment]
@jdef what about this topic? We briefly talked about it on monday. Is there anything we can do or should investigate short term within the next 3 weeks?

**Comment by jdef** [comment]
mesos-go changes are likely required. we should be able to complete an
investigation. not sure that we'll be able to fully resolve within 3 weeks
given all the other work on our plate.

**Comment by jdef** [comment]
related mesos-go changes: https://github.com/mesos/mesos-go/pull/221

**Comment by jdef** [comment]
update to latest mesos-go: https://github.com/kubernetes/kubernetes/pull/21198

**Comment by jdef** [comment]
cherry-picked into v0.7.3, removing cherry-pick label
