### ISSUE TITLE
Clusters should remain healthy when ubercontainer restarts on different hosts

### ISSUE THREAD

**Issue by spacejam** [mesosphere/kubernetes-mesos#583]
Operators should stay asleep when trivial failures occur.  Sometimes the ubercontainer host will have issues, and will be relocated.  The invariants defined in https://github.com/mesosphere/kubernetes-mesos/issues/576 need to hold across restarts.

**Comment by s-urbaniak** [comment]
Just tested the behaviour on a 3-node DCOS-cluster installed via CCM.

Executed:
```
$ dcos config prepend package.sources https://github.com/mesosphere/multiverse/archive/version-1.x.zip
$ dcos package update --validate
$ dcos package install etcd
$ cat >/tmp/options.json <<EOF
{
  "kubernetes": {
    "etcd-mesos-framework-name": "etcd"
  }
}
EOF
$ dcos package install --options=/tmp/options.json kubernetes
```
Find out which machine runs the `kubernetes` ubercontainer in the DCOS UI, ssh into the node:
```
$ dcos node ssh --master-proxy --slave=xxxxxx-yyyy-4cab-b1fb-3c92a11cdd2d-S1
$ sudo systemctl stop dcos-mesos-slave.service
```
Observed behavior:
1. Node is marked as unhealthy in DCOS
2. Kubernetes is marked as unhealthy
3. Kubernetes is being restarted on a different node by Marathon
4. The Kubernetes Ubercontainer restarts with a correctly retained state:
5. The Kubernetes UI was incidently also on the simulated failed node and was correctly restarted on a  different one.

**Comment by jdef** [comment]
:+1:

**Comment by s-urbaniak** [comment]
@jdef Still testing kube-dns behaviour after the failover

**Comment by s-urbaniak** [comment]
Observed behavior on the `kube-dns` instance which kept running on a healthy node:
1. Created a busybox pod
```
$ cat >busybox.yaml <<EOF
apiVersion: v1
kind: Pod
metadata:
 name: busybox
 namespace: default
spec:
 containers:
 - image: busybox
   resources:
     limits:
       cpu: 100m
       memory: 64Mi
   command:
   - sleep
   - "3600"
   imagePullPolicy: IfNotPresent
   name: busybox
 restartPolicy: Always
EOF
$ dcos kubectl create -f busybox.yaml
$ ssh dcos node ssh --master-proxy --slave=aaaaaa-bbbb-4cab-b1fb-3c92a11cdd2d-S2
$ docker exec -it busybox-container-uid /bin/sh
/ # wget http://kube-ui.kube-system.svc.cluster.local
Connecting to kube-ui.kube-system.svc.cluster.local (10.10.10.245:80)
index.html           100% |***********************************************************************************************************************************************************|  2582   0:00:00 ETA

```
2. Successfully `wget`ed the kube-ui via kube-dns

**Comment by spacejam** [comment]
awesome!

**Comment by sttts** [comment]
Next step:
- create a service:
```
apiVersion: v1
kind: Service
metadata:
 name: nginx
 labels:
   name: nginx
spec:
 ports:
 - port: 80
 selector:
   name: nginx
```
- check from the busybox that nginx.default.svc.cluster.local is reachable.

**Comment by s-urbaniak** [comment]
Tested successfully the above service:

```
$ dcos kubectl create -f service.yaml
$ ssh dcos node ssh --master-proxy --slave=aaaaaa-bbbb-4cab-b1fb-3c92a11cdd2d-S2
$ docker exec -it busybox-container-uid /bin/sh
/ # nslookup nginx.default.svc.cluster.local
Server:    10.10.10.10
Address 1: 10.10.10.10 ip-10-10-10-10.us-west-2.compute.internal

Name:      nginx.default.svc.cluster.local
Address 1: 10.10.10.7 ip-10-10-10-7.us-west-2.compute.internal
```

The `nginx.default.svc.cluster.local` DNS is successfully resolved.

**Comment by s-urbaniak** [comment]
Hey, this looks good ! :-)

**Comment by sttts** [comment]
Anything which should test in addition?

**Comment by karlkfi** [comment]
If you're feeling ambitious, test that oinker-go works while both kubernetes ubercontainer is down and cassandra has lost a node. That would be a pretty awesome demo.
