### ISSUE TITLE
The reason not use one ip per pod in k8sm?

### ISSUE THREAD

**Issue by zhengguoyong** [mesosphere/kubernetes-mesos#596]
i know k8sm use dirffent network with kubernetes,  while kubernetes use one ip per pod, k8sm use   "normal" Docker IPv4, host-private networking.  i just wander why we also not use one ip per pod in k8sm project? 
thanks.
@jdef @sttts

**Comment by sttts** [comment]
@zhengguoyong k8sm has two modes of operation: it works perfectly fine with pod ips if you use the upstream endpoint controller. In addition it includes a special endpoint controller which works with host ips (as you describe).

The reason to default to the second is that this is how most Mesos cluster are setup nowadays. There is no overlay network normally and Mesos does port resource management therefore.

**Comment by zhengguoyong** [comment]
thanks  very much for you reply.
@sttts

**Comment by sttts** [comment]
@zhengguoyong I would close the issue. If you notice any problem with the  ip-per-pod setup, feel free to re-open it.
