### ISSUE TITLE
change versioning scheme: only use k8sm version

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#597]
our versioning scheme is confusing for just about everyone that looks at it: it includes both the kubernetes-mesos version AND the kubernetes version. it also puts the k8s version first, which leads some people to believe that we've put out a GA release for this project. such is not the case.

this project should switch to using ONLY the k8sm version (at the time of this writing it is 0.6.6).

**Comment by sttts** [comment]
The 0.6.7 release is nearly out of the door. We can approach this with the next release.

**Comment by karlkfi** [comment]
xref #606
