### ISSUE TITLE
WIP/TEMPLATE: release

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#599]
Release steps
======

Tag
----

In  http://github.com/mesosphere/kubernetes

- [ ] create a release branch with all necessary cherry-picks, e.g. `release-v0.6-v1.0`

  The release branch is without the 3rd digits to allow further minor version updates of the branch names without switching names all the time. Moreover, we should try to keep a linear version history between releases with minor version updates.

- [ ] tag release branch with e.g. `v0.6.6-v1.0.6`

In  http://github.com/mesosphere/kubernetes-mesos

- [ ] tag master branch of with e.g. `v0.6.6`

Build
------

In https://github.com/mesosphere/kubernetes-mesos/ images/docs:

- [ ] `make clean`
- [ ] build docker image: `make image`
- [ ] push docker image: `make push`

In https://github.com/mesosphere/multiverse:

- [ ] create release branch, e.g. `kubernetes-v0.6.6-v1.0.6`
- [ ] update version in package.json, 
- [ ] update config.json (docker image version)
- [ ] create PR against `version-1.x`

In https://github.com/mesosphere/mesosphere-docs:

- [ ] create PR in  w/ updated build #'s, link it to the multiverse PR and mark it WIP until multiverse PR merges

Wait for Multiverse LGTM
---------------------

In http://github.com/mesosphere/mesosphere-docs:

- [ ] merge multiverse

Once multiverse PR merges
---------------------

- [ ] merge the http://github.com/mesosphere/mesosphere-docs changes and wait for
staging rebuild to happen (usually within 1h); 
- [ ] verify that your version bump changes are good (manually walk through the steps in the entire doc)
- [ ] file a ticket in JIRA to request a merge from staging to prod (link to the GH PR)
  - project: DOCS
  - owner: joel hamill
- [ ] run and verify functionality of the k8s guestbook as a sanity check

Useful command to let latest mesosphere pull requests (e3188f6ee7007000c5daf525c8cc32b4c5bf4ba8 is the first common commit between the release branch and master):
```
git log --oneline --first-parent e3188f6ee7007000c5daf525c8cc32b4c5bf4ba8..upstream/master | grep -i mesos | sed 's,^\([^ ]*\).*#\([0-9]*\) from \(.*\)$,- [ ] http://github.com/kubernetes/kubernetes/pull/\2 \1 \3,' | sed '1!G;h;$!d'
```

**Comment by jdef** [comment]
you may not get an LGTM from the multiverse maintainer w/o first running `scripts/build.sh` because they'll want to test things out on their end.

**Comment by karlkfi** [comment]
release branch `0.6.6_k8s-1.0.6` maybe?

**Comment by sttts** [comment]
This breaks the merge every time something is merged. This process is broken. That's why I keep the scripts/build.sh call out of the PR.

**Comment by sttts** [comment]
@karlkfi The release branch should not have fully qualified version because you cannot increase those easily (i.e. because k8s updated to v1.0.7) while we are working on it.

**Comment by karlkfi** [comment]
@sttts I'm ok with that. You just had it in your first bullet point.

**Comment by sttts** [comment]
@karlkfi added some text about that

**Comment by karlkfi** [comment]
So you're thinking of re-using the `v0.6-v1.0` branch between point releases?

**Comment by sttts** [comment]
yes. And rebasing it with all the cherry-picks onto new upstream release tags. The tags for our releases of course have full digits.

**Comment by karlkfi** [comment]
rebasing after cherry-picks sounds like it would break in horrible ways....

**Comment by sttts** [comment]
usually not. We rebase only from v1.0.6->v1.0.(6+n). Never broke until now.

**Comment by sttts** [comment]
And if it breaks, so be it. You can fix it.

**Comment by karlkfi** [comment]
Need to make sure Release Notes are added to https://github.com/mesosphere/kubernetes-mesos/releases/ for each release.

**Comment by sttts** [comment]
@karlkfi please add it above if it is missing.

**Comment by sttts** [comment]
@karlkfi your link is wrong. Releases are here: https://github.com/mesosphere/kubernetes/releases

**Comment by sttts** [comment]
@aaron @jdef Can you add a link to the line `- [ ] file a DOCS ticket in JIRA to request a merge from staging to prod (link to the GH PR)`? Where should it be created and who should be assigned?

**Comment by jdef** [comment]
done

**Comment by s-urbaniak** [comment]
The release template is now being maintained as a GH-wiki page: https://github.com/mesosphere/kubernetes-mesos/wiki/Release-Issue-Template
