### ISSUE TITLE
Release v1.0.6-v0.6.7 with DCOS subcommand

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#600]
Release steps
======

Tag
----

- [x] tag release branch (e.g. v0.6-v1.0): https://github.com/mesosphere/kubernetes/releases/tag/v1.0.6-v0.6.7
- [x] tag master branch: https://github.com/mesosphere/kubernetes-mesos/releases/tag/v0.6.7

Build
------

In https://github.com/mesosphere/kubernetes-mesos/ images/docs:

- [x] `make clean`
- [x] build docker image: `make image`
- [x] push docker image: `make push`

In https://github.com/mesosphere/multiverse

- [x] create release branch: https://github.com/mesosphere/multiverse/tree/k8sm-v1.0.6-v0.6.7

- [x] update version in package.json, 
- [x] update config.json (docker image version)
- [x] create PR: https://github.com/mesosphere/multiverse/pull/28

Wait for Multiverse LGTM
---------------------

In http://github.com/mesosphere/mesosphere-docs:

- [x] create PR w/ updated build #'s, link it to
the multiverse PR and mark it WIP until multiverse PR merges: https://github.com/mesosphere/mesosphere-docs/pull/216
- [x] rebuild index.json using `scripts/build.sh` 
- [x] and merge

Once multiverse PR merges
---------------------

- [x] merge the http://github.com/mesosphere/mesosphere-docs changes and wait for
staging rebuild to happen (usually within 1h); 
- [x] verify that your version bump changes are good (manually walk through the steps in the entire doc)
- [x] file a DOCS ticket in JIRA to request a merge from staging to prod (link to the GH PR)
- [x] run and verify functionality of the k8s guestbook as a sanity check

**Comment by sttts** [comment]
Smoke tested the package successfully.

**Comment by s-urbaniak** [comment]
LGTM
Performed CCM smoke test:
1. installed kubernetes
2. installed guestbook example
3. verified all k8s services are running
