### ISSUE TITLE
Is the scheduler algorithms same in k8sm and k8s project?

### ISSUE THREAD

**Issue by zhengguoyong** [mesosphere/kubernetes-mesos#602]
In k8s project , there are several scheduler algorithms. so when we select the fit node for pod, 
we can take cpu、memroy、HostPort、NodeName、nodeSelector into account.
(https://github.com/kubernetes/kubernetes/blob/master/docs/devel/scheduler_algorithm.md),
in k8sm, we use mesos master to select the node for pod, Does k8sm aslo have such algorithms?
thanks.
@sttts

**Comment by sttts** [comment]
The k8sm Scheduler is different to the upstream one. But it also supports cpu, memory, HostPort, NodeName and NodeSelector.

**Comment by zhengguoyong** [comment]
Can you help show me the code? 
If i want to add another scheduler algorithms,  
How should i do ?
thanks very much.

**Comment by sttts** [comment]
The scheduler is not pluggable right now. You have to change the code in contrib/mesos/pkg/scheduler.

**Comment by zhengguoyong** [comment]
thanks, 
when pod created in k8sm scheduler, it will create a mesos task,
and then mesos master will schedule it and select a fit node for the pod/task,
so in my mind, mesos master will do the schedule,  the k8sm scheduler(contrib/mesos/pkg/scheduler) just pass the schedule result to mesos slave.  
am i right?  
i am sorry i not  so familar in this place.

**Comment by sttts** [comment]
It's a little different. The master only offers resources. All the scheduling, i.e. the decision where to place the pod is done by the k8sm scheduler. At the moment we use a "first come first serve" algorithm though. This essentially means that the first fitting offer is used.

**Comment by zhengguoyong** [comment]
After your answer, it is more clear to me now.  thanks.
Just another doubt:
What is the stragety mesos mater offer resources based?  Mesos master will take  cpu, memory, HostPort, NodeName and NodeSelector into account?  Or it just care about cpu、memory?

**Comment by sttts** [comment]
The master does not know about the node name and node selector. For background about fair scheduling, i.e. which framework will get which offers, read Ben Hindman's paper: https://www.cs.berkeley.edu/~alig/papers/drf.pdf

**Comment by zhengguoyong** [comment]
thanks very much.
@sttts
