### ISSUE TITLE
Better communicate known issues.

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#604]
i.e. Which MVP items are not complete, that users might stumble on.

We already have a known issues doc. It is incomplete.

xref https://github.com/kubernetes/kubernetes/pull/17589

**Comment by jdef** [comment]
exec, log, proxy kubectl subcommands don't work as expected; probably others. should review kubectl

**Comment by sttts** [comment]
- executor upgrade after config change
- maybe scheduling onto a public slave, depending on the progress with the roles patch

**Comment by jdef** [comment]
@karlkfi anything you'd like to see listed here as a result of the kubecon dogfooding?

**Comment by karlkfi** [comment]
Scaling is borked due to pod scheduling, but maybe that's more of a bug

**Comment by jdef** [comment]
xref #624

**Comment by karlkfi** [comment]
The following section is on [[https://docs.mesosphere.com/services/kubernetes/#subcommand]] but should instead be on [[https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/docs/issues.md]]. Then the dcos docs can just link to the known issues.

```
Known Issues
In this release the following kubectl commands are not supported:
- exec
- logs
- port-forward
- proxy
- version
```

**Comment by jdef** [comment]
don't support pod updates

**Comment by jdef** [comment]
port mapping label key `k8s.mesosphere.io/portMapping` affects port allocation (and we should deprecate this as a label, convert it to an annotation)

**Comment by jdef** [comment]
testing slack integration

**Comment by jdef** [comment]
address review feedback, awaiting lgtm
