### ISSUE TITLE
Prepare release v0.7.0-v1.1.x

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#606]
Release steps
======

Tag
----

In  http://github.com/mesosphere/kubernetes

- [x] create a release branch with all necessary cherry-picks: https://github.com/mesosphere/kubernetes/tree/v0.7-v1.1
- [x] tag release branch:
https://github.com/mesosphere/kubernetes/releases/tag/v0.7.0-v1.1.1

In  http://github.com/mesosphere/kubernetes-mesos

- [x] tag master branch:
https://github.com/mesosphere/kubernetes-mesos/releases/tag/v0.7.0

Build
------

In https://github.com/mesosphere/kubernetes-mesos/ images/docs:

- [x] `make clean`
- [x] build docker image: `make image`
- [x] push docker image: `make push`

In https://github.com/mesosphere/multiverse:

- [x] create release branch:
https://github.com/mesosphere/multiverse/tree/v0.7-v1.1

- [x] update version in package.json, 
- [x] update config.json (docker image version)
- [x] create PR against `version-1.x`
https://github.com/mesosphere/multiverse/pull/46

Wait for Multiverse LGTM
---------------------

In http://github.com/mesosphere/mesosphere-docs:

- [x] create PR in  w/ updated build #'s, link it to the multiverse PR and mark it WIP until multiverse PR merges https://github.com/mesosphere/mesosphere-docs/pull/278
- [x] merge

Once multiverse PR merges
---------------------

- [x] merge the http://github.com/mesosphere/mesosphere-docs changes (https://github.com/mesosphere/mesosphere-docs/pull/278) and wait for
staging rebuild to happen (usually within 1h); 
- [x] verify that your version bump changes are good (manually walk through the steps in the entire doc)
- [x] file a ticket in JIRA to request a merge from staging to prod (link to the GH PR)
  - project: DOCS
  - owner: joel hamill
- [x] run and verify functionality of the k8s guestbook as a sanity check

**Comment by s-urbaniak** [comment]
Smoke-tested succesfully on a 3-node cluster:

1. Followed https://github.com/mesosphere/mesosphere-docs/blob/kubernetes-v0.7.0-v1.1.1/services/kubernetes.md for installation of etcd and kubernetes
Note: used a modified local `dcos.toml` pointing to a locally checked out multiverse directory pointing at https://github.com/mesosphere/multiverse/tree/v0.7-v1.1

2. Executed quick install of the guestbook installation as described in https://github.com/kubernetes/kubernetes/tree/master/examples/guestbook
3. Uninstalled all pods/rc/services, kubernetes and etcd

**Comment by s-urbaniak** [comment]
The linked pictures at https://github.com/mesosphere/mesosphere-docs/blob/kubernetes-v0.7.0-v1.1.1/services/kubernetes.md seem broken, is that correct?

**Comment by jdef** [comment]
Seems like we use special non-markdown markup for images. When rendered on
the docs site it should be working. check the staging env

**Comment by karlkfi** [comment]
are there dcos docs changes for this release? what's the pr? is it merged?

**Comment by sttts** [comment]
Your new DCOS getting started guides might be worth linking maybe in the mesosphere-docs PR

**Comment by karlkfi** [comment]
I see https://github.com/mesosphere/mesosphere-docs/pull/278, it just was on a different bullet point than i expected.

**Comment by sttts** [comment]
Maybe also take a look in the blog post and check whether the links are correct with recent conformance claims and your changes. But communicate with Suzanne if you change something. she is editing.

**Comment by sttts** [comment]
Also it seems that PR must be rebased.

**Comment by karlkfi** [comment]
passive voice is for blogs! are you gonna rebase that or should i?

**Comment by sttts** [comment]
go ahead. am busy with git renames.

**Comment by karlkfi** [comment]
done (rebasing the docs)

**Comment by karlkfi** [comment]
Multiverse is updated
Docs are updated
Release notes are updated

**Comment by cmluciano** [comment]
Are the release notes now stored under a different repo? I can't seem to find them for 0.7.0

**Comment by jdef** [comment]
release notes are here: https://github.com/mesosphere/kubernetes/releases/tag/v0.7.0-v1.1.1
