### ISSUE TITLE
port mapping issue in k8sm scheduler

### ISSUE THREAD

**Issue by ravilr** [mesosphere/kubernetes-mesos#614]
@jdef 
when there are multiple discontinuous port ranges in the mesos offer, the wildcard hostport mapping code doesn't always assigns a offer port to all the hostPort=0 in pod spec.

At https://github.com/kubernetes/kubernetes/blob/17defc7383914c1f52d30ab4a46e0992cbfc2bae/contrib/mesos/pkg/scheduler/podtask/port_mapping.go#L110, it is updating the copy of wildports array and at https://github.com/kubernetes/kubernetes/blob/17defc7383914c1f52d30ab4a46e0992cbfc2bae/contrib/mesos/pkg/scheduler/podtask/port_mapping.go#L103, the check fails in next iteration of offer port range always.

for example, when the offer has following port resource ranges (31005,31005), (31011,32000), and the pod spec has 2 container ports (and hostPort=0), and wildportmapping is on (by default),  only the first port gets a offer port in the mapping.

**Comment by sttts** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/16992
