### ISSUE TITLE
Conformance tests of release branch are unstable

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#615]
The conformance tests in Teamcity of the v0.7-v1.0 branch are unstable, compare e.g. https://teamcity.mesosphere.io/viewLog.html?buildId=69542&

The set of failing tests is different every time. The best case I have seen was only the guestbook failing.

Note: all of them include the " Kubernetes e2e suite.Kubectl client Guestbook application should create and stop a working application [Conformance]" test.

**Comment by sttts** [comment]
Rebased to latest upstream/release-1.1 branch. Let's see.

**Comment by jdef** [comment]
It looks like k8s v1.1.1 was put into pre-release 4h ago: https://github.com/kubernetes/kubernetes/releases/tag/v1.1.1

**Comment by sttts** [comment]
Rebased already. Tests are running. The release-1.1 branch from earlier today led to >20 broken tests. Let's hope.

**Comment by sttts** [comment]
Running tests: https://teamcity.mesosphere.io/viewLog.html?buildId=71132&buildTypeId=Oss_KubernetesMesos_ConformanceTests&tab=buildLog

**Comment by sttts** [comment]
Two failed tests: https://teamcity.mesosphere.io/viewLog.html?buildId=71132&buildTypeId=Oss_KubernetesMesos_ConformanceTests&tab=buildResultsDiv

The artifacts includes all logs.
