### ISSUE TITLE
Add DCOS getting started guide

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#617]
The should not only be a getting started guide for pure Mesos, but one for DCOS as well.

We can copy most of https://docs.mesosphere.com/services/kubernetes/

**Comment by karlkfi** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/17198

**Comment by karlkfi** [comment]
One further step for this issue is to get the DCOS guide linked on http://kubernetes.io/gettingstarted/
I'm not sure how to do that. So I'm emailing david to ask.

**Comment by karlkfi** [comment]
We also need to add it to https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/README.md

**Comment by karlkfi** [comment]
David says:
> Just send a PR to update
https://github.com/kubernetes/kubernetes/blob/gh-pages/gettingstarted.md
(note that this is in a branch called "gh-pages" not master)

**Comment by karlkfi** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/17689

**Comment by karlkfi** [comment]
website update PR: https://github.com/kubernetes/kubernetes/pull/17695

**Comment by jdef** [comment]
on target to land today. k8s website needs to be regenerated, need to reach out directly to google (davidopp)

**Comment by karlkfi** [comment]
Guide is merged. Closing. All further kubernetes.io cherry-picks will be tracked by #449
