### ISSUE TITLE
SMOKE TEST FAILING: scheduler will generate invalid pod specs when auto-filling resource limit values

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#619]
someone recently updated the k8s guestbook examples to use "requested" resources. the example specs don't provide resource limits.

https://github.com/kubernetes/kubernetes/pull/14256

turns out that there's a validation rule in k8s that says pod spec resource limits >= pod spec resource requests.

our scheduler sees pod specs without resource limits and auto-fills values using the configured defaults. which in this case are less than the requested resources. the pod specs are serialized and sent out via LaunchTask. they're received by the executor, which immediately logs a warning and then panics because the pod spec fails to validate.

from executor.log:
```
W1110 01:15:56.443637     187 config.go:329] Pod[1] (frontend-k3hox.default) from api failed validation, ignoring: spec.containers[0].resources.resources.limits[memory]: invalid value '64Mi', Details: limit cannot be smaller than request
E1110 01:15:56.443711     187 util.go:82] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
W1110 01:16:02.530776     187 config.go:329] Pod[1] (redis-master-a61ip.default) from api failed validation, ignoring: spec.containers[0].resources.resources.limits[memory]: invalid value '64Mi', Details: limit cannot be smaller than request
E1110 01:16:02.530891     187 util.go:82] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
W1110 01:16:09.079135     187 config.go:329] Pod[1] (frontend-h0n6n.default) from api failed validation, ignoring: spec.containers[0].resources.resources.limits[memory]: invalid value '64Mi', Details: limit cannot be smaller than request
E1110 01:16:09.079208     187 util.go:82] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```

**Comment by jdef** [comment]
we'll probably want to backport a fix to the v0.6x branch for this too

**Comment by sttts** [comment]
Afaik pod spec resource requests weren't there yet when it was implemented for 1.0.

**Comment by sttts** [comment]
Request support implemented in https://github.com/kubernetes/kubernetes/pull/17054

**Comment by jdef** [comment]
why was this moved to the backlog>?

**Comment by sttts** [comment]
Moved #17054 to ready-to-merge. Waffle did some magic with this one.
