### ISSUE TITLE
k8sm is slow to create a pod

### ISSUE THREAD

**Issue by huang195** [mesosphere/kubernetes-mesos#624]
i was able to create a pod in k8s in less than 3 seconds, even when I put hundreds of pods on the same host. However, in k8sm, the time to create a pod has really high variance. It can be as small as a few seconds to tens of seconds, and sometimes a few minutes. 

These experiments were done on the same hardware and same number of nodes. It's either a problem with k8sm or mesos. Is there a way to narrow down who the culprit is?

**Comment by jdef** [comment]
Thanks for reporting this. There's a couple of factors that influence when pods are scheduled by k8s-mesos:
- availability of a resource offer that "fits" the pod (mesos master/slave);
- scheduler *backoff* (to avoid busy-looping) during pod scheduling (k8s-mesos scheduler)

We've tried to mitigate the second item by cancelling the backoff period if an offer arrives that fits a pod-in-waiting. However, there's nothing that the k8s-mesos scheduler can do if there are no resources available in the cluster.

That said, the current scheduling algorithm is somewhat naive: it makes no attempts to pack multiple pods into a single offer. This means that each pod launch requires an independent offer. In a small cluster resource offers do not arrive very frequently. In a large cluster with a decent amount of free resources the arrival rate of offers is expected to be much higher.

The the slave on each host announces offers to mesos periodically. In a single node cluster only a single slave process is advertising resources to the master. The master will pass those along to the k8s-mesos scheduler, at some interval and level of 'fairness' determined by mesos. That k8s-mesos scheduler will pair each resource offer with a pod that needs to be placed in the cluster. Once paired, a task is launched to instantiate the pod. The used resources will be marked as consumed, the remaining resources are "returned" to the cluster and the k8s-mesos scheduler will wait for the next resource offer from the master .. and the cycle repeats itself. This likely limits the scheduling throughput you'll see in a single-node cluster.

We're currently running some benchmarks on the scheduling algorithm to establish some baselines. We are definitely thinking about ways to increase scheduling throughput (including scheduling multiple pods per offer).

/cc @spacejam @sttts

**Comment by huang195** [comment]
@jdef thanks for that detailed explanation of how k8sm scheduler works. I'm starting to look into this part of the code, so this definitely helps when I dive more into it.

Just a bit more details about my experiment: I'm using 1 master and 2 slave nodes, each has 4 cores and 8 GB of RAM. The pods are created sequentially, i.e., we don't create the next pod until the previous pod is reported to be in a running state. The pods we're creating are dummy pods with one container: pause, that k8s uses as the infrastructure container. 

As this setup should put minimal amount of stress to the infrastructure, I was hoping we would get similar results to our k8s experiments, i.e., pods will be created within 2 or 3 seconds with almost no variance, up to a few hundred pods per node. What we saw on k8sm had us scratching our head - really large variance in pod creation time from a few seconds to a few minutes or more. 

A few follow up questions:
1. You mentioned that in a small cluster, resource offers do not arrive very frequently. Is that something that can be adjusted as a runtime configuration? And if so, is that a mesos or kubernetes configuration change?
2. Regarding scheduler backoff, can be elaborate a bit more on that? Do you mean k8sm periodically polls and would use a backoff algorithm to avoid too many polls if no resource offers are available? Why isn't a watch being used so it's event-based to avoid polling?
3. General question: I found debugging and profiling these types of frameworks extremely challenging as there are layers on top of layers of complex code, i.e., k8sm, k8s, mesos, docker, kernel. Do you have some suggestions/tools that you can recommend when someone wants to peek into things under the cover?

**Comment by jdef** [comment]
A1. **Runtime configuration**
- mesos: `--offer_timeout` : Duration of time before an offer is rescinded from a framework.
This helps fairness when running frameworks that hold on to offers, or frameworks that accidentally drop offers. ([via](http://mesos.apache.org/documentation/latest/configuration/))
- k8s-mesos `--scheduler-config` : An ini-style configuration file with low-level scheduler settings. See `offer-ttl`, `initial-pod-backoff`, and `max-pod-backoff`. ([via](https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/pkg/scheduler/config/config.go))

What's not configurable, but perhaps should be, are the mesos "filters" that we include when declining offers that we can't match to pods within the config'd `offer-ttl` (see https://github.com/apache/mesos/blob/0.25.0/include/mesos/mesos.proto#L1165). I think we hardcode the `refuse_seconds` value to 5s. We should probably expose that via the scheduler fine tuning mechanism.

A2. **Scheduler backoff.**
If no matching resource offer can be found for a pod then that pod is put into a backoff queue. Once the backoff period expires the pod is re-added to the scheduling queue. The backoff period may be truncated by the arrival of an offer with matching resources. This is an event-based design and there is no polling.

A3. **Debugging**
Yes, debugging can be challenging. The best experience I've had operationally is when all of the relevant logs are collected into a single tool (Splunk, or an ELK stack) an a manner such it's trivial to search for something like a task-id or pod-id during cluster debugging sessions. The k8sm-scheduler also offers some /debug API endpoints that may be useful:
- on-demand explicit reconciliation: /debug/actions/requestExplicit
- on-demand implicit reconciliation: /debug/actions/requestImplicit
- kamikaze (terminate all "empty" executors that aren't running pods): /debug/actions/kamikaze
- pods to be scheduled: /debug/scheduler/podqueue
- pod registry changes waiting to be processed: /debug/scheduler/podstore
- scheduler metrics are available at /metrics

You can also enable /debug/pprof profiling endpoints for the scheduler and kubelet-executor via the scheduler's `--profiling` flag. More verbose logs can also be useful (via scheduler: `--v`, and `--executor-logv`). Useful when combined with `go tool pprof`.

**Comment by huang195** [comment]
@jdef Thanks for the awesome answers! Will give them a try and see if anything can be improved.

**Comment by jdef** [comment]
xref #604

**Comment by luckyfengyong** [comment]
Just some update regarding to @jdef 's comment of "However, there's nothing that the k8s-mesos scheduler can do if there are no resources available in the cluster.". Mesos-1607 (https://issues.apache.org/jira/browse/MESOS-1607) which we are working on currently is expected to resolve it. After Mesos-1607 phase2 , framework could cache/hold offer and don't have to return it back to Mesos even though it does not use it currently. Therefore, as long as system has available resource, k8s scheduler could schedule pending pods immediately.

**Comment by jdef** [comment]
possible root cause of slowness #636

**Comment by jdef** [comment]
is any further action needed here?

**Comment by huang195** [comment]
Closing this as I can't reproduce this problem anymore
