### ISSUE TITLE
k8s/dcos package should default to etcd-mesos instead of internal etcd

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#627]
CM.3 is GA which means that the mesos-dns changes we need for {etcd,k8s}-mesos integration are in place across the board.

the current default setting for k8s-dcos is to use an internal etcd server. we should change the default setting to point to the default etcd-mesos framework name that's created upon `dcos package install etcd`.

**Comment by sttts** [comment]
I don't like this as long as we don't have dependencies. I would prefer a very explicit message during installation: "NO PERSISTENCE" bla bla. "Do you really want that or do you want to install etcd-mesos?"

**Comment by jdef** [comment]
Until we get a smarter package manager we can't offer prompts like that. :(

**Comment by sttts** [comment]
Maybe not interactive, just the warning and the description how to install etcd-mesos

**Comment by jdef** [comment]
TODO:
* create a known issue that docs the awfulness of the default, and also how to use etcd-mesos
* BLOCKED on better support for package dependencies for DCOS (v0.8)
  - file another GH ticket to track this

**Comment by sttts** [comment]
Added a warning to the install message of our package: https://github.com/mesosphere/multiverse/pull/58

**Comment by sttts** [comment]
Add documentation of the situation in the issues.md: https://github.com/kubernetes/kubernetes/pull/18355

**Comment by sttts** [comment]
Added issue to track dependency topic: https://github.com/mesosphere/kubernetes-mesos/issues/676
