### ISSUE TITLE
Upstream CI shell scripts

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#633]
As a developer, I want to be able to reproduce CI failures locally by running the same build/test code in the same dockerized environment.

Make sure they can be run locally on Mac & Linux as well as on TeamCity.

**Comment by jdef** [comment]
it sounds like this would greatly simplify running our build/tests on Jenkins as well, correct?

**Comment by karlkfi** [comment]
Likely. This should cut our builds all down to 2 steps:
1. build the test container image
2. run the desired build/test

**Comment by karlkfi** [comment]
And if at some point in the future we version our test container image the same way k8s is (by build-<sha>) then we can cut them all down to 1 step.

**Comment by karlkfi** [comment]
A bit more for interruptibility: https://github.com/kubernetes/kubernetes/pull/17748

**Comment by sttts** [comment]
I guess this one is done.
