### ISSUE TITLE
master conformance is red

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#652]
3 red, new tests.

**Comment by sttts** [comment]
/xref https://github.com/mesosphere/kubernetes-mesos/issues/654

**Comment by karlkfi** [comment]
In addition to the Downward API tests failing on master (#654) there are a couple other tests failing for us:

```
Kubernetes e2e suite.Events should be sent by kubelets and the scheduler about pods scheduling and running [Conformance] 
Kubernetes e2e suite.SchedulerPredicates validates resource limits of pods that are allowed to run [Conformance] 
```

**Comment by s-urbaniak** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/669 is related and very probably by my roles patch.

**Comment by s-urbaniak** [comment]
As analyzed:

1. https://github.com/kubernetes/kubernetes/blob/d6134e5/contrib/mesos/pkg/executor/executor.go#L1023: The executor iterates over all resources from the slave info, only taking into account the last available resource, this should be a sum in a roles based world.
2. https://github.com/kubernetes/kubernetes/blob/d6134e5/test/e2e/scheduler_predicates.go#L291: This e2e test assumes that the sum of resources is allocatable by a vanilla pod which may not hold in a role based mesos world.

**Comment by s-urbaniak** [comment]
Additionally kube-ui switched from v2 to v3.

**Comment by sttts** [comment]
Discussion about the failing scheduler_predicate test: https://github.com/kubernetes/kubernetes/issues/18211#issuecomment-162511179

**Comment by s-urbaniak** [comment]
We have the following tests still red tracked in https://github.com/mesosphere/kubernetes-mesos/issues/654:
```
[Fail] Downward API volume [It] should update annotations on modification
[Fail] Events [It] should be sent by kubelets and the scheduler about pods
[Fail] Downward API volume [It] should update labels on modification [Conformance] 
```

**Comment by jdef** [comment]
- #678 is tracking scheduler predicate failures
- #680 fixed events

closing out since the related issues are being tracked by other (linked) tickets
