### ISSUE TITLE
add known issue for liveness probe

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#658]
liveness probe fix was punted to v0.7.1 so we need to document the problem in issues.md

**Comment by sttts** [comment]
I wouldn't document anything we don't understand. This is nothing for v0.7.0.

**Comment by jdef** [comment]
we know that we've experienced this problem on DCOS/k8sm

**Comment by jdef** [comment]
I'm happy to push this to v0.7.1 - we need to document this if there's problems

**Comment by sttts** [comment]
I don't see this as a blocker for v0.7.0. v0.7.1 is fine.

**Comment by sttts** [comment]
:+1:

**Comment by sttts** [comment]
Closing this until we have a proof that this problem actually exists. We saw it working perfectly fine in DCOS.
