### ISSUE TITLE
Backport e2e tag/harness changes to release-1.1

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#659]
Changes made to master fixed the conformance tests to skip `[Skipped]` tests: https://github.com/kubernetes/kubernetes/pull/17180

Some of these changes were back-ported to release-1.1: https://github.com/kubernetes/kubernetes/pull/17750 

But going forward, the conformance tests on release-1.1 will be used to validate conformance: https://github.com/kubernetes/kubernetes/issues/17536

So several of these and other changes need to be backported to allow the release-1.1 conformance tests to pass against master with the Mesos:

- Skip `[Skipped]` tests during conformance testing
- Remove "Suite" from e2e tag names & test harness scripts (e.g. e2e.sh)
- cluster/hack test harness changes
- Mesos test harnesses in contrib/mesos/ci

**Comment by karlkfi** [comment]
xref: #658

**Comment by jdef** [comment]
xref #650

**Comment by karlkfi** [comment]
upstream release-1.1 backport PR: https://github.com/kubernetes/kubernetes/pull/18686

**Comment by karlkfi** [comment]
PR complete, verified in CI, ready for review. Pinged the goog-testing group to get eyes.

**Comment by sttts** [comment]
Is this fixed?

**Comment by jdef** [comment]
I'd say yes since 18686 landed upstream

**Comment by jdef** [comment]
no need to cherry-pick these, we got them in the rebase
