### ISSUE TITLE
dcos makefile should include git username in -dev images

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#663]
AS a K8sm Dev I WANT to generate `-dev` images that are "trackable" per user, so that I can:
- delete images which I know that I am no longer using
- generate new images without fear of overwriting someone else's dev image

suggested image tag (vs the above):
- v0.7.0-v1.1.1-dev-jdef-alpha

which has the form:
- v0.7.0-v1.1.1-dev-{github-username}-alpha

Implement in https://github.com/mesosphere/kubernetes-mesos/pull/714

**Comment by sttts** [comment]
Makes sense.

**Comment by sttts** [comment]
Done on sttts-branch.

**Comment by jdef** [comment]
is there a PR for this?

**Comment by sttts** [comment]
Add a link in the description.

**Comment by jdef** [comment]
fixed by #714, which was just merged
