### ISSUE TITLE
Get rid of tools.etcdClient in the scheduler

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#667]
Upstream issue: https://github.com/kubernetes/kubernetes/issues/18153

Two violators:
- [x] framework-id storage #662 
  - option A: keep this in etcd, migrate to approved storage interface
  - option B: store this in ZK
- [x] scheduler election (HA) -- k8s was supposed to expose other interfaces for this. not sure if they've landed yet
  - option A: migrate to std k8s election/HA api (not sure this landed)
  - option B: migrate to approved storage interface
  - option C: migrate to ZK
  - option D: gut this functionality from the scheduler

**Comment by sttts** [comment]
Moved to P0 for discussion how to proceed here.

**Comment by jdef** [comment]
xref #662

**Comment by sttts** [comment]
Which options do we implement?

**Comment by s-urbaniak** [comment]
I suggest to move this issue at least to v0.8 in w/ respect to the initial plan to include roles support in 0.7.1 only. This issue includes moving persistence to ZK which seems a new scope to me.

**Comment by jdef** [comment]
v0.8 is somewhat ambitious. perhaps we should bump this into v0.7.2

On Tue, Dec 8, 2015 at 11:32 AM, Sergiusz Urbaniak <notifications@github.com

**Comment by sttts** [comment]
Agree. We should start filling v0.7.2 now anyway (next planning)

**Comment by s-urbaniak** [comment]
Agreed, let it be 0.7.2 then :-)

**Comment by sttts** [comment]
I guess this is related to https://github.com/kubernetes/kubernetes/pull/16830. Is this an option? I guess we also have to store our framework id somewhere.

**Comment by jdef** [comment]
for leader election yes that PR is related. still reviewing that PR.

for the framework ID, i'd really like to see us store that in etcd (via
apiserver) somewhere so that we don't have to rely on ZK

**Comment by jdef** [comment]
I think this is addressed by https://github.com/kubernetes/kubernetes/pull/18635
