### ISSUE TITLE
Fix kubernetes.io guide formatting (markdown rendering)

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#668]
xref: https://github.com/kubernetes/kubernetes/issues/18168

**Comment by karlkfi** [comment]
Resolving the dcos doc issue with https://github.com/kubernetes/kubernetes/pull/18181

**Comment by jdef** [comment]
upstream 18181 is closed. can we move this to "done"?

**Comment by karlkfi** [comment]
Nope.
Created cherry-pick: https://github.com/kubernetes/kubernetes/pull/18362
After that, gh-pages needs updating.

**Comment by karlkfi** [comment]
Cherry-pick merged. Working on gh-pages update.

**Comment by karlkfi** [comment]
gh-pages PR created: https://github.com/kubernetes/kubernetes/pull/18474

**Comment by karlkfi** [comment]
finally fixed!

**Comment by jdef** [comment]
sweet!
