### ISSUE TITLE
How to exit "km" process gracefully?

### ISSUE THREAD

**Issue by NanXiao** [mesosphere/kubernetes-mesos#679]
Hi all,

Now, after executing following command:   

    km apiserver --address=16.187.250.141 --etcd-servers=http://16.187.250.141:4001 --service-cluster-ip-range=10.10.10.0/24 --port=8888 --cloud-provider=mesos --cloud-config=mesos-cloud.conf --secure-port=0 --v=1

Or

    km controller-manager --master=16.187.250.141:8888 --cloud-provider=mesos --cloud-config=./mesos-cloud.conf --v=1

I can only use `kill -9` to exit `km` processes. Is there any method to exit `km` process gracefully?

Thanks very much!

Best Regards
Nan Xiao

**Comment by jdef** [comment]
I'm curious why you need to `kill -9` .. a simple `kill` works for me. Or
if I'm attached to the terminal CTRL-C does the trick.

**Comment by NanXiao** [comment]
@jdef : Sorry, the command should run as a daemon:  

    km apiserver \
      --address=${KUBERNETES_MASTER_IP} \
      --etcd-servers=http://${KUBERNETES_MASTER_IP}:4001 \
      --service-cluster-ip-range=10.10.10.0/24 \
      --port=8888 \
      --cloud-provider=mesos \
      --cloud-config=mesos-cloud.conf \
      --secure-port=0 \
      --v=1 >apiserver.log 2>&1 &
So the `CTRL + C` doesn't work.  

Anyway, there is not a out-of-box script which cause `km` exit except a simple `kill` command, right? Thx!

**Comment by karlkfi** [comment]
Last I checked, none of the kubernetes components actually had a "graceful" exit with teardown. Has that changed recently? Normally Golang itself will exit on ctr-c, unless it's specifically trapped by the code.
