### ISSUE TITLE
restrict pods to the resource constraints declared in their manifest

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#68]
Currently pods can declare cpu and memory constraints but we don't honor them. We should.

The current design maps a single mesos task to a k8s pod, which in reality represents multiple containers. One approach would be to place all pods managed by an executor into its container, growing and shrinking the resource constraints of the executor container on the fly to accommodate the pods that it's in charge of managing. That implies that we can actually control placement of the docker containers (well, their cgroup placement). Currently this is only possible by manually moving the processes from their default docker-determined cgroup to that of the executor.

There is a docker proposal on the table to allow for customizable cgroup placement: https://github.com/docker/docker/issues/8551 (related prototype tooling here: https://github.com/ibuildthecloud/systemd-docker).

Assuming that we *could* convince docker to honor custom cgroup placement (at container launch time), then we'd also need to convince/hack the kubelet to apply custom placement rules.

**Comment by jdef** [comment]
custom cgroup parents have landed in docker:
* https://github.com/docker/docker/pull/11428

**Comment by sushantk** [comment]
@jdef k8s now supports setting the parent cgroup for the kublet. Does this open the door to apply resource constraints?

**Comment by jdef** [comment]
Sure does. It's on our todo list.

**Comment by sttts** [comment]
There are not pod resource constraints right now in k8s, only by container. Hence, we can – maybe as a first step – easily sum up the values and put the sum into the `TaskInfo`. The launched docker containers have the container-wise limits applied by the kubelet.

**Comment by jdef** [comment]
resolved by https://github.com/GoogleCloudPlatform/kubernetes/pull/11230
