### ISSUE TITLE
Release v0.7.1-v1.1.3

### ISSUE THREAD

**Issue by s-urbaniak** [mesosphere/kubernetes-mesos#689]
Release steps
======

Tag
----

In  http://github.com/mesosphere/kubernetes

- [x] create or update a release branch with all necessary cherry-picks, e.g. `release-v0.7-v1.1`.

- [x] tag release branch with e.g. `v0.7.1-v1.1.3`

In  http://github.com/mesosphere/kubernetes-mesos

- [x] tag master branch of with e.g. `v0.7.1`

Build
------

In https://github.com/mesosphere/kubernetes-mesos/ images/docs:

- [x] `make clean`
- [x] build docker image: `make build`
- [x] push docker image: `make push`
- [x] push docker image: `make github-release-assets`
- [x] add release notes with the changes to the release description on http://github.com/mesosphere/kubernetes/releases

  Useful command to let latest mesosphere pull requests (e3188f6ee7007000c5daf525c8cc32b4c5bf4ba8 is the first common commit between the release branch and master):

```bash
git log --oneline --first-parent e3188f6ee7007000c5daf525c8cc32b4c5bf4ba8..upstream/master | \
grep -i mesos | sed 's,^\([^ ]*\).*#\([0-9]*\) from \(.*\)$,- [ ] http://github.com/kubernetes/kubernetes/pull/\2 \1 \3,' | \
sed '1!G;h;$!d'
```

In https://github.com/mesosphere/multiverse:

- [x] create release branch, e.g. `kubernetes-v0.7.1-v1.1.3`
- [x] update version in package.json, 
- [x] update config.json (docker image version)
- [x] create PR against `version-1.x`

In https://github.com/mesosphere/mesosphere-docs:

- [x] create PR:
  - use the current master version as a base and update all http links to point to the to be released version.
  - add a xref to the corresponding multiverse PR in the description
  - prefix the PR title with WIP/DO-NOT-MERGE until the multiverse PR merges.

Wait for Multiverse LGTM
---------------------

In http://github.com/mesosphere/mesosphere-docs:

- [x] merge multiverse

Once multiverse PR merges
---------------------

- [x] merge the http://github.com/mesosphere/mesosphere-docs changes and wait for
staging rebuild to happen (usually within 1h); 
- [x] verify that your version bump changes are good (manually walk through the steps in the entire doc)
- [x] file a ticket in JIRA to request a merge from staging to prod (link to the GH PR)
  - project: DOCS
  - owner: joel hamill
- [x] run and verify functionality of the k8s guestbook as a sanity check

**Comment by karlkfi** [comment]
Looks good! Release Milestone v0.7.1 Complete!
