### ISSUE TITLE
add roles support in dcos

### ISSUE THREAD

**Issue by s-urbaniak** [mesosphere/kubernetes-mesos#691]
Currently the DCOS image does not configure roles at all. "--mesos-framework-roles" and "--pod-default-roles" must be configured.

**Comment by s-urbaniak** [comment]
Relevant changes:
https://github.com/mesosphere/kubernetes-mesos/compare/v0.7.0...v0.7.1
https://github.com/mesosphere/multiverse/compare/version-1.x...kubernetes-v0.7.1-v1.1.3
https://github.com/mesosphere/mesosphere-docs/pull/297

**Comment by sttts** [comment]
Isn't this done?
