### ISSUE TITLE
Test v0.7.1-v1.1.3

### ISSUE THREAD

**Issue by s-urbaniak** [mesosphere/kubernetes-mesos#695]
- test ubercontainer failover onto another host when the original host fails (compare mesosphere/kubernetes-mesos#583)
  - [x] pods should keep running on other hosts
  - [x] pods on killed host should be restarted (if backed by rc)
  - [x] dns resolution should keep working: in busybox container `nslookup kube-ui.kube-system.svc.cluster.local`
  - [x] dns resolution should work for new services: launch nginx pod and service. Test in busybox container  `nslookup nginx.service.svc.cluster.local`.
- [x] deploy `examples/guestbook`. Try posting something in the web UI.
- [x] execute `dcos kubectl version`
- [x] do 2h+ soak testing w/ [hack/resizeFrontend.sh](https://github.com/mesosphere/kubernetes-mesos/blob/master/hack/resizingFrontend.sh)
- [x] smoke test Mesos-DNS via a busybox test container executing `nslookup kubernetes.mesos`.

**Comment by s-urbaniak** [comment]
Instructions on how to deploy v0.7.1
```
$ cd src
$ git clone https://github.com/mesosphere/multiverse
$ cd multiverse
$ git checkout v0.7.1-v1.1.3
$ cd ~
$ source /Users/sur/dcos/bin/env-setup && dcos help
```
Configure `.dcos/dos.toml` to point to the `multiverse` repo:
```
$ dcos config show package.sources
[
  "file:///Users/sur/src/multiverse",
  "https://github.com/mesosphere/universe/archive/version-1.x.zip"
]
$ dcos package update --validate
```
Follow instructions as per http://docs.mesosphere.com/services/kubernetes/#install

**Comment by jdef** [comment]
to test the v0.7.1-v1.1.3 branch you'll need a `dcos config set
package.sources ...` command that points to the right zip

**Comment by jdef** [comment]
`dcos config set package.sources '["https://github.com/mesosphere/multiverse/archive/kubernetes-v0.7.1-v1.1.3.zip"]'`

**Comment by jdef** [comment]
```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                READY     STATUS    RESTARTS   AGE
kube-system   kube-dns-v9-1o6m3   4/4       Running   0          <invalid>
kube-system   kube-ui-v2-5bqps    1/1       Running   0          <invalid>
```

? what's up with the `invalid`?

**Comment by s-urbaniak** [comment]
@jdef hmmm ... we have "works on my machine" situation, just installed on a vanilla ccm:
```
dcos kubectl get po --all-namespaces
NAMESPACE     NAME                READY     STATUS    RESTARTS   AGE
kube-system   kube-dns-v9-4en99   0/4       Pending   0          26s
kube-system   kube-ui-v2-4t359    1/1       Running   0          26s
```
The biggest difference is that I deploy from a local branch:
```
$ dcos config show package.sources
[
  "file:///Users/sur/src/multiverse",
  "https://github.com/mesosphere/universe/archive/version-1.x.zip"
]
```
Will try with the zip above...

**Comment by s-urbaniak** [comment]
Same result with the zip above:
```
$ dcos kubectl get po --all-namespaces
Download kubectl from http://pool-b63a-elasticl-zhirh02ezfs9-494708382.us-west-2.elb.amazonaws.com/service/kubernetes/static/darwin/kubectl.bz2
NAMESPACE     NAME                READY     STATUS    RESTARTS   AGE
kube-system   kube-dns-v9-8sax0   4/4       Running   0          36s
kube-system   kube-ui-v2-oozgh    1/1       Running   0          36s
```

**Comment by karlkfi** [comment]
FWIW, I really just needed the zip url. Here's what I use:

```
dcos config prepend package.sources https://github.com/mesosphere/multiverse/archive/kubernetes-v0.7.1-v1.1.3.zip
dcos package update --validate
dcos package install etcd
cat >/tmp/options.json <<EOF
{
  "kubernetes": {
    "etcd-mesos-framework-name": "etcd"
  }
}
EOF
dcos package install --options=/tmp/options.json kubernetes
```

**Comment by karlkfi** [comment]
We should make sure to cover all of the following:

- [ ] stable
- [ ] EarlyAccess
- [ ] testing/continuous

Check them off if you've tested them, and comment which DCOS version it was (see dcos ui).

**Comment by jdef** [comment]
OK .. so the `invalid` is **not** observed when using `dcos kubectl` but it **is** observed when I use a direct invocation of `kubectl` built from:
```sh
$ git status
On branch release-v0.7-v1.1
Your branch is up-to-date with 'origin/release-v0.7-v1.1'.
```
... am I building a kubectl binary from the wrong branch?

**Comment by karlkfi** [comment]
kube-ui dashboard doughnuts aren't working on v0.7.1 on a stable DCOS cluster.

EarlyAccess and testing/continuous DCOS clusters never came up at all for me (CCM or DCOS problem, I guess).

**Comment by karlkfi** [comment]
oinker-go tested successfully on v0.7.1 k8s on DCOS (except `/` proxy path redir bug with adminrouter, which isn't in stable yet).

**Comment by karlkfi** [comment]
Cody says the EarlyAccess and stable configurations are the same DCOS version atm.
I just tested k8s & oinker-go on EarlyAccess and it has the same problems stable did.

**Comment by karlkfi** [comment]
Tested on testing/continuous:
- kube-ui dashboard doughnuts aren't working
- `/` proxy path redir works (as expected)

**Comment by jdef** [comment]
didn't notice any new problems in soak testing (observed same docker hanging as for the 0.7 release, it's a docker thing)

**Comment by jdef** [comment]
@karlkfi are your broken doughnuts related/the same as #669?

**Comment by karlkfi** [comment]
Symptom is different. The rings don't show up all all, as opposed to showing up with zero utilization.

**Comment by s-urbaniak** [comment]
Some DNS resolutions don't seem to work inside a busybox container:
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "36000"
    name: busybox
```
Maybe I'm doing something wrong:
```
$ dcos kubectl get po
NAME             READY     STATUS    RESTARTS   AGE
busybox          1/1       Running   0          8m
nginx            1/1       Running   0          5m
nginxrep-eejg9   1/1       Running   0          32m
```
ssh into slave where the busybox pod runs:
```
$ dcos node ssh --master-proxy --slave=d2985e27-301e-4db0-85a9-68d1a29eb3e0-S3
$ docker exec -ti k8s_busybox.5f5a443_busybox_... /bin/sh
/ # nslookup kube-ui.kube-system.svc.cluster.local
Server:    10.10.10.10
Address 1: 10.10.10.10 ip-10-10-10-10.us-west-2.compute.internal

Name:      kube-ui.kube-system.svc.cluster.local
Address 1: 10.10.10.171 ip-10-10-10-171.us-west-2.compute.internal

/ # nslookup nginx.service.svc.cluster.local
Server:    10.10.10.10
Address 1: 10.10.10.10 ip-10-10-10-10.us-west-2.compute.internal

nslookup: can't resolve 'nginx.service.svc.cluster.local'
```

**Comment by jdef** [comment]
do you actually have a service running called nginx? your output only shows
a pod...

On Tue, Dec 15, 2015 at 7:30 AM, Sergiusz Urbaniak <notifications@github.com

**Comment by s-urbaniak** [comment]
@jdef *facepalm*, you're probably right

**Comment by s-urbaniak** [comment]
@sttts let's reiterate on the tests tomorrow, I could test everything except the Mesos DNS lookup, I think the entry too look up for is wrong. I updated the test template https://github.com/mesosphere/kubernetes-mesos/wiki/Test-Template where corrections needed to be made.

**Comment by s-urbaniak** [comment]
tested everything finally
