### ISSUE TITLE
Configure roles via annotations rather than labels

### ISSUE THREAD

**Issue by s-urbaniak** [mesosphere/kubernetes-mesos#697]
As we found out, '*' cannot be set as a label value in the kubernetes yaml descriptor.

Furthermore it makes more sense to configure roles via annotations rather than labels.

**Comment by sttts** [comment]
Where is the PR for this?

**Comment by sttts** [comment]
https://github.com/kubernetes/kubernetes/pull/18618

**Comment by sttts** [comment]
Waits for https://github.com/mesosphere/kubernetes-mesos/issues/678 to be merged.

**Comment by sttts** [comment]
https://github.com/kubernetes/kubernetes/pull/18618
