### ISSUE TITLE
Document dogfooding deployment

### ISSUE THREAD

**Issue by s-urbaniak** [mesosphere/kubernetes-mesos#700]
The deployment of kubernetes.mesosphere.com is undocumented. Document it on the wiki.

**Comment by sttts** [comment]
Removed v0.7.1. This not release related. When closed within the v0.7.1 timeframe, assign the milestone when closing (as discussed in the last planning).

**Comment by s-urbaniak** [comment]
replaced by https://github.com/mesosphere/kubernetes-mesos-private/issues/69
