### ISSUE TITLE
Conformance of Kubernetes on DCOS with Container IPs

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#706]
This is a placeholder ticket for issues to fix towards this goal. We have documentation of conformance, but not conformance itself. 

This ticket is open for discussion about priority.

Related:
- conformance documentation: https://github.com/mesosphere/kubernetes-mesos/issues/607
- investigate conformance with Container IPs: https://github.com/mesosphere/kubernetes-mesos/issues/651
- SSL and service accounts: https://github.com/mesosphere/kubernetes-mesos/issues/409, https://github.com/mesosphere/kubernetes-mesos/issues/535

**Comment by karlkfi** [comment]
did you mean "without Container IPs"?

**Comment by sttts** [comment]
Actually it was supposed to be the counterpart to https://github.com/mesosphere/kubernetes-mesos/issues/651, i.e. "with container IPs".
