### ISSUE TITLE
Propose kube-ui fix upstream

### ISSUE THREAD

**Issue by s-urbaniak** [mesosphere/kubernetes-mesos#712]
In v0.7.1 we currently use a custom built kube-ui which fixes kube-ui not displaying on nodes having no kubelet/executor running.

This bugfix should be PR'ed upstream.

xref https://github.com/mesosphere/kubernetes-mesos/issues/703#issuecomment-165811134

**Comment by sttts** [comment]
The first two commits are in this PR against upstream: https://github.com/kubernetes/kube-ui/pull/48

The last commit about the comparison with `KubeletReady` is not. We have to decide what to do with that one. Without that commit the cAdvisor view is working as well, but a number of 503s are visible in the website inspector because the cAdvisor does not answer on the unready hosts.

**Comment by jdef** [comment]
ping'd 3 days ago to get a review on the kube-ui changes

**Comment by jdef** [comment]
@sttts the above PR has landed. assume that now we need to ask google to rebuild kube-ui and then we can transition back to stock?

**Comment by sttts** [comment]
@jdef yes, they have to push a new build.

**Comment by jdef** [comment]
file issue to track completion of new v5 build: https://github.com/kubernetes/kubernetes/issues/20285

**Comment by jdef** [comment]
v5 has landed upstream!

**Comment by jdef** [comment]
I'm inclined to not worry about the 503's for now. Dashboard (the next UI) will be ready soon and is (supposedly) 1.1 compat - we'll probably want to upgrade to that and in the process probably uncover a new batch of compatibility/assumption related problems.

**Comment by jdef** [comment]
UGH! tested v5 without the 3rd commit and the doughnuts are missing. will attempt to build a custom image with the "3rd commit" to attempt to resolve: https://github.com/sttts/kube-ui/commit/d235186e5479341f842fdf18ce4765ebebdd1c94

**Comment by jdef** [comment]
rebuilt with command:
```sh
$ make TAG=v5 PREFIX=mesosphere IMAGE=k8sm-ui GCLOUD=
```

**Comment by jdef** [comment]
fixes incorporated here: https://github.com/mesosphere/kube-ui/pull/1

suspect that the `npn run build` process was not executed properly for the stock v5 release

**Comment by jdef** [comment]
changes incorporated directly into release branch here:
```
commit 143715248c85d47eb4cf25ab62db85c634da6766
Author: James DeFelice <james@mesosphere.io>
Date:   Sat Jan 30 00:30:51 2016 +0000

    use mesosphere-patched kube-ui:v5 image
```
