### ISSUE TITLE
Fix Job conformance tests on master

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#713]
Some Jobs conformance tests are failing on master. One of them hangs forever.

```
Kubectl client Kubectl run --rm job
  should create a job from an image, then delete the job [Conformance]
```

See #651 for more details.

**Comment by jdef** [comment]
this test is blocking for hours at a time, and needs a more reasonable timeout - this should unblock conformance in TC

**Comment by jdef** [comment]
xref https://github.com/kubernetes/kubernetes/pull/19410

**Comment by jdef** [comment]
there's a bigger problem here: our custom controller manager doesn't include a job controller

**Comment by sttts** [comment]
Just instantiate it? Having this duplicated code is a mess.

**Comment by jdef** [comment]
yes i'll be sync-ing the controller code today

**Comment by jdef** [comment]
controller-manager sync has landed: https://github.com/kubernetes/kubernetes/pull/19412

just waiting for the kubectl e2e test timeout changes to be LGTM'd and merged

**Comment by jdef** [comment]
cherry-picked into https://github.com/mesosphere/kubernetes/pull/55
