### ISSUE TITLE
Copy test steps into wiki

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#721]
From https://github.com/mesosphere/kubernetes-mesos/issues/695 to https://github.com/mesosphere/kubernetes-mesos/wiki/Test-Template.

The description should be verbose enough such that everybody of us can redo them for the next release.

**Comment by s-urbaniak** [comment]
LGTM, I'll add an entry for roles testing.

**Comment by s-urbaniak** [comment]
Added roles support test, @sttts PTAL https://github.com/mesosphere/kubernetes-mesos/wiki/Test-Template/b314431c4ff84620f71daf6fb396081053150691

**Comment by jdef** [comment]
:+1:
