### ISSUE TITLE
Extract keygen container image

### ISSUE THREAD

**Issue by karlkfi** [mesosphere/kubernetes-mesos#723]
The mesosphere/kubernetes-mesos-keygen container is generic enough to be useful for DCOS, and other Kubernetes cluster deployments. We want to extract it from the upstream k8s repo to make it easier to maintain independently.

This is a prerequisite to making Kubernetes on DCOS use SSL.

Part of the work was already done as part of a weekend project: https://github.com/kubernetes/kubernetes/pull/19241

**Comment by karlkfi** [comment]
Source: https://github.com/mesosphere/kubernetes-keygen)
DockerHub (automated build): https://hub.docker.com/r/mesosphere/kubernetes-keygen/

**Comment by jdef** [comment]
@karlkfi the upstream PR has merged, does that mean that this can be closed?

**Comment by karlkfi** [comment]
yup! hope it's useful! I don't remember if there was another ticket to actually use it for the dcos cert gen.
