### ISSUE TITLE
k8sm release from v1.1.5 on kubernetes/kubernetes

### ISSUE THREAD

**Issue by ravilr** [mesosphere/kubernetes-mesos#744]
We are seeing socket leaks in userspace kube-proxy which seems to be fixed in v1.1.5:
https://github.com/kubernetes/kubernetes/pull/19463
Can you please release k8sm 0.7.1 upon v1.1.5 of kubernetes. Thanks.

**Comment by jdef** [comment]
i've started hacking on branch that's rebased to v1.1.5: https://github.com/mesosphere/kubernetes/pull/55

**Comment by jdef** [comment]
marking as dup of issue I mentioned in the previous comment
