### ISSUE TITLE
K8S not scaling on DCOS cluster.

### ISSUE THREAD

**Issue by thilinapiy** [mesosphere/kubernetes-mesos#747]
I have 15 node dcos cluster with K8S package installed. There are 3 K8S doughnuts active among 15. When K8S cluster hit its limit its not using other mesos nodes to get resources.

I need to add more nodes to this K8S cluster. Is this a configurable thing or it should happen automatically? Or anything else I can do?

Also I can see following on empty doughnuts nodes when I view the K8S api /nodes json

    {
      "metadata": {
       ...
        "labels": {
          "kubernetes.io/hostname": "<IP>"
        }
      },
      "spec": {
        "externalID": "<IP>"
      },
      "status": {
        "phase": "Pending",
        "conditions": [
          {
            "type": "Ready",
            "status": "True",
            "lastHeartbeatTime": "2016-01-27T21:47:53Z",
            "lastTransitionTime": "2016-01-19T21:59:11Z",
            "reason": "SlaveReady",
            "message": "mesos reports ready status"
          }
        ],
        "daemonEndpoints": {
          "kubeletEndpoint": {
            "Port": 0
          }
        },
        "nodeInfo": {
          "machineID": "",
          "systemUUID": "",
          "bootID": "",
          "kernelVersion": "",
          "osImage": "",
          "containerRuntimeVersion": "",
          "kubeletVersion": "",
          "kubeProxyVersion": ""
        }
      }
    }

**Comment by thilinapiy** [comment]
![k8s-2](https://cloud.githubusercontent.com/assets/998499/12646003/a2d7b366-c59b-11e5-9798-a01ec82a99df.png)

**Comment by jdef** [comment]
Your node json implies that kubelet isn't running on the slave node;
k8s-mesos "sees" the slave in the cluster but for some reason tasks are not
being launched there.

Is this a homebrew dcos-like cluster? Is this on AWS? How was this DCOS
cluster put together, and what version of mesos is running on it?

**Comment by tkrausjr** [comment]
This was an Prem installation of DCOS 1.6 so its running Mesos 0.26

**Comment by jdef** [comment]
Thanks for the info. We haven't certified that k8s/dcos actually runs on
that version of DCOS/mesos yet. In fact, I've observed problems running
k8s/dcos on DCOS 1.6/mesos-0.26. I'm putting together an RC this week for
v0.7.2 that should be compatible.

**Comment by thilinapiy** [comment]
We found the culprit. It was a proxy settings that block requests to the 'http://kubernetes.marathon.mesos:25504/km' URL.

When I check the mesos tasks for some reason I saw that there are some failed tasks with name '*pod*'. So I view the 'stderr' and it gave something as follows and the 'km' log showed some proxy thing as well. 

> Downloading resource from 'http://kubernetes.marathon.mesos:25504/km' to '/var/lib/mesos/slave/slaves/2e4d1d29-2cab-49d2-a1cb-a0a8f22345f3-S21/frameworks/2e4d1d29-2cab-49d2-a1cb-a0a8f22345f3-0005/executors/6f8fdd082fc306fc_k8sm-executor/runs/cf61a391-da8b-4673-b549-e18ca1e6c04d/km'
> Failed to fetch 'http://kubernetes.marathon.mesos:25504/km': Error downloading resource, received HTTP return code 502

We add the *.mesos to no_proxy section and now its working. 

By the way we had 100% disk usage in mount that had '/var/lib/docker' directory. Then we ran following commands and got ~20GB free space. 

```
docker rm `docker ps -a | grep -i exited | awk '{print $1}' `
docker rmi `docker images | grep none  | awk '{print $3}' `
```

Do we have any GC (garbage collection) mechanism for dead docker and to orphan images? Raw K8S says that It has some default high/low values to deal with things like this. (--image-gc-high-threshold/--image-gc-low-threshold). 

Thanks for the help .. !!

**Comment by jdef** [comment]
Looks like GH lost my reply:

> Glad you were able to isolate the proxy issue.
>
GC thresholds are documented here: https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/admin/kubelet.md; I don't believe that we change them.
>
upstream, related:
>
* https://github.com/kubernetes/kubernetes/issues/17994
* https://github.com/kubernetes/kubernetes/issues/16563
