### ISSUE TITLE
update mesosphere docs re: version bump from v0.7.1 to v0.7.2

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#748]
... it no longer requires an /api suffix

tracking this internally as DOCS-568

**Comment by jdef** [comment]
xref #632

**Comment by jdef** [comment]
no work to do here since k8s mesosphere docs use `dcos kubectl` subcommand

**Comment by jdef** [comment]
oops, closed too soon. there's links at the bottom of the docs that reference a specific release of k8s/dcos: https://docs.mesosphere.com/manage-service/kubernetes/

**Comment by jdef** [comment]
Specifically, these links at the bottom of the page:
* Documentation
* Architecture
* Known Issues

**Comment by jdef** [comment]
and this:

> The current Kubernetes alpha DCOS package v0.7.1-v1.1.3 is based on Kubernetes v1.1.3. For more information see the Kubernetes-Mesos project on GitHub. There are behavioral differences between the Kubernetes DCOS service and standalone Kubernetes, notably the behavior of the scheduler.

**Comment by jdef** [comment]
and this (which appears incorrectly formatted to begin with):
> $ dcos package list NAME VERSION APP COMMAND DESCRIPTION kubernetes v0.7.1-v1.1.3-alpha /kubernetes kubernetes Kubernetes is an open source system for managing containerized applications across multiple hosts, providing basic mechanisms for deployment, maintenance, and scaling of applications.

**Comment by sascala** [comment]
Ta-da! https://docs.mesosphere.com/manage-service/kubernetes/

**Comment by jdef** [comment]
Thanks!
