### ISSUE TITLE
support resource shapes if/when they show up in k8s

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#76]
via @ConnorDoyle : https://github.com/GoogleCloudPlatform/kubernetes/pull/617

**Comment by jdef** [comment]
xref https://github.com/GoogleCloudPlatform/kubernetes/issues/168

**Comment by jdef** [comment]
closely related to #68

**Comment by karlkfi** [comment]
@jdef does this still need to be open? the initial linked task is closed. What's a resource "shape" anyway?

**Comment by jdef** [comment]
we currently support the following:

- cpu and memory limits of a pod's containers define the resource shape of the pod

i think it's reasonable to close this out. we can open a new ticket if resource shape requirements change down the road.
