### ISSUE TITLE
cadvisor docker stats not working in v0.7.2-v1.15 release

### ISSUE THREAD

**Issue by ravilr** [mesosphere/kubernetes-mesos#766]
@jdef 
version : v0.7.2-v1.1.5

kubelet embedded cadvisor reporting docker container stats has stopped working since we upgraded to v0.7.2-v1.1.5 (from v0.7.0-v1.1.1). 

kubelet stats are exposed via http on port 10255.
http://mesos-slave1.host.com:10255/stats/kube-system/kube-dns-v10-2-yrmw0/6d14f56e-ca21-11e5-a652-fa163eee7610/etcd
returns 'Internal Error: unable to find Docker container "0df7cae297149a47684df7360b164329e40287f824cacfc161f671f8c38310bc' even though the container id exists in the system.

http://mesos-slave1.host.com:4194/ (cadvisor ui) also doesn't list any docker containers in it UI. 

Not sure if this is an issue in the upstream or something to do with they way kubelet-executor launches kubelet. Any idea?

heapster pod calls the above kubelet stats port for cluster stats aggregation, and because of this issue, heapster stats for pods are also empty. 

this is where it is failing:
https://github.com/mesosphere/kubernetes/blob/v0.7.2-v1.1.5/pkg/kubelet/server.go#L1022
https://github.com/google/cadvisor/blob/v0.19.3.2/manager/manager.go#L526

**Comment by ravilr** [comment]
apparently, this turns out to be an upstream issue in cadvisor. there seems to be a change related to how cadvisor recognizes docker managed containers in systemd based systems that went in around cadvisor 0.19.{1-3} release :
https://github.com/google/cadvisor/pull/821
the above change seems to have broken use cases where docker containers are launched with --cgroup_parent, which the mesos executor does. 

adding --nosystemd=true flag to the kubelet executor appears to bring back the cadvisor docker container stats working along with the heapster stats(atleast on RHEL system).

**Comment by jdef** [comment]
#460

**Comment by jdef** [comment]
see the `contain-pod-resources` flag for the scheduler. we added this because k8s on dcos ran into a similar problem w/ respect to mesos/docker/systemd interaction

**Comment by jdef** [comment]
dup of #460, closing out

**Comment by ravilr** [comment]
@jdef, we are running with --contain-pod-resources=true and everything seems to work well. but, in newer cadvisor version, they introduced --nosystemd flag to support setups using --cgroup-parent: https://github.com/google/cadvisor/pull/960.
Can we add support for this flag in kubelet-executor?

**Comment by jdef** [comment]
tracking support for that flag in #775
