### ISSUE TITLE
TODO: Clean up go-binding, upgrade protocol, replace goprotobuf

### ISSUE THREAD

**Issue by yifan-gu** [mesosphere/kubernetes-mesos#8]
Since the go-binding is written long time ago, some of the protobuf messages are depreciated(e.g. `LaunchTask` with just one `OfferID`), so we should do a cleanup to make it update.
Also we would want to replace `goprotobuf` with `gogoprotobuf` for faster encoding/decoding speed.

**Comment by jdef** [comment]
pure bindings support has been merged to master, the pure bindings (currently) is using gogoprotobuf. closing this out
