### ISSUE TITLE
determine alignment between mesos slave roles/attributes and k8s minion labels

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#81]
In the upstream [release notes](https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.5) there's mention of "Restrict which minion a pod schedules on based on predicate tested agains minion labels.":

* https://github.com/GoogleCloudPlatform/kubernetes/pull/1946
* https://github.com/GoogleCloudPlatform/kubernetes/pull/2007

Is there any overlap between minion labels and slave roles or slave attributes? For example, would it be interesting to schedule certain pods only on slaves that define a matching attribute?

**Comment by jdef** [comment]
example of constraint-based scheduling from old "demo" branch, thanks @adam-mesos!
```patch
+	label := t.Pod.Labels["cluster"]
+	if label != "" {
+		var label_match = false
+		log.V(2).Infof("Matching against 'cluster' label: %v\n", label)
+		for _, attribute := range offer.Attributes {
+			log.V(3).Infof("attr: %v (%v) : %v\n", attribute.GetName(), attribute.GetType(), attribute.GetText().GetValue())
+			if attribute.GetName() == "cluster" {
+				attr := attribute.GetText().GetValue()
+				if attr == label {
+					log.V(2).Infof("Attribute cluster:'%v' == label cluster:'%v'\n", attr, label)
+					label_match = true
+					break
+				} else {
+					log.V(3).Infof("Attribute cluster:'%v' != label cluster:'%v'\n", attr, label)
+				}
+			}
+		}
+		if label_match == false {
+			log.V(2).Infof("Could not schedule pod %s: no matching attribute for label cluster=%v", t.Pod.ID, label)
+			return false
+		}
+	}
+
```

**Comment by jdef** [comment]
the k8s node controller is responsible for constructing api.Node objects from cloud instances. it seems like the right place to decorate the node with labels. perhaps the cloud provider API should provide a func that the controller can call in order to apply labels?

https://github.com/GoogleCloudPlatform/kubernetes/blob/v0.11.0/pkg/cloudprovider/controller/nodecontroller.go#L366

**Comment by adam-mesos** [comment]
Also note that Mesos now provides Task Labels, which could map well to pod
labels.
https://issues.apache.org/jira/browse/MESOS-2120
You may also be interested in the new service DiscoveryInfo, to provide
port names/protocols for service discovery services to consume (from
state.json)
https://issues.apache.org/jira/browse/MESOS-2150

**Comment by jdef** [comment]
@adam-mesos task labels are interesting for sure. their usefulness, w/ respect to clients that want to discover kubernetes services, is somewhat questionable. in kubernetes a service is decoupled from the pod (or pods) that back it. the backing pods often have no idea what declared services they may be supporting.

Christos and I have been chatting about some enhancements to mesos-dns that would allow k8s services to be more easily exposed. I've been sketching out some ideas here: https://github.com/mesosphere/mesos-dns/pull/110

**Comment by jdef** [comment]
xref #126

**Comment by sttts** [comment]
The attribute part of this issue is covered by https://github.com/mesosphere/kubernetes-mesos/issues/452

**Comment by sttts** [comment]
Roles are covered by https://github.com/mesosphere/kubernetes-mesos/issues/482

**Comment by jdef** [comment]
closing this out since it's addressed by the aforementioned tickets
