### ISSUE TITLE
About Managing DCOS Services - Kubernetes Docs Link

### ISSUE THREAD

**Issue by wenhongqiang** [mesosphere/kubernetes-mesos#810]
Hi all
   I've found something gone. pls check  Managing DCOS Services - Kubernetes this hyperlink

![screen shot 2016-12-01 at 4 40 01 pm](https://cloud.githubusercontent.com/assets/23624404/20787092/f3e9a5f2-b7e4-11e6-90e3-f2998bc9dea1.png)

any correct link can be updated?

Thanks a lot

**Comment by joel-hamill** [comment]
This content is out of date and no longer accurate - it has been removed. There currently is not a Kubernetes DC/OS service in Universe.

**Comment by wenhongqiang** [comment]
@joel-hamill  any plans for that?

**Comment by jdef** [comment]
https://dcos-community.slack.com/messages/kubernetes/
